### ISSUE TITLE
[BUG] MSSQL jdbc driver wont work on ibm websphere

### ISSUE THREAD

**Issue by frikit** [microsoft/mssql-jdbc#1061]
## Driver version

Any existing jdbc verson witch compatible with jre8

## Client Operating System

Windows + IBM Websphere 9.0.11

Host Operating System is Windows Server 2016, version 10.0
Java version = 1.8.0_211, Java Runtime Version = 8.0.5.35 - pwa6480sr5fp35-20190418_01(SR5 FP35), Java Compiler = j9jit29, Java VM name = IBM J9 VM

## Problem description

1. Expected behaviour:
Start and working
2. Actual behaviour:
Fail to start webapp
3. Error message/stack trace:
Caused by: java.lang.LinkageError: loading constraint violation when overriding method "java/sql/SQLXML.getSource(Ljava/lang/Class;)Ljavax/xml/transform/Source;" during creation of class "com/microsoft/sqlserver/jdbc/SQLServerSQLXML": loader "com/ibm/ws/classloader/CompoundClassLoader@4b784444" of class "com/microsoft/sqlserver/jdbc/SQLServerSQLXML" and loader "com/ibm/oti/vm/BootstrapClassLoader@60a8e215" of class "java/sql/SQLXML" have different types for the method signature
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:391)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:360)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:154)
	at com.ibm.ws.classloader.CompoundClassLoader._defineClass(CompoundClassLoader.java:858)
	at com.ibm.ws.classloader.CompoundClassLoader.localFindClass(CompoundClassLoader.java:766)
	at com.ibm.ws.classloader.CompoundClassLoader.loadClass(CompoundClassLoader.java:607)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:865)
	at com.microsoft.sqlserver.jdbc.JavaType.<clinit>(DataTypes.java:582)
	at com.microsoft.sqlserver.jdbc.Util$1.<clinit>(Util.java:868)
	at com.microsoft.sqlserver.jdbc.Util.shouldHonorAEForRead(Util.java:800)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet$1CursorInitializer.onColMetaData(SQLServerResultSet.java:239)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:99)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.<init>(SQLServerResultSet.java:335)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet42.<init>(SQLServerResultSet42.java:35)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1684)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:903)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:796)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7535)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2438)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:208)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:183)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeQueryInternal(SQLServerStatement.java:703)
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getResultSetFromInternalQueries(SQLServerDatabaseMetaData.java:252)
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getTypeInfo(SQLServerDatabaseMetaData.java:1534)
4. Any other details that can be helpful:
Classloading is set parent last in IBM

## Reproduction code

I don;t have exact code snippet but it look like it fail on startup not on accessing exact column of xml type in database

Thanks, If you need more info ask me.

**Comment by rene-ye** [comment]
Hi @frikit, I see that this issue supposedly occurs with any version of the driver, but can you provide the version that you're using/is directly affecting  you. If you don't have a direct code snippet, can you see if you can reproduce it in a separate project? If it fails on startup this shouldn't be difficult.

**Comment by cheenamalhotra** [comment]
Related Discussions: https://www.ibm.com/developerworks/community/forums/html/topic?id=77777777-0000-0000-0000-000014455516

> Caused by: java.lang.LinkageError: loading constraint violation when overriding method "java/sql/SQLXML.getSource(Ljava/lang/Class;)Ljavax/xml/transform/Source;" during creation of class "com/microsoft/sqlserver/jdbc/SQLServerSQLXML": loader "**com/ibm/ws/classloader/CompoundClassLoader**@4b784444" of class "com/microsoft/sqlserver/jdbc/SQLServerSQLXML" and loader "**com/ibm/oti/vm/BootstrapClassLoader**@60a8e215" of class "java/sql/SQLXML" have different types for the method signature

It doesn't look like a driver problem. Probably Java classes loaded are of different version by both classloaders.

**Comment by frikit** [comment]
In folder libs existing only one mssql jdbc driver, now version is 7.0.0-jre8, but i tried all libraries existing in mvn central which is with -jre8 or -jre7, to make a small project is harder than it look like , I will try maybe next week, 

**One more moment is about IBM JDK, for some reason for e.g. ojdbc work well I can't figure out why**

Version is ojdbc8-12.2.0.1 work well

**Comment by cheenamalhotra** [comment]
@frikit 
Do you have any update on this issue?

**Comment by frikit** [comment]
We hold support for WAS, now I dont have time to create working sample,

I think problem can be solved by looking on odbc and mssql on classes which implement java/sql/SQLXML and specific on method java/sql/SQLXML.getSource(Ljava/lang/Class;)Ljavax/xml/transform/Source , I suppose byte code will be different which belong to method signature

**Comment by cheenamalhotra** [comment]
Hi @frikit 

I'm closing the issue as we cannot reproduce the same and haven't heard any similar issues from any IBM customers. To me it seems to be classloader conflict issue in your environment.

**Comment by pavanbnv** [comment]
`Caused by: java.lang.LinkageError: loading constraint violation when overriding method "java/sql/SQLXML.getSource(Ljava/lang/Class;)Ljavax/xml/transform/Source;" during creation of class "com/microsoft/sqlserver/jdbc/SQLServerSQLXML": loader "com/ibm/ws/classloader/CompoundClassLoader@4b784444" of class "com/microsoft/sqlserver/jdbc/SQLServerSQLXML" and loader "com/ibm/oti/vm/BootstrapClassLoader@60a8e215" of class "java/sql/SQLXML" have different types for the method signature`

The problem is with javax.xml.transform.Source in "com/ibm/ws/classloader/CompoundClassLoader". CompoundClassLoader represents the jars of application. The class loaders list order, when parent last setting is used, will be 1. application jars, 2. jvm jars, 3. shared library jars 4. ibm WAS server jars. The 1. application jars is loaded by CompoundClassLoader. Usually, CompoundClassLoader loads application jars and jvm jars together. When it loads [com/microsoft/sqlserver/jdbc/SQLServerSQLXML], it has to load 1. [java/sql/SQLXML] and 2. [javax/xml/transform/Source]. As mentioned in the error the signature of the method getSource is invalid. The signature of the method getSource is 
`public abstract <T extends Source> T getSource(Class<T> paramClass)`. In this signature it refers to Source. So, here the byte code of Source defined in SQLServerSQLXML class which is loaded in CompoundClassLoader and byte code of Source loaded in BootstrapClassLoader does not match. So, we have two different versions of Source classes in classpath. Please verify your classpath that resolves the issue.
