### ISSUE TITLE
DatabaseMetaData#getImportedKeys() fails on Azure SQL Data Warehouse

### ISSUE THREAD

**Issue by FejfarKamil** [microsoft/mssql-jdbc#1145]
## Driver version
7.4.1

## SQL Server version
Microsoft Azure SQL Data Warehouse - 10.0.9999.0 Aug 16 2019 21:18:18 Copyright (c) Microsoft Corporation

## Client Operating System
Windows 10 Pro

## JAVA/JVM version
java version "1.8.0_221

## Problem description
We want to obtain imported keys on Azure SQL Data Warehouse.

`DatabaseMetaData#getImportedKeys()` calls `DECLARE @jdbc_temp_fkeys_result table (...`, that fails, because variable of a table type is not supported on Azure SQL Data Warehouse (https://docs.microsoft.com/en-us/sql/t-sql/language-elements/declare-local-variable-transact-sql?view=sql-server-2017).

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Parse error at line: 1, column: 33: Incorrect syntax near 'table'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1624)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:594)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2979)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:446)
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.executeSPFkeys(SQLServerDatabaseMetaData.java:1026)
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getCrossReference(SQLServerDatabaseMetaData.java:920)
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getImportedKeys(SQLServerDatabaseMetaData.java:992)

**Comment by lilgreenbird** [comment]
Hi @FejfarKamil, 
Can you please tell us what you are expecting from this call? SQL Data Warehouse does not support foreign keys so the fix would be to return an empty result set. Would that work for you?
