### ISSUE TITLE
[QUESTION] Spring Data @Query and always encrypted

### ISSUE THREAD

**Issue by RomainWilbert** [microsoft/mssql-jdbc#1298]
## Question
I have a Spring data app with custom queries such as 
`@Query("SELECT DISTINCT f.folder FROM Folder f " +
            "JOIN f.manages m " +
            "WHERE f.folder like %:folderId% " +
            "AND m.manageCode in :manageCodes")
    List<String> findFoldersIdForMatchingFolderId(@Param("folderId") String folderId, @Param("manageCodes") List<String> manageCodes);
`
folder is an encrypted column. When I run the query, I have the following error :
`Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Encryption scheme mismatch for columns/variables 'folder', 'folder'. The encryption scheme for the columns/variables is (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'CEK_Auto1', column_encryption_key_database_name = 'cpa-dev-02-db') and the expression near line '1' expects it to be (encryption_type = 'PLAINTEXT') (or weaker).
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:600)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:522)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7225)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3053)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQueryInternal(SQLServerPreparedStatement.java:458)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.getParameterEncryptionMetadata(SQLServerPreparedStatement.java:868)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:570)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:522)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7225)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3053)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:444)`

Is this because of the "like" criteria ? I guess it has no sense to pass an encrypted value to the server when doing "like" criteria on an encrypted column.

**Comment by RomainWilbert** [comment]
Is Always encrypted with secured enclaves the solution to this ?

**Comment by rene-ye** [comment]
Whenever you receive a mismatch error when using AE, it's usually because there wasn't enough information specified. E.g. nvarchar(15) and nvarchar are not compatible when AE is on, length and precision must match. Datatypes that are also usually compatible and can be silently cast to each other are also no longer compatible. Whether Always Encrypted with Secure Enclaves solves this issue goes on a case by case basis, the feature does not cover all scenarios. Also, using a framework will usually obfuscate what the underlying driver is sending, and we recommend contacting framework creators for workarounds.

**Comment by ulvii** [comment]
Hi @RomainWilbert ,
Do you need further assistance on this?

**Comment by rene-ye** [comment]
Closing due to inactivity.
