### ISSUE TITLE
ERROR: Could not fetch the SequenceInformation from the database

### ISSUE THREAD

**Issue by malm66** [microsoft/mssql-jdbc#1318]
## Driver version
mssql-jdbc-8.2.2.jre11

## SQL Server version
Microsoft SQL Server 2014 (SP3-CU4) (KB4500181) - 12.0.6329.1 (X64) 
 Jul 20 2019 21:42:29 
 Copyright (c) Microsoft Corporation
 Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

## Client Operating System
Windows 10

## JAVA/JVM version
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Corretto-11.0.7.10.1 (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.7.10.1 (build 11.0.7+10-LTS, mixed mode)

## Problem description
1. Expected behaviour:
Persistence context can be created

2. Actual behaviour:
A ClassCast Exception is thrown

3. Error message/stack trace:
`
ERROR: Could not fetch the SequenceInformation from the database
java.sql.SQLException: An SQLException was provoked by the following failure: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:74)
	at com.mchange.v2.c3p0.impl.NewPooledConnection.handleThrowable(NewPooledConnection.java:505)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getLong(NewProxyResultSet.java:491)
	at org.hibernate.tool.schema.extract.internal.SequenceInformationExtractorLegacyImpl.resultSetStartValueSize(SequenceInformationExtractorLegacyImpl.java:129)
	at org.hibernate.tool.schema.extract.internal.SequenceInformationExtractorLegacyImpl.extractMetadata(SequenceInformationExtractorLegacyImpl.java:59)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentImpl.sequenceInformationList(JdbcEnvironmentImpl.java:403)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentImpl.<init>(JdbcEnvironmentImpl.java:268)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:114)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:152)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:286)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:243)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:176)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:118)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1214)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1245)
	at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:56)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)
	at au.net.synergy.wts.domain.dao.jpa.JpaUtil.<clinit>(JpaUtil.java:59)
	at au.net.synergy.wts.domain.dao.jpa.JpaTransactionManager.beginTransaction(JpaTransactionManager.java:23)
	at au.net.synergy.wts.domain.dao.jpa.JpaDataAccessCommandHandler.executeCommand(JpaDataAccessCommandHandler.java:54)
	at au.net.synergy.wts.business.shared.services.helpers.EnumMapper.initialise(EnumMapper.java:190)
	at au.net.synergy.wts.business.Activator.start(Activator.java:33)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:843)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:835)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:792)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1015)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getLong(SQLServerResultSet.java:2340)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getLong(NewProxyResultSet.java:477)
	... 43 more
`

4. Any other details that can be helpful:

This is a working application we are trying to port to Java 11. The JPA provider is hibernate-core-
5.4.14.Final
Identical code works fine with Java 8, sqljdbc42, and hibernate-core-5.0.0.Final

**Comment by rene-ye** [comment]
Hi @malm66, this seems to be a hibernate error message. Can you give more details regarding the use case; what datatype are you trying to retrieve from the column, the table structure, etc. Or if you could provide a reproduction without using Hibernate that'd be even better.

**Comment by malm66** [comment]
Hi @rene-ye, I think this is a defect in Hibernate. It tries to read sequence schema information, e.g. something like SELECT * FROM INFORMATION_SCHEMA.SEQUENCES, and then accesses all the numerical columns using getLong() even though they are of varying type depending on how the sequence is defined. It works when all sequences are defined as being of type long but the moment you have sequences of type int it breaks during the schema inspection phase in Hibernate. I think it can be safely said that this is a Hibernate bug.

**Comment by wumpz** [comment]
On JDK 14, using JDBC 7.4.1.jre12, 7.2.2.jre11,  7.2.2.jre8  produces the same error, but using JTDS 1.3 (very old) works. 

So it seems this is a problem with the combination of new Hibernate, JDBC, JDK versions.

**Comment by malm66** [comment]
Hi @wumpz, this is a defect in hibernate as explained further above. I worked around this by implementing a custom hibernate dialect that works around the problem.

**Comment by wumpz** [comment]
@malm66 Did you already filed an Hibernate issue? I have no account there. However it is strange, that Hibernate with the good old JTS driver does work without this issue.

**Comment by wumpz** [comment]
@malm66 just now I found the (one) issue within Hibernates issue tracker. So thx for clarification.

**Comment by wumpz** [comment]
@malm66 now I understood why it's works. Thx for sharing your patch.
