### ISSUE TITLE
Read Timeout after 120sec for a usual 3sec query

### ISSUE THREAD

**Issue by Tetradeus** [microsoft/mssql-jdbc#1324]
## Driver version

8.1.1.jre11-preview OK
8.2.0.jre11 KO
8.2.2.jre11 KO

## SQL Server version
Microsoft SQL Azure (RTM) - 12.0.2000.8 
	Feb 26 2020 10:26:43 
	Copyright (C) 2019 Microsoft Corporation

## Client Operating System
Macos & Debian

## JAVA/JVM version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

## Problem description
1. Expected behaviour:
The query should be fast
2. Actual behaviour:
The query never resolves and timeout after the configured 120 sec
3. Error message/stack trace:
```
org.springframework.dao.DataAccessResourceFailureException: PreparedStatementCallback; SQL [select al.portfolio_id, phs.name as portfolio_name , al.custodian_id, al.asset_id, a.name as asset_name, 
i.id as linked_issuer_id, i.name as linked_issuer_name, iv.id as linked_vehicle_id, vhs.name as linked_vehicle_name 
from allocation al
inner join portfolio p ON p.id = al.portfolio_id
inner join holding_set phs on phs.id = p.holding_set_id 
inner join asset a ON a.id = al.asset_id
inner join issuer i ON i.id = a.issuer_id
left join investment_vehicle iv on iv.id = i.investment_vehicle_id
left join holding_set vhs on vhs.id = iv.holding_set_id
where al.portfolio_id in (?, ?, ?)
and al.date = (select max(al2.date) from allocation al2 where al2.date <= ? and al2.portfolio_id = al.portfolio_id )]; Read timed out; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: Read timed out
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:107)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:694)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:748)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:216)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:223)
	at com.XXX.processMessage(HoldingSetService.kt:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.camel.support.ObjectHelper.invokeMethodSafe(ObjectHelper.java:207)
	at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:421)
	at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:242)
	at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:213)
	at org.apache.camel.component.bean.AbstractBeanProcessor.process(AbstractBeanProcessor.java:148)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:55)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryState.run(RedeliveryErrorHandler.java:476)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:185)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:87)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:228)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:78)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:40)
	at org.apache.camel.component.azure.queue.QueueServiceConsumer.poll(QueueServiceConsumer.java:40)
	at org.apache.camel.support.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:183)
	at org.apache.camel.support.ScheduledPollConsumer.run(ScheduledPollConsumer.java:102)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Read timed out
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3081)
	at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2036)
	at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6474)
	at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7638)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:598)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:522)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7253)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3136)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:444)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:678)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
	... 40 common frames omitted
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1009)
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:999)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1103)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
	at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2030)
	... 53 common frames omitted
```
4. Any other details that can be helpful:

## JDBC trace logs
Ask me which one you would like

## Reproduction code
This is not easily reproducible as if I copy the jdbcquery somewhere else it just works!!!!
All that I can say is that there is 1 connection available, 0 transaction surrounding the call.

**Comment by ulvii** [comment]
Hi @Tetradeus ,

Java getting stuck at `java.net.SocketInputStream.socketRead0` usually means the initial connection was successful, but during execution of queries connection randomly becomes unusable, because of packet loss for example, but JAVA is not aware of it and waits to read data. 

From my experience, this is almost never a driver issue. I would suggest to do network troubleshooting, perhaps there is a configuration on your VM that causes a packet loss.

**Comment by Tetradeus** [comment]
Hello @ulvii , I do not think this is the issue. I have been stuck on the same request again and this time it fails everytime with every version of the lib.

Firstly, I am using spring jdbc template. I will try to reproduce directly with the driver.

Secondly, if I copy the parameters directly in the query string instead of passing them via a prepared statement parameters, the request takes 7 second vs 120 sec timeout.

Here is the success logs after a sending the request with hard coded parameters :
```
 main] c.m.s.jdbc.internals.TDS.Channel              : com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream@4a2d66e Writing 1597 bytes
2020-05-02 15:19:49.526 TRACE 5040 --- [           main] c.m.s.jdbc.internals.TDS.Channel              : com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream@4a2d66e Flushing
2020-05-02 15:19:49.526 TRACE 5040 --- [           main] c.m.s.jdbc.internals.TDS.Command              : TDSCommand@40cd02fc (SQLServerPreparedStatement:5 executeXXX): request complete
2020-05-02 15:19:49.526 TRACE 5040 --- [           main] c.m.s.jdbc.internals.TDS.Command              : TDSCommand@40cd02fc (SQLServerPreparedStatement:5 executeXXX): Reading response...
2020-05-02 15:19:49.526 TRACE 5040 --- [           main] c.m.s.jdbc.internals.TDS.Channel              : com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@432f4626 Reading 5 bytes
2020-05-02 15:19:52.800 TRACE 5040 --- [           main] c.m.s.jdbc.internals.TDS.Channel              : com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@432f4626 Read 5 bytes
2020-05-02 15:19:52.800 TRACE 5040 --- [           main] c.m.s.jdbc.internals.TDS.Channel              : com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@432f4626 Reading 1024 bytes
2020-05-02 15:19:52.800 TRACE 5040 --- [           main] c.m.s.jdbc.internals.TDS.Channel              : com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@432f4626 Read 1024 bytes
2020-05-02 15:19:52.800 TRACE 5040 --- [           main] c.m.s.jdbc.internals.TDS.Channel              : com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@432f4626 Reading 1024 bytes
2020-05-02 15:19:52.800 TRACE 5040 --- [           main] c.m.s.jdbc.internals.TDS.Channel              : com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@432f4626 Read 1024 bytes
2020-05-02 15:19:52.800 TRACE 5040 --- [           main] c.m.s.jdbc.internals.TDS.Channel              : com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@432f4626 Reading 1024 bytes
2020-05-02 15:19:52.800 TRACE 5040 --- [           main] c.m.s.jdbc.internals.TDS.Channel              : com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@432f4626 Read 1024 bytes
```


Here is the failed logs after a sending the request with prepared statement parameters :
```
26 08 08 DC 00 00 00 00 00 00 00                  &..........
2020-05-02 15:20:32.871 TRACE 5040 --- [           main] c.m.s.jdbc.internals.TDS.Channel              : com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream@4a2d66e Writing 1880 bytes
2020-05-02 15:20:32.871 TRACE 5040 --- [           main] c.m.s.jdbc.internals.TDS.Channel              : com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream@4a2d66e Flushing
2020-05-02 15:20:32.871 TRACE 5040 --- [           main] c.m.s.jdbc.internals.TDS.Command              : TDSCommand@7789719e (SQLServerPreparedStatement:7 executeXXX): request complete
2020-05-02 15:20:32.871 TRACE 5040 --- [           main] c.m.s.jdbc.internals.TDS.Command              : TDSCommand@7789719e (SQLServerPreparedStatement:7 executeXXX): Reading response...
2020-05-02 15:20:32.871 TRACE 5040 --- [           main] c.m.s.jdbc.internals.TDS.Channel              : com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@432f4626 Reading 5 bytes
```

As you could see, it looks like it does not even receive server data in the last case. Any idea where this could come from ? The sql query is exactly the same with same parameters.

Thanks for your help.

**Comment by ulvii** [comment]
>  I will try to reproduce directly with the driver.

This would definitely help us to identify if driver is sending wrong data.

> As you could see, it looks like it does not even receive server data in the last case. 

Exactly, this just means there is a communication failure, JAVA socket expects a response to the request made and it never receives it (or partially receives it) which causes the application to hang.

A few things you can try that are proven to be helpful to identify the root cause. Try to eliminate variables in your environment. For example, does the query fail on a different VM? Does it fail on a different network? We have seen multiple occurrences where switching to a different network configuration resolved the issue. Does the issue happen only against Azure? Try running the query against your local SQL Server. Please let me know how it goes.

**Comment by ulvii** [comment]
Hi @Tetradeus , 
Any updates on this issuse?

**Comment by ulvii** [comment]
Closing the issue due to inactivity. Please feel free to re-open it if you need any other questions for us.
