### ISSUE TITLE
Unable to use passwordless AD Authentication from Linux Java code

### ISSUE THREAD

**Issue by krishnamsft20** [microsoft/mssql-jdbc#1358]
## Driver version
sqljdbc_8.2/enu/mssql-jdbc-8.2.0.jre8.jar

## SQL Server version
Microsoft SQL Server 2019 (RTM-CU4) (KB4548597) - 15.0.4033.1 (X64)

## Client Operating System
Red Hat Enterprise Linux Server 7.6 (Maipo)) <X64>

## JAVA/JVM version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 8.0.5.35 - pxa6480sr5fp35-20190418_01(SR5 FP35))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190417_414854 (JIT enabled, AOT enabled)
OpenJ9   - 777635f
OMR      - 16b77d7
IBM      - 72459d3)
JCL - 20190409_01 based on Oracle jdk8u211-b25

## Table schema
CREATE TABLE [dbo].[test1](
	[id] [int] NULL,
	[name] [varchar](30) NULL
) ON [PRIMARY]
GO

## Problem description
Tried all different combinations of jdbc connection strings from Linux machine
String dbURL = "jdbc:sqlserver://sql-ad.acnet.greenearth.com:1433;database=TestDB;authenticationScheme=JavaKerberos;integratedSecurity=true" -- does not work

String dbURL = "jdbc:sqlserver://sql-ad.acnet.greenearth.com:1433;database=TestDB;authenticationScheme=JavaKerberos;integratedSecurity=true;userName=sqladmin;password=Password";  -- this works. but it defeats the purpose of using AD Integrated Auth.

create myJDBCTest.java
[sqladmin@sql-ad domainjavatest]$ javac -classpath .:/home/sqladmin/java/jdbcdriver/sqljdbc_8.2/enu/mssql-jdbc-8.2.0.jre8.jar JavaTest3.java
[sqladmin@sql-ad domainjavatest]$ java -classpath .:/home/sqladmin/java/jdbcdriver/sqljdbc_8.2/enu/mssql-jdbc-8.2.0.jre8.jar JavaTest3

1. Expected behaviour:
Successful connection: (works when we put userName=userid;password=Password; at the end of the connection string
Driver name: Microsoft JDBC Driver 8.2 for SQL Server
Driver version: 8.2.0.0
Product name: Microsoft SQL Server
Product version: 12.00.2000

2. Actual behaviour:
com.microsoft.sqlserver.jdbc.SQLServerException: This driver is not configured for integrated authentication. ClientConnectionId:ec69eb72-e155-41a7-84cb-e2d26b05350a
Caused by: java.lang.UnsatisfiedLinkError: mssql-jdbc_auth-8.2.0.x64 (Not found in java.library.path)
3. Error message/stack trace:
com.microsoft.sqlserver.jdbc.SQLServerException: This driver is not configured for integrated authentication. ClientConnectionId:ec69eb72-e155-41a7-84cb-e2d26b05350a
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2998)
        at com.microsoft.sqlserver.jdbc.AuthenticationJNI.<init>(AuthenticationJNI.java:72)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:3765)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$000(SQLServerConnection.java:94)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:3754)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7225)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3053)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2562)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2216)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2067)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1204)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:825)
        at java.sql.DriverManager.getConnection(DriverManager.java:675)
        at java.sql.DriverManager.getConnection(DriverManager.java:281)
        at myJDBCTest.main(myJDBCTest.java:21)
Caused by: java.lang.UnsatisfiedLinkError: mssql-jdbc_auth-8.2.0.x64 (Not found in java.library.path)
        at java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1437)
        at java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1407)
        at java.lang.System.loadLibrary(System.java:584)
        at com.microsoft.sqlserver.jdbc.AuthenticationJNI.<clinit>(AuthenticationJNI.java:51)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:3764)
        ... 12 more
4. Any other details that can be helpful:

## Reproduction code
[sqladmin@sql-ad domainjavatest]$ vi JavaTest3.java
import java.sql.*;
import java.*;
/**
 *  * This program demonstrates how to establish database connection to Microsoft
 *   * SQL Server.
 *    * @author www.codejava.net
 *     *
 *      */
public class JavaTest3 {

    public static void main(String[] args) {

        Connection conn = null;

        try {

        String dbURL = "jdbc:sqlserver://sql-ad.acnet.greenearth.com:1433;database=TestDB;authenticationScheme=JavaKerberos;integratedSecurity=true";
            conn = DriverManager.getConnection(dbURL);
            if (conn != null) {
                DatabaseMetaData dm = (DatabaseMetaData) conn.getMetaData();
                System.out.println("Driver name: " + dm.getDriverName());
                System.out.println("Driver version: " + dm.getDriverVersion());
                System.out.println("Product name: " + dm.getDatabaseProductName());
                System.out.println("Product version: " + dm.getDatabaseProductVersion());
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        } finally {
            try {
                if (conn != null && !conn.isClosed()) {
                    conn.close();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }
}

**Comment by mprins** [comment]
> Caused by: java.lang.UnsatisfiedLinkError: mssql-jdbc_auth-8.2.0.x64 (Not found in java.library.path)

As the error message says you need the native libraries in `java.library.path` for AD authentication, check the docs: https://docs.microsoft.com/en-us/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server?view=sql-server-ver15

**Comment by ulvii** [comment]
@krishnamsft20 ,
You need to use  `ActiveDirectoryIntegrated` connection property. On Linux, you also need to setup Kerberos environment.  See [this page](https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver15#connecting-using-activedirectoryintegrated-authentication-mode) for more details.

**Comment by krishnamsft20** [comment]
> @krishnamsft20 ,
> `integratedSecurity` connection property is for Windows only and won't work on Linux, you either need to use [Kerberos ](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server?view=sql-server-ver15) or [NTLM](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-ntlm-authentication-to-connect-to-sql-server?view=sql-server-ver15). Also see this page for more details on [JDBC connection properties](https://docs.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver15).

Hi Ulvii, 

tried using Kerberos too and getting errors
String connectionUrl = "jdbc:sqlserver://sql-ad.acnet.greenearth.com:1433;database=TestDB;integratedSecurity=true;authenticationScheme=JavaKerberos";
[sqladmin@sql-ad domainjavatest]$ java -classpath .:/home/sqladmin/java/jdbcdriver/sqljdbc_8.2/enu/mssql-jdbc-8.2.0.jre8.jar JavaDomainTest
com.microsoft.sqlserver.jdbc.SQLServerException: Kerberos Login failed: Integrated authentication failed. ClientConnectionId:211db277-f4de-49e4-a8c4-5adbd5adb23b due to javax.security.auth.login.LoginException (javax.security.auth.callback.UnsupportedCallbackException: Cannot get any of properties: [user, USER] from con properties)
        at com.microsoft.sqlserver.jdbc.KerbAuthentication.intAuthInit(KerbAuthentication.java:100)
        at com.microsoft.sqlserver.jdbc.KerbAuthentication.generateClientContext(KerbAuthentication.java:207)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:4926)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:3810)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$000(SQLServerConnection.java:94)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:3754)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7225)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3053)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2562)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2216)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2067)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1204)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:825)
        at java.sql.DriverManager.getConnection(DriverManager.java:675)
        at java.sql.DriverManager.getConnection(DriverManager.java:281)
        at JavaDomainTest.main(JavaDomainTest.java:14)
Caused by: javax.security.auth.login.LoginException: javax.security.auth.callback.UnsupportedCallbackException: Cannot get any of properties: [user, USER] from con properties
        at com.ibm.security.auth.module.Krb5LoginModule.m(Unknown Source)
        at com.ibm.security.auth.module.Krb5LoginModule.k(Unknown Source)
        at com.ibm.security.auth.module.Krb5LoginModule.b(Unknown Source)
        at com.ibm.security.auth.module.Krb5LoginModule.login(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:788)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:196)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:698)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:696)
        at java.security.AccessController.doPrivileged(AccessController.java:703)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:696)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:597)
        at com.microsoft.sqlserver.jdbc.KerbAuthentication.intAuthInit(KerbAuthentication.java:77)
        ... 15 more

I am wondering why it is expecting username password when specifying javakerberos. I have klist returing ticket properly.

**Comment by ulvii** [comment]
This error usually means you haven't setup JAVA Kerberos configuration or the driver is unable to find the Kerberos ticket. Please make sure to follow the steps from [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server?view=sql-server-ver15). 

You can set the path to your config files using environment variables or JAVA properties. For example, using environment variables KRB5CCNAME=path_to_ticket or KRB5_CONFIG=path_to_ini .

**Comment by krishnamsft20** [comment]
I have /etc/krb5.conf already configured as the client server is joined to domain. I created SQLJDBCDriver.conf with entries below. 

SQLJDBCDriver {
   com.sun.security.auth.module.Krb5LoginModule required useTicketCache=true doNotPrompt=true;
};

I am getting following error: I am not sure what am I missing.
Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "com.ibm.jsse2.util.h: PKIX path building failed: java.security.cert.CertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:d651105c-b835-4e63-813c-b72b80ab6d85
Caused by: javax.net.ssl.SSLHandshakeException: com.ibm.jsse2.util.h: PKIX path building failed: java.security.cert.CertPathBuilderException: unable to find valid certification path to requested target
  at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1802)
        ... 7 more
Caused by: com.ibm.jsse2.util.h: PKIX path building failed: java.security.cert.CertPathBuilderException: unable to find valid certification path to requested target

Caused by: java.security.cert.CertPathBuilderException: unable to find valid certification path to requested target
        at com.ibm.security.cert.PKIXCertPathBuilderImpl.buildCertPath(PKIXCertPathBuilderImpl.java:654)

**Comment by krishnamsft20** [comment]
I am running it as below

java -classpath .:/home/sqladmin/java/jdbcdriver/sqljdbc_8.2/enu/mssql-jdbc-8.2.0.jre8.jar -Djava.security.auth.login.config=SQLJDBCDriver.conf -Djava.security.krb5.conf=/etc/krb5.conf JDBCAD

**Comment by ulvii** [comment]
How are you specifying path to the ticket?  Can you try using KRB5CCNAME=path_to_ticket?

**Comment by krishnamsft20** [comment]
This [LInk](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server?view=sql-server-ver15#using-kerberos-authentication-from-unix-machines-on-the-same-domain)  says KRB5CCNAME is optional. I am not sure what to set KRB5CCNAME to.

**Comment by krishnamsft20** [comment]
> This [LInk](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server?view=sql-server-ver15#using-kerberos-authentication-from-unix-machines-on-the-same-domain) says KRB5CCNAME is optional. I am not sure what to set KRB5CCNAME to.

The link also says code should work in LInux but it doesn't in my case. I am out of ideas

**Comment by mprins** [comment]
`PKIX path building failed: java.security.cert.CertPathBuilderException: unable to find valid certification path to requested target` suggests that you are missing an intermediate of signing certificate in your keystore

**Comment by krishnamsft20** [comment]
I am not using certs of any kind. When I use sqlcmd to connect to SQL Server, it works fine. trying to get jdbc to work. My java skill is close to zero. I am just trying to test jdbc connection to SQL server.

**Comment by ulvii** [comment]
@krishnamsft20 , the article assumes you have a valid Kerberos setup. Are you using Kerberos authentication with sqlcmd? Or you provide username and password ?

**Comment by krishnamsft20** [comment]
> @krishnamsft20 , the article assumes you have a valid Kerberos setup. Are you using Kerberos authentication with sqlcmd? Or you provide username and password ?

using kerberos with sqlcmd 
# sqlcmd -S sqlhost -E as a domain user from Linux command line

**Comment by ulvii** [comment]
`java.security.cert.CertPathBuilderException: unable to find valid certification path to requested target` means  the driver is trying to establish an SSL connection but it fails. As @mprins mentioned , to be able to create encrypted connections, you need to add  the server certificate to your JAVA keystore. So to test this theory. please try the options below and let me know if the connection succeeds.

- Explicitly turn off connection encryption.  `connectionUrl = "jdbc:sqlserver://sql-ad.acnet.greenearth.com:1433;database=TestDB;integratedSecurity=true;authenticationScheme=JavaKerberos;encrypt=false";`
- Disable server certificate validation. ``connectionUrl = "jdbc:sqlserver://sql-ad.acnet.greenearth.com:1433;database=TestDB;integratedSecurity=true;authenticationScheme=JavaKerberos;encrypt=true;trustServerCertificate=true";``

**Comment by krishnamsft20** [comment]
xplicitly turn off connection encryption. connectionUrl = "jdbc:sqlserver://sql-ad.acnet.greenearth.com:1433;database=TestDB;integratedSecurity=true;authenticationScheme=JavaKerberos;encrypt=false";

Error:
com.microsoft.sqlserver.jdbc.SQLServerException: Kerberos Login failed: Integrated authentication failed. ClientConnectionId:9615a372-92f5-4ea6-a99f-ffbffa5f60b                                                                             a due to javax.security.auth.login.LoginException (javax.security.auth.callback.UnsupportedCallbackException: Cannot get any of properties: [user, USER] from con properties)
at JTDSTest.main(JTDSTest.java:20)
Caused by: javax.security.auth.login.LoginException: javax.security.auth.callback.UnsupportedCallbackException: Cannot get any of properties: [user, USER] from con properties


Disable server certificate validation. connectionUrl = "jdbc:sqlserver://sql-ad.acnet.greenearth.com:1433;database=TestDB;integratedSecurity=true;authenticationScheme=JavaKerberos;encrypt=true;trustServerCertificate=true";
com.microsoft.sqlserver.jdbc.SQLServerException: Kerberos Login failed: Integrated authentication failed. ClientConnectionId:4f676e9b-ea03-4684-b2ba-056cf88edbb0 due to javax.security.auth.login.LoginException (Login Failure: all modules ignored)
Caused by: javax.security.auth.login.LoginException: Login Failure: all modules ignored

**Comment by ulvii** [comment]
These error messages are confusing.

Explicitly turning off connection encryption should not result in  `Cannot get any of properties: [user, USER] from con properties`. This error message means the driver is not able to find the Kerberos ticket. If the ticket is in the default location, this should not happen. For example, on my Windows machine, the default location for the ticket is C:\Users\ulvii\krb5cc_ulvii. If your Kerberos ticket is not in the default location, then you need to specify the location of it using `KRB5CCNAME` environment variable. Please try to figure out the default Kerberos ticket path for your environment and check if the ticket is there. See [this page](https://web.mit.edu/kerberos/krb5-1.4/krb5-1.4/doc/klist.html) for more details about ticket locations.

If you have troubles with reading the ticket, you can try to authenticate using principal name for testing purposes. See instructions [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server?view=sql-server-ver15#kerberos-connection-using-principal-names-and-password). 

In general, it is not easy to debug Kerberos issues and I highly doubt this is a driver issue. To further troubleshoot, you can also try to gather Kerberos logs for additional information using the following properties:

```
-Dcom.ibm.security.jgss.debug=all
-Dcom.ibm.security.krb5.Krb5Debug=all
```

**Comment by peterbae** [comment]
Hi @krishnamsft20, were you able to find a solution to your problem?

**Comment by peterbae** [comment]
Were there any updates on this item?

**Comment by krishnamsft20** [comment]
This has been still a problem for me. I am unable to use integratedSecurity in Linux JDBC driver.

**Comment by ulvii** [comment]
Hi @krishnamsft20 ,
Have you had a chance to try the suggestions [here](https://github.com/microsoft/mssql-jdbc/issues/1358#issuecomment-656430236)?

**Comment by krishnamsft20** [comment]
Hi Ulvii, 

I have not been able to test it successfully. I am still testing. I will let you know more about my testing soon.
Thank you,

**Comment by lilgreenbird** [comment]
hi @krishnamsft20 

have you had any success with your testing?

**Comment by rene-ye** [comment]
Closing issue due to inactivity, please feel free to reopen or create another issue if further assistance is needed.

**Comment by fcorange** [comment]
I'm also having a similar issue. So far the workaround is changing `default_cache_name` from using keyring to a local file (e.g. /tmp/krb5cc_${UID}).

**Comment by krishnamsft20** [comment]
update here. 
Had to change dfault_ccache_name to a file for this to work. KEYRING did not work
# default_ccache_name = KEYRING:persistent:%{uid}
 **default_ccache_name = FILE:/tmp/krb5cc_%{uid}**

**Comment by thomass4t** [comment]
I had the same error. After adjusting my login.config it worked:

SQLJDBCDriver {
   com.sun.security.auth.module.Krb5LoginModule required
   useTicketCache=false
   principal="HTTP/xy.com@CONTOSO.COM"
   useKeyTab=true
   keyTab="/opt/xy/test.keytab"
   doNotPrompt=true;
};

Adjust the principal and keyTab path to your environment.
After this change, I even didn't have to use kinit to fetch a ticket initially.
