### ISSUE TITLE
SQLServerBulkCopy causes error when a column name is also a reserved word

### ISSUE THREAD

**Issue by fjalvingh** [microsoft/mssql-jdbc#1381]
## Driver version

8.2.2-jre11

## SQL Server version

Microsoft SQL Azure (RTM) - 12.0.2000.8 
	Jun 18 2020 16:54:11 
	Copyright (C) 2019 Microsoft Corporation

## Client Operating System

Ubuntu 18.04

## JAVA/JVM version
openjdk 11.0.3 2019-04-16 LTS
OpenJDK Runtime Environment Zulu11.31+11-CA (build 11.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.31+11-CA (build 11.0.3+7-LTS, mixed mode)

## Table schema
create table s_h_energieprestatie_ssm
(
	id_s int not null
		constraint s_h_energieprestatie_ssm_pk
			primary key,
	client_number smallint default 1 not null,
	dv_end_dts datetime not null,
	dv_load_dts datetime not null,
	dv_start_dts datetime not null,
	id_h_energieprestatie int not null,
	office_number smallint default 1 not null,
	adviseur varchar(8000),
	auditinfo varchar(8000),
	begindatum date,
	businesskey varchar(8000),
	code varchar(8000),
	eenheid varchar(8000),
	einddatum date,
	extraelementen varchar(8000),
	identificatie varchar(8000),
	[index] numeric(15,2),
	label varchar(8000),
	sat_attributes_concat char(32),
	source_system_id varchar(64)
)

## Problem description
I am using the SQLServerBulkCopy class to get the terribly bad performance of SQLServer at least slightly better. This works fine for most tables. But the table above contains a column with the name "index" which of course is also a reserved word. Inserting data in that table causes:

com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'index'. If this is intended as a part of a table hint, A WITH keyword and parenthesis are now required. See SQL Server Books Online for proper syntax.

which seems to indicate that the server is not properly quoting that name. I tried to work around it by letting the ISQLServerBulkData implementation look like this:

		public String getColumnName(int i) {
			return "[" + m_myColumnList.get(i - 1) + "]";
		}

but that does not fix the issue.

**Comment by fjalvingh** [comment]
Forgot the stack trace:
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'index'. If this is intended as a part of a table hint, A WITH keyword and parenthesis are now required. See SQL Server Books Online for proper syntax.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:600)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:522)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7225)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3053)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:444)
	at nl.skarp.dataloader.db.mssql.SqlServerBulkInserter.inserter(SqlServerBulkInserter.java:273)
	at nl.skarp.dataloader.db.mssql.SqlServerBulkInserter.lambda$0(SqlServerBulkInserter.java:84)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by fjalvingh** [comment]
Ok, this was a mistake; the error occurs in a completely different place... Sorry..
