### ISSUE TITLE
Regression in 8.4.0; SQLServerResultSet; SQLServerConnection vs SQLServerConnectionPoolProxy 

### ISSUE THREAD

**Issue by christophs78** [microsoft/mssql-jdbc#1401]
## Driver version
8.4.0

## Problem description
Caused by: java.lang.ClassCastException: com.microsoft.sqlserver.jdbc.SQLServerConnectionPoolProxy incompatible with com.microsoft.sqlserver.jdbc.SQLServerConnection 
at com.microsoft.sqlserver.jdbc.SQLServerResultSet.configureLobs(SQLServerResultSet.java:2085) 
at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getClob(SQLServerResultSet.java:2825) 
at com.ibm.ws.rsadapter.jdbc.WSJdbcResultSet.getClob(WSJdbcResultSet.java:750) 
at org.hibernate.type.descriptor.sql.ClobTypeDescriptor$1.doExtract(ClobTypeDescriptor.java:44) 
at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47) 
...

## Analysis
https://github.com/microsoft/mssql-jdbc/commit/54c67488d881f7075c4632967ec0d5a558138c69#diff-e5880682be515f702f2a448d2dbcdedf introduced the new method "configureLobs".
configureLobs uses hardcoded SQLServerConnection. But in some usecases (java-applicationserver?) the connection is not an instance of SQLServerConnection but of SQLServerConnectionPoolProxy. --> ClassCastException

![image](https://user-images.githubusercontent.com/10461942/89412285-1426b980-d727-11ea-906d-e24660e51b80.png)

**Comment by rene-ye** [comment]
Hi @christophs78, thanks for bringing this issue to our attention. I've applied a fix which should resolve the issue. I'm attaching the binaries to this comment, can you test the binaries and confirm the fix is working on your end as well, thanks.

[SQLServerConnectionPoolProxy Jars.zip](https://github.com/microsoft/mssql-jdbc/files/5030127/SQLServerConnectionPoolProxy.Jars.zip)

**Comment by christophs78** [comment]
Yes it´s fixed. :-)

I´ll try to have an eye on the commits in the next days. Hope your are able to fix this in a clean way.
It looks like getDelayLoadingLobs was only added to SQLServerConnection. But not to SQLServerConnectionPoolProxy.
IMO the fix should not only be a instanceof - check. Sounds a bit like getDelayLoadingLobs should be moved to a interface which is implemented by SQLServerConnection and SQLServerConnectionPoolProxy. (And maybe some more classes i did not figure out yet.)
