### ISSUE TITLE
What does mssql-jdbc_auth maven artifact do to avoid java.lang.UnsatisfiedLinkError?

### ISSUE THREAD

**Issue by bahaabeih** [microsoft/mssql-jdbc#1439]
### Environment Details:

- OS: Windows 10 2004
- JDK/JRE: zulu11.39.15
- IDE: Intellij IDEA
- Relevant maven dependencies:

        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>8.4.1.jre11</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc_auth</artifactId>
            <version>8.4.1.x64</version>
            <type>dll</type>
        </dependency>

## Issue:
I am trying connect to an SQL Server DB using integrated security. The DB URL I use is (`jdbc:sqlserver://pc0217\instance04;integratedSecurity=true`). According to [documentation](https://github.com/microsoft/mssql-jdbc#download-the-dlls), using integrated security requires DLLs, which can be pulled using a maven artifact instead of manual download. Nonetheless, I keep getting the following exception no matter what:

```
com.microsoft.sqlserver.jdbc.SQLServerException: This driver is not configured for integrated authentication. ClientConnectionId:c54fb8fc-3a10-4cb5-970c-959c0c2fa4c0
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3151)
	at com.microsoft.sqlserver.jdbc.AuthenticationJNI.<init>(AuthenticationJNI.java:72)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:3943)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:3932)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7375)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3206)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2713)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2362)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2213)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1276)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:861)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.mycompany.demo.getData(DbDemo.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeAllMethod(TimeoutExtension.java:68)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllMethods$9(ClassBasedTestDescriptor.java:384)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllMethods(ClassBasedTestDescriptor.java:382)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:196)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.lang.UnsatisfiedLinkError: no mssql-jdbc_auth-8.4.1.x64 in java.library.path: [ ... contents of the system PATH variable, omitted for brevity ... ]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1870)
	at com.microsoft.sqlserver.jdbc.AuthenticationJNI.<clinit>(AuthenticationJNI.java:51)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:3942)
	... 68 more
```

The contents of `<my home directory>\.m2\repository\com\microsoft\sqlserver\mssql-jdbc_auth\8.4.1.x64` are as shown:
![image](https://user-images.githubusercontent.com/10739550/94694162-d4e6a480-0334-11eb-9eea-9b5b0672daf7.png)

The only way I could get it to work is by manually copying `mssql-jdbc_auth-8.4.1.x64.dll` from my local maven repository to a folder on the classpath. The same/Similar behavior is reported [here](https://stackoverflow.com/questions/63842649/set-mssql-jdbc-auth-with-maven) and [here](https://stackoverflow.com/questions/64098524/maven-build-failure-when-trying-to-create-runnable-jar-failed-to-create-assembl)

**Comment by mprins** [comment]
so... did you set up the java.libary.path? apparently not, since that is a JVM option it needs to be specified at jvm startup and cannot be set using maven.

examples: https://stackoverflow.com/questions/1734207/how-to-set-java-library-path-for-processing

**Comment by bahaabeih** [comment]
No. I didn't and I hope I don't have to. What is the point of using maven artifact `mssql-jdbc_auth` then.
I could just manually download the `mssql-jdbc_auth-8.4.1.x64.dll`, put it on my path and my code would work

**Comment by SabbitRex** [comment]
I came from the comment you made on my question on stackoverflow, thank you for opening the thread!

**Comment by ulvii** [comment]
Hi @bahaabeih , @SabbitRex 

In JAVA, [`System.loadLibrary()` ](https://github.com/microsoft/mssql-jdbc/blob/0db30ad1000437bd92d3e2b133da06a541c54fa0/src/main/java/com/microsoft/sqlserver/jdbc/AuthenticationJNI.java#L51) method loads the DLL from `java.library.path`, the driver does not have a choice here. Couple things you can do to load the DLL :
 
- Use Maven to download the DLL to a folder  and set `java.library.path` to that folder. 
`mvn dependency:copy-dependencies -DoutputDirectory=OUTPUT_DIR`
`java.library.path=OUTPUT_DIR`
- Use Maven to download the  DLL to a folder and make sure that folder is in PATH variable on WIndows (default `java.library.path` is equal to `PATH` on WIndows).

**Comment by bahaabeih** [comment]
Thanks for the response, @ulvii 
Would you recommended a specific folder to use for the first variant? Any sample code?

**Comment by rene-ye** [comment]
The folder naming scheme and dll location could vary depending on the application and best practices, so we don't really have any recommendations. But regarding your initial question as to why do this at all if it doesn't just work out of the box; we previously only provided this DLL on our Microsoft download site, and users requested we add this on maven so it was easier for them to retrieve the latest version through w/e script they have set up.

**Comment by bahaabeih** [comment]
Thanks for the informative feedback about the rationale behind the maven artifact.
So, since I'm using integrated security during unit tests, I ended up doing the following:

- using `maven-dependency-plugin` to copy the dll from the `mssql-jdbc_auth` subdirectory in my local m2 repo to a libs folder in my current directory
- using `maven-surefire-plugin` to set the system property, `java.library.path` to that libs folder mentioned earlier

**Comment by ulvii** [comment]
Hi @bahaabeih ,
Glad the steps worked for you. Closing the issue, please feel free to contact us if you have any other questions.
