### ISSUE TITLE
Is SQLServerBulkCopy thread-safe to use for writing data?

### ISSUE THREAD

**Issue by siggemannen** [microsoft/mssql-jdbc#1442]
## Question
Hi. I wonder if SQLServerBulkCopy.writeToServer can be called concurrently from multiple threads against the same table?
I've been trying but getting exceptions which make me suspect it doesn't work thread-safely:

Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: The column name 'temp' is specified more than once in the SET clause or column list of an INSERT. A column cannot be assigned more than one value in the same clause. Modify the clause to make sure that a column is updated only once. If this statement updates or inserts columns into a view, column aliasing can conceal the duplication in your code.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:283)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:129)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:26)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.sendBulkCopyCommand(SQLServerBulkCopy.java:1606)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.doInsertBulk(SQLServerBulkCopy.java:1561)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.access$300(SQLServerBulkCopy.java:64)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy$1InsertBulk.doExecute(SQLServerBulkCopy.java:662)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7375)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3206)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.sendBulkLoadBCP(SQLServerBulkCopy.java:696)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeToServer(SQLServerBulkCopy.java:1654)

If i put instance of SQLServerBulkCopy into a synchronized block, it works fine.

It might be problem with my code when fetching metadata though?

**Comment by peterbae** [comment]
Hi @siggemannen, sorry for the delay in response. You can bulk copy concurrently from multiple threads against the same table. The error you're running into is probably happening because you're sharing JDBC resources between multiple threads - by that, I mean that you're probably re-using the same connection across multiple threads or re-using the same stmt, etc. If you were to create a new connection from every thread, bulk copying into the same table concurrently should be possible.

Please let me know if you need more help / would like for me to take a look at your code.

**Comment by siggemannen** [comment]
Yes, i do share the same connection, so that probably explains it.
But, i don't see any way to pass a new connection to writeToServer-calls. So, it means i still need to create a copy of SQLServerBulkCopy for each thread, no?

**Comment by peterbae** [comment]
You can do that, or what usually happens is that the application relies on a connection pool so that they can avoid re-creating and closing a connection every time.

**Comment by siggemannen** [comment]
Yes, i see. I will close this issue, since i got the answer, thanks a bunch
