### ISSUE TITLE
The conversion from TIMESTAMP_WITH_TIMEZONE to DATETIMEOFFSET is unsupported

### ISSUE THREAD

**Issue by brfrth** [microsoft/mssql-jdbc#1444]
## Driver version

8.4.1

## SQL Server version

```
Microsoft SQL Server 2017 (RTM-CU21) (KB4557397) - 14.0.3335.7 (X64) 
	Jun 12 2020 20:39:00 
	Copyright (C) 2017 Microsoft Corporation
	Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)
```

## Client Operating System

Microsoft Windows 10 Enterprise 10.0.17763 Build 17763

## JAVA/JVM version

OpenJDK 14.0.2

## Table schema

```sql
create table table
(
	id int identity
		constraint table_pk
			primary key nonclustered,
	create_date_time datetimeoffset
)
```

## Problem description

1. Expected behaviour:

I'm trying to insert an `java.time.OffsetDateTime` into a `datetimeoffset` column. This should create a new row in the table with the current datetime and the offset. A `datetime2` field is not suitable for the needs of the application. As `datetimeoffset` is the MSSQL version of a zoned date, this should work intuitively.

2. Actual behaviour:

An error is thrown by the JDBC driver.

3. Error message/stack trace:

```
com.microsoft.sqlserver.jdbc.SQLServerException: The conversion from TIMESTAMP_WITH_TIMEZONE to DATETIMEOFFSET is unsupported.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:234)
	at com.microsoft.sqlserver.jdbc.DataTypes.throwConversionError(DataTypes.java:1112)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.setObject(SQLServerPreparedStatement.java:1591)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.setObject(SQLServerPreparedStatement.java:1510)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setObject(HikariProxyPreparedStatement.java)
	at org.springframework.jdbc.core.StatementCreatorUtils.setValue(StatementCreatorUtils.java:415)
	at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValueInternal(StatementCreatorUtils.java:232)
	at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValue(StatementCreatorUtils.java:163)
	at org.springframework.jdbc.core.ArgumentTypePreparedStatementSetter.doSetValue(ArgumentTypePreparedStatementSetter.java:100)
	at org.springframework.jdbc.core.ArgumentTypePreparedStatementSetter.setValues(ArgumentTypePreparedStatementSetter.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$0(JdbcTemplate.java:865)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:862)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:917)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:922)
	at org.springframework.jdbc.core.simple.AbstractJdbcInsert.executeInsertInternal(AbstractJdbcInsert.java:358)
	at org.springframework.jdbc.core.simple.AbstractJdbcInsert.doExecute(AbstractJdbcInsert.java:348)
	at org.springframework.jdbc.core.simple.SimpleJdbcInsert.execute(SimpleJdbcInsert.java:122)
	at com.*.create(UserQueryRepositoryJdbcImpl.java:81)
	at com.*$$FastClassBySpringCGLIB$$1d59876a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.*$$EnhancerBySpringCGLIB$$24500203.create(<generated>)
	at com.*(ProfileController.java:68)
	at com.*$$FastClassBySpringCGLIB$$2803ae8f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.*$$EnhancerBySpringCGLIB$$1825b030.createUserQuery(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.oauth2.client.filter.OAuth2ClientContextFilter.doFilter(OAuth2ClientContextFilter.java:64)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:155)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.oauth2.client.filter.OAuth2ClientContextFilter.doFilter(OAuth2ClientContextFilter.java:64)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

4. Any other details that can be helpful:

MSSQL doesn't actually provide a real `TIMESTAMP_WITH_TIMEZONE`, so I would argue `DATETIMEOFFSET` should support `OffsetDateTime` implicitly. I realize that I would need to provide a `microsoft.sql.DateTimeOffset` explicitly, but that seems rather unnecessary. `java.time.OffsetDateTime` stores all the relevant information for `DATETIMEOFFSET`, so I'm not quite sure why it's not supported. This is particularly odd because `ResultSet.getObject` **does** support `OffsetDateTime` just fine.

Obviously the JDBC driver is receiving the correct object type. It is saying `TIMESTAMP_WITH_TIMEZONE` isn't right for the field. I just feel that `TIMESTAMP_WITH_TIMEZONE` (and by extension `java.time.OffsetDateTime`) actually is right for `DATETIMEOFFSET` in this context.

**Added info:** Simply using `OffsetDateTime.toString()` instead of the object itself works perfectly. Quite a confusing construct.

## Reproduction code

```java
// Wrapper class for inserts with the application data source
SimpleJdbcInsert simpleJdbcInsert = new SimpleJdbcInsert(jdbcTemplate);

MapSqlParameterSource parameters = new MapSqlParameterSource();
parameters.addValue("create_date_time ", java.time.OffsetDateTime.now(ZoneOffset.UTC));
simpleJdbcInsert.execute(parameters);
```

**Comment by ulvii** [comment]
Hi @brfrth ,
We will investigate and get back to you.

**Comment by ulvii** [comment]
Hi @brfrth ,
I am unable to reproduce the issue.
```
    public static void main(String[] args) throws SQLException {
        new SQLServerDriver();
        String url = "jdbc:sqlserver://localhost;username=user;password=password;database=db";
        try (Connection con = DriverManager.getConnection(url); Statement stmt = con.createStatement();
                PreparedStatement pstmt = con.prepareStatement("insert into issue1444 values(?)")) {
            pstmt.setObject(1, java.time.OffsetDateTime.now(ZoneOffset.UTC));
            pstmt.execute();
            try (ResultSet rs = stmt.executeQuery("select * from issue1444;")) {
                while (rs.next()) {
                    System.out.println(rs.getString(1));
                }
            }
        }
    }
```
Can you provide vanilla JDBC repro code?

**Comment by brfrth** [comment]
Hey @ulvii,

I've managed to find the issue. Spring tries to infer SQL types behind the scenes for `SimpleJdbcInsert`. Specifically this happens [here](https://github.com/spring-projects/spring-framework/blob/7be7e5beb4e7d808761f06e386b359d45a0890d8/spring-jdbc/src/main/java/org/springframework/jdbc/core/metadata/TableMetaDataContext.java#L319). The type it infers is `-155`, which is technically correct as it's defined in [`microsoft.sql.Types`](https://github.com/microsoft/mssql-jdbc/blob/dev/src/main/java/microsoft/sql/Types.java#L22). So now we have our column mapped to the `DATETIMEOFFSET` type. The column is that type, so it's technically correct. But this will now call `SQLServerPreparedStatement#setObject` with that type. 

I believe the above prepared statement does not error, because it lets `SQLServerPreparedStatement` infer the type (uses [`setObjectNoType`](https://github.com/microsoft/mssql-jdbc/blob/3447732f89171ecefbb1b44dab4a9ed6efd205aa/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java#L1460). This in turn uses [`JavaTime.of()`](https://github.com/microsoft/mssql-jdbc/blob/3447732f89171ecefbb1b44dab4a9ed6efd205aa/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java#L1475), which [resolves `OffsetDateTime` to `TIMESTAMP_WITH_TIMEZONE`](https://github.com/microsoft/mssql-jdbc/blob/3447732f89171ecefbb1b44dab4a9ed6efd205aa/src/main/java/com/microsoft/sqlserver/jdbc/DataTypes.java#L407).

So the real issue seems to be, that the column of type `datetimeoffset` has a special JDBC type that `SimpleJdbcInsert` finds and uses. What works is explicitly setting the `JdbcType` for `OffsetDateTime` values with the SQL parameter map to use `TIMESTAMP_WITH_TIMEZONE`.

```java
// Wrapper class for inserts with the application data source
SimpleJdbcInsert simpleJdbcInsert = new SimpleJdbcInsert(jdbcTemplate);

MapSqlParameterSource parameters = new MapSqlParameterSource();
java.time.OffsetDateTime now = java.time.OffsetDateTime.now(ZoneOffset.UTC);
parameters.addValue("create_date_time ", now, java.sql.types.TIMESTAMP_WITH_TIMEZONE); // This works
simpleJdbcInsert.execute(parameters);
```

In the end the issue is the fact that SQL server doesn't implement a `TIMESTAMP_WITH_TIMEZONE` and instead uses a custom type `DATETIMEOFFSET` that `SimpleJdbcInsert` infers. This type then does not work when using [`setObject` with a type parameter](https://github.com/microsoft/mssql-jdbc/blob/3447732f89171ecefbb1b44dab4a9ed6efd205aa/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java#L1583).

Quite a complex issue. Not sure anything can be done about it, since the data type for `OffsetDateTime` is mismatched in the SQL Server JDBC driver internally.

**Comment by brfrth** [comment]
It seems to be mostly an issue of 

```java
              +-------------------+                 |           +------------------+
              | PreparedStatement |                 |           | SimpleJdbcInsert |
              +-------------------+                 |           +------------------+
                        |                           |                     |
             setObject(value, column)               |          execute(value, column)
                        |                           |                     |
          setObjectNoType(value, column)            |            createInsertTypes()
                        |                           |                     |
    JavaType.of(value): TIMESTAMP_WITH_TIMEZONE     |        Column type: DATETIMEOFFSET
                        |                           |                     |
setObject(value, column, 'TIMESTAMP_WITH_TIMEZONE') | setObject(value, column, 'DATETIMEOFFSET')
                        |                           |                     |
              Value and JDBC type match             |     Value and JDBC type do not match
```

**Comment by ulvii** [comment]
Hi @brfrth ,
Thank you for detailed explanation, it clarifies the issue.

According to [this page](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-basic-data-types?view=sql-server-ver15), the driver claims to support `DATETIMEOFFSET`  SQL type with `microsoft.sql.DateTimeOffset`, so the Spring code should look like this:
```
// Wrapper class for inserts with the application data source
SimpleJdbcInsert simpleJdbcInsert = new SimpleJdbcInsert(jdbcTemplate);

MapSqlParameterSource parameters = new MapSqlParameterSource();
microsoft.sql.DateTimeOffset now =`DateTimeOffset valueOf(timestamp, minutesOffset);
parameters.addValue("create_date_time ", now, microsoft.sql.Types.DATETIMEOFFSET); // This works
simpleJdbcInsert.execute(parameters);
```
That being said, I can see why they would want to use `OffsetDateTime` instead of `DateTimeOffset`, but supporting this scenario might not be straightforward. I did a quick research and already noticed some differences between these datatypes. For example  I was not able to insert max `OffsetDateTime` value `+999999999-12-31T23:59:59.999999999-18:00` into `DATETIMEOFFSET` column, received `One or more values is out of range of values for the datetimeoffset SQL Server data type.`.  Another difference I noticed, Time zone offset range is for `OffsetDateTime` is `-18:00 through +18:00` whereas it is `-14:00 through +14:00` for `DateTimeOffset`.   My initial impression is that these datatypes are not necessarily compatible, please let me know what you think.

**Comment by brfrth** [comment]
Yeah I agree. I’m just wondering why it is then, that the SQLServerPreparedStatement will happily bind an OffsetDateTime and insert it. It seems for a lot of cases they are compatible.

The issue appears the be less with the driver and
more with MSSQL not having an equivalent data type. I honestly don’t know a solution. For my purposes these are compatible so I’m just passing their type as if it was inferred by PreparedStatement. I guess that works. But I realize that’s a bit brittle.

**Comment by lilgreenbird** [comment]
hi @brfrth 

As mentioned in previous comment this [page](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-basic-data-types?view=sql-server-ver15) contains all the datatype mappings for the driver. For those types that do not have a direct java.sql.Types mapping the driver has them defined in `microsoft.sql.Types`. 

If you would like to specify a specific SQL type you can use the [setobject](https://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html#setObject(int,%20java.lang.Object,%20int)) API which includes a param for the targeted  SQL type. In your example it should be `microsoft.sql.Types.DATETIMEOFFSET`.

**Comment by lilgreenbird** [comment]
closing due to inactivity

**Comment by ul8422** [comment]
Hi!
Sorry, but it looks like a bug.
* `java.sql.timestamp` on one hand represents local time but on the other time it represents ~timestamp/instant.

Please look at my code and the result:
```java
        Instant date = LocalDateTime.of(2010, 1, 1, 0, 0).toInstant(ZoneOffset.UTC);

        try (Connection conn = DriverManager.getConnection(mssql.getJdbcUrl(), mssql.getUsername(), mssql.getPassword())) {
            conn.setAutoCommit(true);
            // DDL
            try (Statement statement = conn.createStatement()) {
                statement.execute("create table test_table (test_date datetimeoffset)");
            }
            // INSERT
            try (PreparedStatement preparedStatement = conn.prepareStatement("insert into test_table values (?)")) {
                preparedStatement.setTimestamp(1, Timestamp.from(date));
                preparedStatement.execute();
                System.out.println("timestamp represents LOCAL DATE on the one hand: " + Timestamp.from(date).toString());
                System.out.println("timestamp represents ~INSTANT on the other hand: " + Timestamp.from(date).getTime()
                        + " - " + date.toEpochMilli());
            }
            // FETCH
            try (Statement statement = conn.createStatement()) {
                try (ResultSet rs = statement.executeQuery("select * from test_table")) {
                    if (rs.next()) {
                        Timestamp received = rs.getTimestamp(1);
                        System.out.println("ZoneId: " + ZoneId.systemDefault());
                        System.out.println("ORIGIN: " + date);
                        System.out.println("FETCHED: " + received.toInstant());
                    } else {
                        throw new RuntimeException("TLD");
                    }
                }
            }
        }
```

Result:
```java
timestamp represents LOCAL DATE on the one hand: 2010-01-01 03:00:00.0
timestamp represents ~INSTANT on the other hand: 1262304000000 - 1262304000000
ZoneId: Europe/Moscow
ORIGIN: 2010-01-01T00:00:00Z
FETCHED: 2010-01-01T03:00:00Z
```

SO, I expected to receive "2010-01-01T00:00:00Z". Postgres does it, H2 Database does it, Oracle so does...


Thanks in advance! :)
