### ISSUE TITLE
[QUESTION] Float read as Double and throwing exception

### ISSUE THREAD

**Issue by mouldi145** [microsoft/mssql-jdbc#1451]
I'm using BulkCopy for transferring data between two SQL Server databases that have the exact same structure , tables and types. 

i'm not adding any column information/metadata or mapping manually since the structure is the same. I'm just calling writeToServer() with a resultset:

`bulkCopy.writeToServer(rs);`

The problem is that the above writeToServer fails whenever it encounters a column with of type float in the database with the following exception:

```
com.microsoft.sqlserver.jdbc.SQLServerException: An error occurred while converting the Double value to JDBC data type FLOAT.
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeColumnToTdsWriter(SQLServerBulkCopy.java:2567)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeColumn(SQLServerBulkCopy.java:3069)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeBatchData(SQLServerBulkCopy.java:3607)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.doInsertBulk(SQLServerBulkCopy.java:1566)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.access$300(SQLServerBulkCopy.java:64)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy$1InsertBulk.doExecute(SQLServerBulkCopy.java:662)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7375)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3206)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.sendBulkLoadBCP(SQLServerBulkCopy.java:696)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeToServer(SQLServerBulkCopy.java:1654)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeResultSet(SQLServerBulkCopy.java:595)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeToServer(SQLServerBulkCopy.java:533)
Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeColumnToTdsWriter(SQLServerBulkCopy.java:2136)
```

The error while debugging is this:
`java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float
`
Is there a way to workaround this with manual mappings or metadata?
Thanks!

**Comment by peterbae** [comment]
Hi @mouldi145, I tested a simple scenario with a table that only has a float column and tried to bulk copy into another table with the same schema, and it was successful. Could you share your table schema and your code with us, so we can take a closer look at this issue?

**Comment by rene-ye** [comment]
Hi @mouldi145, can you also provide what version of the mssql-jdbc driver you're using and the SQL Server versions of both the source/destination databases.

**Comment by mouldi145** [comment]
@rene-ye The database I'm writing to is SQL Server 13.04224.16 and the source database has version 13.0.5239.0

Driver version was initially 7.4.1.jre8 but tried even with 8.4.1.jre8

**Comment by peterbae** [comment]
Hi @mouldi145, could you try getting the data from the source DB using our driver, then also bulk copying with our driver then see if that works? I think there might be a difference in how float is handled between the MSSQL JDBC driver and the Progress driver (which by the way you mentioned was ODBC, could you share how you're using the ODBC driver in your Java application?)

**Comment by peterbae** [comment]
@mouldi145 did you have a chance to look into the above comment?

**Comment by mouldi145** [comment]
@peterbae Unfortunately I cannot connect to the Progress database without their own proprietary driver.

**Comment by peterbae** [comment]
I see. Are you okay with the SQLServerBulkCSVFileRecord workaround, or do you need the JDBC team to further investigate this?

**Comment by mouldi145** [comment]
@peterbae  I didn't settle for SQLServerBulkCSVFileRecord since it was too complicated, I used the workaround below which seems to solve the issue. 

```
        DecimalFormat df = new DecimalFormat("#.##");
        df.setRoundingMode(RoundingMode.FLOOR);
        int columnCount = cachedRowSet.getMetaData().getColumnCount();
        while (cachedRowSet.next()) {
            for (int i = 1; i <= columnCount; i++) {
                if (cachedRowSet.getMetaData().getColumnType(i) == Types.FLOAT) {
                    Object fs = cachedRowSet.getFloat(i);
                    cachedRowSet.updateDouble(i, parseDouble(df.format(parseDouble(fs.toString()))));
                    cachedRowSet.updateRow();
                }
            }
        }
```

**Comment by peterbae** [comment]
Thanks. The team will investigate into this issue soon and get back to you.

**Comment by rene-ye** [comment]
Hi @mouldi145, the problem here is that there's a clash in the ResultSet between the 2 drivers. In the mssql-jdbc driver, we map the  SQL Server `float` datatype to Java's `double` datatype . Whereas I'm assuming in the driver you're using, maps it to the Java `float` datatype. The ResultSet information you're passing to BulkCopy is telling it to insert a float datatype into a column that expects a double, which is causing the error. There really isn't much to do from our end as this seems to just be a design clash between drivers, and it's not reasonable for us to support BulkCopying ResultSets generated from any other JDBC driver.

**Comment by lilgreenbird** [comment]
hi @mouldi145,

Hope the explanation helped. Please let us know if you have any more questions otherwise we will be closing the issue.  Thanks..

**Comment by lilgreenbird** [comment]
closing due to inactivity
