### ISSUE TITLE
SQLServerException: The TDS protocol stream is not valid.

### ISSUE THREAD

**Issue by jeusdi** [microsoft/mssql-jdbc#1459]
## Driver version
I'm using this dependency:

    <dependency>
        <groupId>com.microsoft.sqlserver</groupId>
	<artifactId>mssql-jdbc</artifactId>
	<version>8.4.1.jre11</version>
    </dependency>

## SQL Server version
2019

## JAVA/JVM version
Java 11.0.5

## Problem description
I'm getting this stacktrace:

```
HikariPool-2 - Connection ConnectionID:1 ClientConnectionId: 7d5e3717-c1af-4b26-8268-543e3848b428 marked as broken because of SQLSTATE(08S01), ErrorCode(0)

com.microsoft.sqlserver.jdbc.SQLServerException: The connection is closed.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:234) ~[mssql-jdbc-8.4.1.jre11.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.checkClosed(SQLServerConnection.java:1202) ~[mssql-jdbc-8.4.1.jre11.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.checkClosed(SQLServerStatement.java:1063) ~[mssql-jdbc-8.4.1.jre11.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.checkClosed(SQLServerResultSet.java:454) ~[mssql-jdbc-8.4.1.jre11.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getLong(SQLServerResultSet.java:2352) ~[mssql-jdbc-8.4.1.jre11.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getLong(HikariProxyResultSet.java) ~[HikariCP-3.4.5.jar:na]
	at net.gencat.clt.arxius.connector.mapper.AutorRowMapper.mapRow(AutorRowMapper.java:24) ~[classes/:na]
	at net.gencat.clt.arxius.connector.mapper.AutorRowMapper.mapRow(AutorRowMapper.java:11) ~[classes/:na]
	at org.springframework.batch.item.database.JdbcCursorItemReader.readCursor(JdbcCursorItemReader.java:142) ~[spring-batch-infrastructure-4.3.0.jar:4.3.0]
	at org.springframework.batch.item.database.AbstractCursorItemReader.doRead(AbstractCursorItemReader.java:495) ~[spring-batch-infrastructure-4.3.0.jar:4.3.0]
	at org.springframework.batch.item.support.AbstractItemCountingItemStreamItemReader.read(AbstractItemCountingItemStreamItemReader.java:93) ~[spring-batch-infrastructure-4.3.0.jar:4.3.0]
	at org.springframework.batch.core.step.item.SimpleChunkProvider.doRead(SimpleChunkProvider.java:99) ~[spring-batch-core-4.3.0.jar:4.3.0]
	at org.springframework.batch.core.step.item.SimpleChunkProvider.read(SimpleChunkProvider.java:180) ~[spring-batch-core-4.3.0.jar:4.3.0]
	at org.springframework.batch.core.step.item.SimpleChunkProvider$1.doInIteration(SimpleChunkProvider.java:126) ~[spring-batch-core-4.3.0.jar:4.3.0]
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375) ~[spring-batch-infrastructure-4.3.0.jar:4.3.0]
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215) ~[spring-batch-infrastructure-4.3.0.jar:4.3.0]
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145) ~[spring-batch-infrastructure-4.3.0.jar:4.3.0]
	at org.springframework.batch.core.step.item.SimpleChunkProvider.provide(SimpleChunkProvider.java:118) ~[spring-batch-core-4.3.0.jar:4.3.0]
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:71) ~[spring-batch-core-4.3.0.jar:4.3.0]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407) ~[spring-batch-core-4.3.0.jar:4.3.0]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331) ~[spring-batch-core-4.3.0.jar:4.3.0]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.1.jar:5.3.1]
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273) ~[spring-batch-core-4.3.0.jar:4.3.0]
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82) ~[spring-batch-core-4.3.0.jar:4.3.0]
	at org.springframework.batch.repeat.support.TaskExecutorRepeatTemplate$ExecutingRunnable.run(TaskExecutorRepeatTemplate.java:262) ~[spring-batch-infrastructure-4.3.0.jar:4.3.0]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2020-11-18 19:03:34.809  WARN 26507 --- [  spring_batch2] com.zaxxer.hikari.pool.ProxyConnection   : HikariPool-2 - Connection ConnectionID:1 ClientConnectionId: 7d5e3717-c1af-4b26-8268-543e3848b428 marked as broken because of SQLSTATE(08S01), ErrorCode(0)

com.microsoft.sqlserver.jdbc.SQLServerException: The TDS protocol stream is not valid.
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3151) ~[mssql-jdbc-8.4.1.jre11.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3140) ~[mssql-jdbc-8.4.1.jre11.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.throwInvalidTDS(SQLServerConnection.java:3123) ~[mssql-jdbc-8.4.1.jre11.jar:na]
	at com.microsoft.sqlserver.jdbc.TDSReader.throwInvalidTDS(IOBuffer.java:6507) ~[mssql-jdbc-8.4.1.jre11.jar:na]
	at com.microsoft.sqlserver.jdbc.ServerDTVImpl.getValuePrep(dtv.java:3421) ~[mssql-jdbc-8.4.1.jre11.jar:na]
	at com.microsoft.sqlserver.jdbc.ServerDTVImpl.getValue(dtv.java:3686) ~[mssql-jdbc-8.4.1.jre11.jar:na]
	at com.microsoft.sqlserver.jdbc.DTV.getValue(dtv.java:247) ~[mssql-jdbc-8.4.1.jre11.jar:na]
	at com.microsoft.sqlserver.jdbc.Column.getValue(Column.java:190) ~[mssql-jdbc-8.4.1.jre11.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getValue(SQLServerResultSet.java:2054) ~[mssql-jdbc-8.4.1.jre11.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getValue(SQLServerResultSet.java:2040) ~[mssql-jdbc-8.4.1.jre11.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getLong(SQLServerResultSet.java:2353) ~[mssql-jdbc-8.4.1.jre11.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getLong(HikariProxyResultSet.java) ~[HikariCP-3.4.5.jar:na]
	at net.gencat.clt.arxius.connector.mapper.AutorRowMapper.mapRow(AutorRowMapper.java:23) ~[classes/:na]
	at net.gencat.clt.arxius.connector.mapper.AutorRowMapper.mapRow(AutorRowMapper.java:11) ~[classes/:na]
	at org.springframework.batch.item.database.JdbcCursorItemReader.readCursor(JdbcCursorItemReader.java:142) ~[spring-batch-infrastructure-4.3.0.jar:4.3.0]
	at org.springframework.batch.item.database.AbstractCursorItemReader.doRead(AbstractCursorItemReader.java:495) ~[spring-batch-infrastructure-4.3.0.jar:4.3.0]
	at org.springframework.batch.item.support.AbstractItemCountingItemStreamItemReader.read(AbstractItemCountingItemStreamItemReader.java:93) ~[spring-batch-infrastructure-4.3.0.jar:4.3.0]
	at org.springframework.batch.core.step.item.SimpleChunkProvider.doRead(SimpleChunkProvider.java:99) ~[spring-batch-core-4.3.0.jar:4.3.0]
	at org.springframework.batch.core.step.item.SimpleChunkProvider.read(SimpleChunkProvider.java:180) ~[spring-batch-core-4.3.0.jar:4.3.0]
	at org.springframework.batch.core.step.item.SimpleChunkProvider$1.doInIteration(SimpleChunkProvider.java:126) ~[spring-batch-core-4.3.0.jar:4.3.0]
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375) ~[spring-batch-infrastructure-4.3.0.jar:4.3.0]
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215) ~[spring-batch-infrastructure-4.3.0.jar:4.3.0]
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145) ~[spring-batch-infrastructure-4.3.0.jar:4.3.0]
	at org.springframework.batch.core.step.item.SimpleChunkProvider.provide(SimpleChunkProvider.java:118) ~[spring-batch-core-4.3.0.jar:4.3.0]
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:71) ~[spring-batch-core-4.3.0.jar:4.3.0]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407) ~[spring-batch-core-4.3.0.jar:4.3.0]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331) ~[spring-batch-core-4.3.0.jar:4.3.0]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.1.jar:5.3.1]
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273) ~[spring-batch-core-4.3.0.jar:4.3.0]
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82) ~[spring-batch-core-4.3.0.jar:4.3.0]
	at org.springframework.batch.repeat.support.TaskExecutorRepeatTemplate$ExecutingRunnable.run(TaskExecutorRepeatTemplate.java:262) ~[spring-batch-infrastructure-4.3.0.jar:4.3.0]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

My `application.properties` is:

```
spring.job-datasource.jdbcUrl=jdbc:sqlserver://localhost;databaseName=ac_img_p
spring.job-datasource.username=sa
spring.job-datasource.password=StR0nGp4ss.
spring.job-datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.job-datasource.initialization-mode=always
```

**Comment by lilgreenbird** [comment]
hi @jeusdi ,
Is this reproducible and can you please share the code and your database schema you were running when you saw this issue?

**Comment by peterbae** [comment]
Hi @jeusdi, did you have an update on this?

**Comment by peterbae** [comment]
Closing the issue due to inactivity, feel free to re-open this if the issue comes back and there's more information.
