### ISSUE TITLE
mssql-jdbc/ADA4J for Spring 2.4

### ISSUE THREAD

**Issue by carlmendoza** [microsoft/mssql-jdbc#1480]
Hi, I am in the process of migrating a project from Spring 2.3 to 2.4 but was getting this error:

`2020-12-10T09:39:00.581369532Z ERROR   [2020-12-345 09:39:00.580] [user: -] [cid: -] [main] [c.z.h.p.HikariPool] - HikariPool-1 - Exception during pool initialization.
2020-12-10T09:39:00.581408235Z com.microsoft.sqlserver.jdbc.SQLServerException: Failed to authenticate the user xxx in Active Directory (Authentication=ActiveDirectoryPassword).
2020-12-10T09:39:00.581418335Z 	at com.microsoft.sqlserver.jdbc.SQLServerADAL4JUtils.getSqlFedAuthToken(SQLServerADAL4JUtils.java:62)
2020-12-10T09:39:00.581425736Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.getFedAuthToken(SQLServerConnection.java:4442)
2020-12-10T09:39:00.581432536Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:4415)
2020-12-10T09:39:00.581439237Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:4380)
2020-12-10T09:39:00.581445937Z 	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:289)
2020-12-10T09:39:00.581452738Z 	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:125)
2020-12-10T09:39:00.581459138Z 	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
2020-12-10T09:39:00.581465639Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:5233)
2020-12-10T09:39:00.581472139Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:3988)
2020-12-10T09:39:00.581478640Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:3932)
2020-12-10T09:39:00.581485240Z 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7375)
2020-12-10T09:39:00.581491641Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3206)
2020-12-10T09:39:00.581498141Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2713)
2020-12-10T09:39:00.581504642Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2362)
2020-12-10T09:39:00.581511142Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2213)
2020-12-10T09:39:00.581531343Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1276)
2020-12-10T09:39:00.581538244Z 	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:861)
2020-12-10T09:39:00.581544644Z 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
2020-12-10T09:39:00.581551145Z 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
2020-12-10T09:39:00.581558645Z 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
2020-12-10T09:39:00.581565546Z 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
2020-12-10T09:39:00.581572246Z 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
2020-12-10T09:39:00.581578647Z 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
2020-12-10T09:39:00.581585547Z 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
2020-12-10T09:39:00.581592048Z 	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:266)
2020-12-10T09:39:00.581598748Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1847)
2020-12-10T09:39:00.581605549Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784)
2020-12-10T09:39:00.581612249Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609)
2020-12-10T09:39:00.581619050Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
2020-12-10T09:39:00.581625850Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
2020-12-10T09:39:00.581632450Z 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
2020-12-10T09:39:00.581639251Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
2020-12-10T09:39:00.581645751Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
2020-12-10T09:39:00.581652252Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
2020-12-10T09:39:00.581658752Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
2020-12-10T09:39:00.581665353Z 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1161)
2020-12-10T09:39:00.581671853Z 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915)
2020-12-10T09:39:00.581678654Z 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588)
2020-12-10T09:39:00.581690655Z 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
2020-12-10T09:39:00.581697655Z 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
2020-12-10T09:39:00.581704055Z 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
2020-12-10T09:39:00.581710556Z 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
2020-12-10T09:39:00.581717056Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
2020-12-10T09:39:00.581723357Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)
2020-12-10T09:39:00.581729757Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)
2020-12-10T09:39:00.581736158Z 	at uk.gov.defra.reach.notify.ReachNotifyApplication.main(ReachNotifyApplication.java:18)
2020-12-10T09:39:00.581742558Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-10T09:39:00.581748859Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2020-12-10T09:39:00.581755259Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2020-12-10T09:39:00.581761760Z 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2020-12-10T09:39:00.581768260Z 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
2020-12-10T09:39:00.581774760Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
2020-12-10T09:39:00.581781061Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
2020-12-10T09:39:00.581787461Z 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
2020-12-10T09:39:00.581794162Z Caused by: java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: com/nimbusds/oauth2/sdk/http/CommonContentTypes
2020-12-10T09:39:00.581800862Z 	at com.microsoft.sqlserver.jdbc.SQLServerADAL4JUtils.getSqlFedAuthToken(SQLServerADAL4JUtils.java:60)
2020-12-10T09:39:00.581807563Z 	... 53 common frames omitted
2020-12-10T09:39:00.581813763Z Caused by: com.microsoft.aad.adal4j.AuthenticationException: com/nimbusds/oauth2/sdk/http/CommonContentTypes
2020-12-10T09:39:00.581820264Z 	at com.microsoft.sqlserver.jdbc.SQLServerADAL4JUtils.getSqlFedAuthToken(SQLServerADAL4JUtils.java:53)`

My pom have:

      <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>8.4.1.jre11</version>
            <scope>provided</scope>
        </dependency>
      <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>adal4j</artifactId>
            <version>1.6.5</version>
            <scope>runtime</scope>
        </dependency>

Is there anything I have missed out upgrading from Spring 2.3 to 2.4, thanks.

**Comment by ulvii** [comment]
Hi @carlmendoza ,

Are you using the same version of the driver for both Spring 2.3 and 2.4?

This is an authentication failure and I am not sure why migrating to newer Spring would cause it, perhaps you could look for changes in authentication logic in Spring?

**Comment by lilgreenbird** [comment]
hi @carlmendoza ,

Please let us know if you have more info or require more assistance with this?

**Comment by lilgreenbird** [comment]
closing due to inactivity
