### ISSUE TITLE
JDBC sends TLS 1.3 as handled protocol, when it fails to connect when using it

### ISSUE THREAD

**Issue by adrklos** [microsoft/mssql-jdbc#1524]
## Driver version
8.2.2.jre8

## SQL Server version
None (It didn't happen during direct connection to SQL Server database, but during using proxy.)

## Client Operating System
Ubuntu 20.04

## JAVA/JVM version
11.0.9 AdoptOpen

## Table schema
None

## Problem description

**1. Expected behaviour:** Successfully opened connection with using TLS.
**2. Actual behaviour:** Trying to reconnect until throwing an exception.
**3. Error message/stack trace:**
```
com.microsoft.sqlserver.jdbc.SQLServerException: Connection reset ClientConnectionId:adad76c9-f08b-477b-ad7c-6ea9240f2c54
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2998)
	at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2034)
	at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6446)
	at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7612)
	at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7575)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:5172)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:3810)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$000(SQLServerConnection.java:94)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:3754)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7225)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3053)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2562)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2216)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2067)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1204)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:825)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at aaaa.TestingApplication.main(TestingApplication.java:12)
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2026)
	... 17 more

```
**4. Any other details that can be helpful:**
Main problem is that TLS 1.3 is send as enabled protocol, in ClientHello packet of TLS handshake. That causes that server, which is reading that packet, can choose this protocol to be used for the rest of TLS handshake process. When TLS 1.3 is used for the rest of the process, MSSQL JDBC doesn't send Client Change Cipher Spec packet, which is expected by a server's side. That causes that next packet, which is packet with encrypted authentication, is read as Client Change Cipher Spec packet, what can cause an exception on server's side ([TLS 1.3 protocol](https://tls13.ulfheim.net/)). After our analysis, we suspect that the main problem is a `flush()` method of `SSLHandshakeOutputStream` class, because object of that class is inside code of `SSLEngine` class, and the method is only logging calls.

We don't expect that the problem gonna be resolved quickly, but more like in the far future (because there are no information about using TLS 1.3 by SQLServer database, so even when sent, a database is going to choose TLS 1.2), this report's intention is just to let you know about this incident as it may be more problematic in the future. What we could suggest, is to disable TLS 1.3 protocol in SSLEngine for now, so newer versions of Java wouldn't make that problem, or to adjust the code to be suited to work with TLS 1.3. 

## JDBC trace logs
I don't have them, but if they are needed for this incident, I can get them.

## Reproduction code
Code:
```
        try (Connection connection = DriverManager
            .getConnection("jdbc:sqlserver://localhost:1433;databaseName=master", "randomuser",
                "randompassword")) {

            Statement stmt = connection.createStatement();
            stmt.execute("SELECT 1");
        } catch (SQLException exception) {
            exception.printStackTrace();
        }
```

**Comment by lilgreenbird** [comment]
hi @adrklos 

Starting with the [8.3.1 preview release](https://github.com/microsoft/mssql-jdbc/releases/tag/v8.3.1) the driver will throw a warning when the TLS version lower than 1.2 is negotiated.

**Comment by lilgreenbird** [comment]
hi @adrklos 

Sorry I responded to this a bit too fast the warning is thrown when the TLS version is lower than 1.2 but it won't throw an error for 1.3. TLS 1.3 is not supported yet we are waiting for this on the server side before we can look into this at our end.

**Comment by ebrandsberg** [comment]
Adding to this (I work with Adrklos), If you want to get ahead of the curve on developing for TLS 1.3, we have support in our proxy for TLS 1.3 already, which is where we encountered the issue.  We have disabled it for negotiations now with our SQL server code, but we could provide code that the JDBC driver can test against to ensure support for TLS 1.3.  This will help ensure that when supported on the server side, any updated clients will be ready for it.  We already support TLS 1.3 for our MySQL and Postgres code, and would be more than willing to help prepare this driver as well.

**Comment by David-Engel** [comment]
@ebrandsberg We went through TLS 1.3 testing with the server and windows teams over a year ago and found that the TDS design of using TLS over TDS doesn't work well with TLS 1.3. The current TDS design assumes that the TLS channel (used during login) cannot carry anything but an application_data record from client to server, as soon as the TLS handshake is completed. This assumption was never correct, but was rarely violated in TLS <= 1.2. With TLS 1.3, the assumption is frequently incorrect and connections usually fail. So more in-depth changes are need to the design of the TDS protocol in order to support it. That design process is happening on the server-side first.

While it would be great to get some client-side only testing and we definitely appreciate the offer, I think the time spent might be wasted as I believe more in-depth TDS changes will need to happen for both client and server sides to support TLS 1.3.

Thanks,
David

**Comment by lilgreenbird** [comment]
closing as this requires no action on the driver right now we will be looking into this when it is supported on the server side.
