### ISSUE TITLE
Thread hanging indefinitely during connect Prelogin socket read even with login timeout set

### ISSUE THREAD

**Issue by ryanrupp** [microsoft/mssql-jdbc#1529]
## Driver version
8.2.1.jre8

## SQL Server version
Microsoft SQL Server 2008 R2 (SP3) - 10.50.6000.34 (X64) Aug 19 2014 12:21:34 Copyright (c) Microsoft Corporation Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)

## Client Operating System
Ubuntu 16.04

## JAVA/JVM version
OpenJDK 1.8.181

## Table schema
N/A

## Problem description
We encountered some event (network partition?) that resulted in the connection thread hanging indefinitely on a socket read with the following call stack:

```
"HikariPool-6 connection adder" #6541 daemon prio=5 os_prio=0 tid=0x00007f5370012800 nid=0x20a7 runnable [0x00007f53323ee000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2026)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.Prelogin(SQLServerConnection.java:2709)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2554)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2216)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2067)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1204)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:825)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

We actually had 6 connection pools (app is aggregating from many databases), 2 of which the connection pool adder thread was stuck indefinitely on the above code. This becomes apparent because the pooling library we're using ([HikariCP](https://github.com/brettwooldridge/HikariCP)) uses a single thread for connection acquisition so when it was stuck indefinitely like this future connections were not able to be spawned and the pool exhausted. We **did** have a login timeout of 30 seconds set though however we don't globally have `SO_TIMEOUT` set (we have some longer running queries so we want login timeout to be more aggressive but to globally set socket timeout it would have to be a fairly large value). When we restarted the application it was able to connect to the database without issue.

Anyway, while we don't think the JDBC driver caused the issue (probably is something on the remote side, connection was over a VPN and various networking factors involved) ideally `login timeout` would be pushed down as the socket timeout during connect time so even if we don't have `SO_TIMEOUT` set globally this will safeguard against this scenario. It looks like the "socket connect" part is applying the timeout as it pushes down the timeout all the way to the `connect` [here](https://github.com/microsoft/mssql-jdbc/blob/567ae6ee992f81e945bead5be05a36ab2c744fe5/src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java#L2689) - however somehow we managed to make it past that point and got to the `Prelogin` step which then hangs on the socket read. Wondering if [here](https://github.com/microsoft/mssql-jdbc/blob/dev/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L2746) where the `TDSChannel` is established could this be in a `try/finally` where it temporarily sets the socket timeout so that all subsequent actions during "login" are safeguarded by the login timeout? E.g.

```
tdsChannel = new TDSChannel(this);
tdsChannel.open(... ) // with timeout

// guard the next operations with login timeout
int originalTimeout = tdsChannel.getNetworkTimeout();
tdsChannel.setNetworkTimeout(timeOutSliceInMillis);
try {
    // do remaining operations e.g. Prelogin
} finally {
    // set back (probably doesn't even need finally as if an exception is thrown not sure it makes sense to try to set this back
   tdsChannel.setNetworkTimeout(originalTimeout);
}
```

HikariCP itself actually does `setNetworkTimeout` guards like this for pooling operations it does, see [here](https://github.com/brettwooldridge/HikariCP/blob/5efab340e8bb4229eadbef3e388ed027ff0bef4d/src/main/java/com/zaxxer/hikari/pool/PoolBase.java#L401) however it only does this after actually having a `Connection` available to set this on so the the original `getConnection` call [here](https://github.com/brettwooldridge/HikariCP/blob/5efab340e8bb4229eadbef3e388ed027ff0bef4d/src/main/java/com/zaxxer/hikari/pool/PoolBase.java#L364) cannot be guarded like that which is where we experienced this issue.

## JDBC trace logs
Unable to reproduce unfortunately with trace logs enabled

## Reproduction code
Unable to reproduce on demand although it could probably be reproduced by artificially hanging the socket response.

**Comment by ryanrupp** [comment]
As a workaround we will probably consider setting SO_TIMEOUT via the JDBC URL or properties to some lower value (e.g. 30 seconds to match login timeout) and then once we get the `Connection` back programmatically call `setNetworkTimeout` setting it to some value larger than our slowest query.

**Comment by peterbae** [comment]
Hi @ryanrupp, thanks for bringing this to our attention. I think your suggestion definitely makes sense, and I feel that this is something the team should review and implement so that if the user sets the login timeout, it gets applied to sockets as well during the login process. The team will add this to the backlog of features and will let you know once we have an update.

**Comment by ecki** [comment]
The fix #2280 is in 12.6

**Comment by Jeffery-Wasty** [comment]
Yes, thank you for noticing this, this is resolved in 12.6.

**Comment by lilgreenbird** [comment]
thanks yes @ryanrupp could you please give the latest [12.6.0](https://github.com/microsoft/mssql-jdbc/releases/tag/v12.6.0) a try to see if it resolves your issue?

@ecki do you know what these Oracle properties are called so we investigate if we want to consider something similar?

**Comment by ecki** [comment]
It’s  TRANSPORT_CONNECT_TIMEOUT in milliseconds for the time allowed to open a single tcp connection. If that one fails it does retries for CONNECT_TIMEOUT before going to another server and loginTimeout for this plus the login response time. After that you can set only a socket read timeout which is however not very flexible since it needs to covermlongest statement runtime.

**Comment by globalillo** [comment]
@lilgreenbird The Informix driver, similar to Oracle's driver with TRANSPORT_CONNECT_TIMEOUT, also includes the INFORMIXCONTIME parameter as a TCP timeout specific to the connection phase. Once the connection is established, it switches the socket timeout to the value configured in IFX_SOC_TIMEOUT (similar to mssql-jdbc's socketTimeout).

We encounter the same stack trace in 12.8 when the driver successfully establishes a TCP connection (successfully performs the TCP handshake), but the server fails to respond with any data during the prelogin phase.

```
"mssql-pool connection adder" #51 daemon prio=5 os_prio=0 cpu=6.85ms elapsed=50.38s tid=0x00007fbe5001c620 nid=0xf983e runnable  [0x00007fbed59e7000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.SocketDispatcher.read0(java.base@17.0.13/Native Method)
        at sun.nio.ch.SocketDispatcher.read(java.base@17.0.13/SocketDispatcher.java:47)
        at sun.nio.ch.NioSocketImpl.tryRead(java.base@17.0.13/NioSocketImpl.java:266)
        at sun.nio.ch.NioSocketImpl.implRead(java.base@17.0.13/NioSocketImpl.java:317)
        at sun.nio.ch.NioSocketImpl.read(java.base@17.0.13/NioSocketImpl.java:355)
        at sun.nio.ch.NioSocketImpl$1.read(java.base@17.0.13/NioSocketImpl.java:808)
        at java.net.Socket$SocketInputStream.read(java.base@17.0.13/Socket.java:966)
        at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1206)
        at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:1192)
        at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2166)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.prelogin(SQLServerConnection.java:3981)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3793)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3385)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:3194)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1971)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1263)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
        at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
        at java.util.concurrent.FutureTask.run(java.base@17.0.13/FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.13/ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.13/ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(java.base@17.0.13/Thread.java:840)

```

I think the original issue is not resolved.
