### ISSUE TITLE
Can´t connect  Permission denied: no further information

### ISSUE THREAD

**Issue by JohelCastilloV** [microsoft/mssql-jdbc#1544]
## Driver version

        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>6.2.2.jre8</version>
        </dependency>

## SQL Server version

Microsoft SQL Server 2008 R2 (SP3-GDR) (KB4057113) - 10.50.6560.0 (X64) 
	Dec 28 2017 15:03:48 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)

## Client Operating System

Windows
## JAVA/JVM version

1.8.0
Azure function Operating System Windows jdk8

## Problem description
i cant connect to a database from java  ,however in c# using sqlclient package I can.
Connection string  using sqlclient  in c#:
this works
Server=172.16.129.62\\bdm,61862; Initial Catalog=myDatabase;

but when I use java cant connect.
I tried with many connection strings, 
Connection String 1
jdbc:sqlserver://172.16.129.62\bdm:61862;databaseName=myDatabase;
Error
Exception: The TCP/IP connection to the host 172.16.129.62, port 61862 has failed. Error: "Permission denied: no further information. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
Stack: com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host 172.16.129.62, port 61862 has failed. Error: "Permission denied: no further information. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:227)
	at com.microsoft.sqlserver.jdbc.SQLServerException.ConvertConnectExceptionToSQLServerException(SQLServerException.java:284)
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2435)
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:635)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2010)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:1687)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1528)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:866)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:569)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)

Connection String 2
jdbc:sqlserver://172.16.129.62\bdm;databaseName=Interfondos;
Error
Exception: The connection to the host 172.16.129.62, named instance bdm failed. Error: "java.net.SocketTimeoutException: Receive timed out". Verify the server and instance names and check that no firewall is blocking UDP traffic to port 1434.  For SQL Server 2005 or later, verify that the SQL Server Browser Service is running on the host.
Stack: com.microsoft.sqlserver.jdbc.SQLServerException: The connection to the host 172.16.129.62, named instance bdm failed. Error: "java.net.SocketTimeoutException: Receive timed out". Verify the server and instance names and check that no firewall is blocking UDP traffic to port 1434.  For SQL Server 2005 or later, verify that the SQL Server Browser Service is running on the host.

Connection String 3
jdbc:sqlserver://172.16.129.62:61862;instanceName=bdm;databaseName=Interfondos;

Error:
Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: Application Exception
Exception: The TCP/IP connection to the host 172.16.129.62, port 61862 has failed. Error: "Permission denied: no further information. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
Stack: com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host 172.16.129.62, port 61862 has failed. Error: "Permission denied: no further information. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:227)
	at com.microsoft.sqlserver.jdbc.SQLServerException.ConvertConnectExceptionToSQLServerException(SQLServerException.java:284)
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2435)
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:635)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2010)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:1687)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1528)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:866)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:569)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)

Connection String 4
jdbc:sqlserver://172.16.129.62;instanceName=bdm;databaseName=Interfondos;

Error:
Exception: The connection to the host 172.16.129.62, named instance bdm failed. Error: "java.net.SocketTimeoutException: Receive timed out". Verify the server and instance names and check that no firewall is blocking UDP traffic to port 1434.  For SQL Server 2005 or later, verify that the SQL Server Browser Service is running on the host.
Stack: com.microsoft.sqlserver.jdbc.SQLServerException: The connection to the host 172.16.129.62, named instance bdm failed. Error: "java.net.SocketTimeoutException: Receive timed out". Verify the server and instance names and check that no firewall is blocking UDP traffic to port 1434.  For SQL Server 2005 or later, verify that the SQL Server Browser Service is running on the host.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:227)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.getInstancePort(SQLServerConnection.java:5241)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.primaryPermissionCheck(SQLServerConnection.java:1916)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:1669)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1528)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:866)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:569)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)

4. Any other details that can be helpful:

## Reproduction code

        try {
            Connection conn = DriverManager.getConnection(dburl,dbuser,dbpassword);
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("select 1");
            context.getLogger().info(rs.toString());
        }catch (Exception e){
            context.getLogger().log(Level.SEVERE,"Application Exception",e);
        }

**Comment by lilgreenbird** [comment]
hi @JohelCastilloV 

Can you please check if you have TCP/IP enabled on your SQL Server?

![image](https://user-images.githubusercontent.com/8549794/111740285-b7a18600-8841-11eb-962d-7fdabe7120e4.png)

If so, can you please try to see if you can connect with the same connection string and user/password using SSMS?

**Comment by vient0** [comment]
hi @lilgreenbird 

I'm in the same team with @JohelCastilloV.

Yes we can connect via SSMS with the same user/password, with a connection string from a .Net Function and even from the CMD console of the same Java Function using sqlcmd.

**Comment by lilgreenbird** [comment]
That is very strange. I noticed you are using a very old driver version could you please try with the [latest](https://github.com/microsoft/mssql-jdbc/releases/tag/v9.2.1)? 

Also, could you check your firewall configuration to see if it's only allowing certain apps? If possible could you run the test with the firewall disabled?

**Comment by lilgreenbird** [comment]
hi @vient0 

This is really strange. Can you help me understand your environment, where is this SQL Server hosted and where are you running the client code? Windows NT 6.1 is Windows 7, the SQL Server 2008 R2 [docs](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms143506(v=sql.105)?redirectedfrom=MSDN) states that the min requirement is Windows Server 2012 or Windows 8. Windows 7 has reached end of life it's no longer in the driver's support matrix. Having said that however I'm surprised that it wouldn't connect at all tho. Can you upgrade the OS and the latest SQL Server version? Or do you have another SQL Server you could try?

You mentioned you have a case with Azure support are you running these in an Azure VM? Is the client code run from another VM? If so, you have to add that VM to the firewall rules on the portal. I believe you can't simply open all ports there is an auto deny all rule that kicks in automatically. Are you connecting via SSMS from within the same machine/VM as the client code? I'm just thinking of different possibilities as this is very strange I can't think of any good reasons why this isn't working there must be something special about your environment?

Could you also enable logging on the driver and provide the logs?

**Comment by lilgreenbird** [comment]
Closing due to inactivity. Please let us know if you have further updates and would like us to re-open this issue.

**Comment by vient0** [comment]
Sorry for the late response. We were able to find the solution by changing the Hybrid Connection from IP addresses to DNS names. Either way it was very strange but we hope this solution helps anyone with the same error.

**Comment by lilgreenbird** [comment]
that's good to know you've resolved your issue, thanks!
