### ISSUE TITLE
[QUESTION] ActiveDirectoryServicePrincipal, doesn't it need the tenant-id?

### ISSUE THREAD

**Issue by J-CMartin** [microsoft/mssql-jdbc#1560]
## Question
I'm trying to use the new authentication ActiveDirectoryServicePrincipal but it's giving me an error:

Failed to authenticate the user XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX in Active Directory (Authentication=ActiveDirectoryServicePrincipal).

On my MSAL code, I need to pass clientID, client secret and an "authority" which is an URL with my Tenant-id on it but I don't see where to pass that information to the JDBC driver and I'm wondering if that could be the cause of the issue?

**Comment by lilgreenbird** [comment]
hi @J-CMartin 

Yes, here is a [link](https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver15#connecting-using-activedirectoryserviceprincipal-authentication-mode) to the documentation and sample code to use `ActiveDirectoryServicePrincipal`.

**Comment by J-CMartin** [comment]
I'm trying to use DbVisualizer (or other tools that use JDBC) to connect to Azure SQL using AAD Authentication but it's failing. 
If I use Python MSAL I'm able to get an Authentication token but if I try to use the JDBC by itself, it always fails to authenticate. So far I've tried different Authentication methods (Password, Interactive and Service Principal) and they all have failed

This is my url:
`jdbc:sqlserver://SERVER.database.windows.net:1433;database=DATABASE;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=60;authentication=ActiveDirectoryServicePrincipal`

Along with the URL, I'm passing the following parameters:
AADSecurePrincipalSecret = SECRET
AADSecurePrincipalId = CLIENT_ID
applicationName = dbvis


2021-04-08 16:01:40.447 FINE   242 [pool-5-thread-27 - e.b] RootConnection: EXCEPTION -> com.microsoft.sqlserver.jdbc.SQLServerException: Failed to authenticate the user xxxxxxxxxxxxxxxxxxx in Active Directory (Authentication=ActiveDirectoryServicePrincipal).
java.lang.RuntimeException: com/nimbusds/common/contenttype/ContentType
	at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getCorrectedException(SQLServerMSAL4JUtils.java:219)
 [wrapped] java.util.concurrent.ExecutionException: java.lang.RuntimeException: com/nimbusds/common/contenttype/ContentType
	at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getCorrectedException(SQLServerMSAL4JUtils.java:225)
 [wrapped] com.microsoft.sqlserver.jdbc.SQLServerException: Failed to authenticate the user 916d3acd-6731-481a-9b8a-9586a7c45c2f in Active Directory (Authentication=ActiveDirectoryServicePrincipal).
	at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getCorrectedException(SQLServerMSAL4JUtils.java:227)
	at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getSqlFedAuthTokenPrincipal(SQLServerMSAL4JUtils.java:91)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.getFedAuthToken(SQLServerConnection.java:4539)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:4498)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:4458)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:289)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:125)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:5333)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4066)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$000(SQLServerConnection.java:85)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4004)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3272)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2768)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2265)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1291)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:881)
	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.onseven.dbvis.jdbc.b.e.b(Z:2153)
	at com.onseven.dbvis.jdbc.b.g$_b.call(Z:3572)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by J-CMartin** [comment]
> hi @J-CMartin
> 
> Yes, here is a [link](https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver15#connecting-using-activedirectoryserviceprincipal-authentication-mode) to the documentation and sample code to use `ActiveDirectoryServicePrincipal`.

The link still refers to ADAL library, but it looks like version 9.2.1 has already migrated to MSAL4J.

**Comment by lilgreenbird** [comment]
you're right thank you! we will get that updated!!

**Comment by lilgreenbird** [comment]
fyi here is the [wiki](https://github.com/microsoft/mssql-jdbc/wiki/Download-MSAL4J-And-AKV-Dependencies-with-Apache-Maven) to download the MSAL4J library if you haven't done that already.

**Comment by J-CMartin** [comment]
I have downloaded the msal4j library and all dependencies, I was able to get a successful connection from a computer outside our corporate firewall, but I'm unable to connect from inside our corporate network,  

All our internet traffic goes thru a Proxy, but I cannot find a way to setup mssql-jdbc driver to use a proxy. 

The proxy is a http proxy without authentication.  I've tried setting up env variables and passing http_proxy to JVM without any success. Any ideas?

Thanks

**Comment by lilgreenbird** [comment]
hi @J-CMartin 

@sehrope had recently created a [PR](https://github.com/microsoft/mssql-jdbc/pull/1217) that allows to use a custom socket factory that delegates to a SOCKS proxy to tunnel the connection. This PR was merged into the 9.1 release so if you are on the latest driver release you should have access to the new [connection property](https://docs.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver15). You can take a look at this [test](https://github.com/microsoft/mssql-jdbc/blob/dev/src/test/java/com/microsoft/sqlserver/jdbc/socketfactory/CustomSocketFactoryTest.java) to get an idea on how to use the connection property.

**Comment by lilgreenbird** [comment]
Closing due to inactivity. Please let us know if you have further updates and would like us to re-open this issue.
