### ISSUE TITLE
socketFactoryClass property is ignored during login method

### ISSUE THREAD

**Issue by adligo** [microsoft/mssql-jdbc#1588]
## Driver version
9.2

## SQL Server version
Microsoft SQL Azure (RTM) - 12.0.2000.8   Apr 29 2021 13:52:20   Copyright (C) 2019 Microsoft Corporation 

## Client Operating System
Windows 10

## JAVA/JVM version
JDK 15 something

## Table schema
any and all

## Problem description
1. Expected behaviour:
  The socketFactoryClass would be used for a https proxy connection during the login method,
so that JDBC could connect through a https proxy to Azure.
2. Actual behaviour:
   The setting is ignroed
3. Error message/stack trace:
Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host EXAMPLE_REMOVED, port 1433 has failed. Error: "null. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:234)
	at com.microsoft.sqlserver.jdbc.SQLServerException.ConvertConnectExceptionToSQLServerException(SQLServerException.java:285)
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2466)
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:672)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2747)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2265)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1291)
	at com.microsoft.sqlserver.jdbc.SQLServerDataSource.getConnectionInternal(SQLServerDataSource.java:1257)
	at com.microsoft.sqlserver.jdbc.SQLServerDataSource.getConnection(SQLServerDataSource.java:85)
4. Any other details that can be helpful:
I am trying to fork and patch!
line 1685 is called and before the error on line 2418
   socketFactoryClass = activeConnectionProperties                    
    .getProperty(SQLServerDriverStringProperty.SOCKET_FACTORY_CLASS.toString());

## Reproduction code
 ds.setSocketFactoryClass(LoggingSocketFactory.class.getName());

public class LoggingSocketFactory extends SocketFactory {
  @Override
  public Socket createSocket() throws IOException {
    println("createSocket");
    return super.createSocket();
  }

  @Override
  public Socket createSocket(String host, int port) throws IOException, UnknownHostException {
    println(String.format("LoggingSocketFactory host %s port %d", host, port));
    return null;
  }
etc ....

**Comment by adligo** [comment]
Retro fit netty to a Socket extension / implementation and we should be good to go, I tried with the standard java.net.Proxy class, which didn't work and I couldn't tell what was going wrong I just got some high level error messages.
 https://projectreactor.io/docs/netty/release/reference/index.html#_connect_and_disconnect
 4.3. Writing Data
 4.4. Consuming Data

**Comment by v-zhangw** [comment]
Investigating

**Comment by v-zhangw** [comment]
Hi Adligo,

I tried running a test app against SQL Server 2019 and 2017 with a LoggingSocketFactory the same as yours in your "Reproduction" step except with all the other overrides implemented with default implementation and println -> System.out.println.

It appears that the setSocketFactoryClass function is working just fine as I'm seeing several lines of "createSocket" until an 'Error: "Unconnected sockets not implemented...' error.

Could you provide a more complete reproduction so we get more clues as to why you are running into this issue?

**Comment by adligo** [comment]
Sure, as I debugged through the code I made this change;
com.microsoft.sqlserver.jdbc.TDS

    private Socket getConnectedSocket(InetSocketAddress addr, int timeoutInMilliSeconds) throws IOException {
        assert timeoutInMilliSeconds != 0 : "timeout cannot be zero";
        String socketFactoryClass = conn.getSocketFactoryClass();
        //@Adligo a marker to track what I changed
        if (addr.isUnresolved() && socketFactoryClass == null)
            throw new java.net.UnknownHostException("A custom socketFactoryClass "
                + "MAY be used to connect through a Https proxy @see;\n" + ProxySocketFactory.class);
        selectedSocket = getSocketFactory(addr.getHostName() + ":" + addr.getPort()).createSocket();
        if (!selectedSocket.isConnected()) {
            selectedSocket.connect(addr, timeoutInMilliSeconds);
        }
        return selectedSocket;
    }

Although I solve my actual issue in another way.  I was at a client site and as it turns out there was no proxy involved, I had simply been given the wrong server host name (SSMS vs JDBC) the host names MAY not be the same.
  If you want to see the other code that I would contribute let me know, it is quite extensive change to the way proxying would work.

**Comment by v-zhangw** [comment]
To clarify,
Are you still experiencing the issue of "socketFactoryClass property is ignored"?
And if so, could you please share your reproduction (sample application) which would trigger that issue?

**Comment by v-zhangw** [comment]
Hello,

We are closing this issue due to inactivity, if anyone encounters this again we can reopen.
