### ISSUE TITLE
Using TVP is causing TDS protocol error

### ISSUE THREAD

**Issue by roy-saikat** [microsoft/mssql-jdbc#1605]
## Driver version
9.2.0.jre11

## SQL Server version
Microsoft SQL Server 2019 (RTM-CU9) (KB5000642) - 15.0.4102.2 (X64) 	Jan 25 2021 20:16:12 	Copyright (C) 2019 Microsoft Corporation	Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor)

## Client Operating System
Mac OS Big Sur 11.4
Windows 10

## JAVA/JVM version
OpenJDK 16.0.1

## Table schema
-- TABLE
`create table Identities
(
    ID INT PRIMARY KEY
)`

-- TVP TYPE
	CREATE TYPE dbo.IntegersPK AS TABLE
		( Token INT NOT NULL
		, PRIMARY KEY CLUSTERED (Token)
		)
	GRANT EXECUTE ON TYPE::dbo.IntegersPK TO [public]

-- STORED PROC
IF NOT EXISTS (SELECT * FROM sys.procedures WHERE name = 'test'
			AND schema_id = SCHEMA_ID('dbo'))
	EXEC ('CREATE PROCEDURE dbo.test AS RETURN')
GO

ALTER proc dbo.test
@securityIds dbo.integersPK READONLY
AS
BEGIN
    select sm.ID from Identities sm WITH (NOLOCK)
    join @securityIds s ON (sm.ID = s.Token)
END
GO

GRANT EXECUTE ON dbo.test TO [public]

## Problem description

1. Expected - When using TVP appropriately, we should be able to pass in a large number of rows in the TVP.
2. Actual behavior - TDS protocol error causes statement and/or result set to be closed unexpectedly.
3. Error message/stack trace:
Jun 25, 2021 12:00:21 AM com.microsoft.sqlserver.jdbc.TDSParser throwUnexpectedTokenException
SEVERE: TDSReader@7 (ConnectionID:2 ClientConnectionId: 45c72f34-c8f3-4888-ae60-6e88fa6f7fcb): getNextResult: Encountered unexpected TDS_ROW (0xD1)
Jun 25, 2021 12:00:21 AM com.microsoft.sqlserver.jdbc.TDSReader throwInvalidTDSToken
SEVERE: TDSReader@7 (ConnectionID:2 ClientConnectionId: 45c72f34-c8f3-4888-ae60-6e88fa6f7fcb) got unexpected value in TDS response at offset:1251
Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: The result set is closed.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:234)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.checkClosed(SQLServerResultSet.java:450)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getInt(SQLServerResultSet.java:2334)
4. Any other details that can be helpful:
We have tried using WITH (NOLOCK), and without that. Both times, same types of problem exists. If you run the driver app, it should reproduce the error on the first try. If not, please run the driver app a few times. 

## JDBC Connection String
1265012928, URL=jdbc:sqlserver://sql-server:1433;maxResultBuffer=-1;sendTemporalDataTypesAsStringForBulkCopy=true;delayLoadingLobs=true;useFmtOnly=false;useBulkCopyForBatchInsert=false;cancelQueryTimeout=-1;sslProtocol=TLS;jaasConfigurationName=SQLJDBCDriver;statementPoolingCacheSize=0;serverPreparedStatementDiscardThreshold=10;enablePrepareOnFirstPreparedStatementCall=false;fips=false;socketTimeout=0;authentication=NotSpecified;authenticationScheme=nativeAuthentication;xopenStates=false;sendTimeAsDatetime=true;trustStoreType=JKS;trustServerCertificate=false;TransparentNetworkIPResolution=true;serverNameAsACE=false;sendStringParametersAsUnicode=true;selectMethod=direct;responseBuffering=adaptive;queryTimeout=-1;packetSize=8000;multiSubnetFailover=false;loginTimeout=15;lockTimeout=-1;lastUpdateCount=true;encrypt=false;disableStatementPooling=true;databaseName=lm;columnEncryptionSetting=Disabled;applicationName=Microsoft JDBC Driver for SQL Server;applicationIntent=readwrite;, Microsoft JDBC Driver 9.2 for SQL Server

## JDBC trace logs
[JDBCDriverTrace.log](https://github.com/microsoft/mssql-jdbc/files/6713566/JDBCDriverTrace.log)

## Reproduction code

import com.ca.sql.DataSources;
import com.microsoft.sqlserver.jdbc.ISQLServerCallableStatement;
import com.microsoft.sqlserver.jdbc.SQLServerDataTable;

import javax.sql.DataSource;
import java.io.BufferedReader;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) throws Exception {

        try(BufferedReader reader = new BufferedReader(new FileReader("IDs.csv"))) { // the csv file contains 500,000 random integer values
            String secId;
            List<Integer> securityIds = new ArrayList<>();
            while((secId = reader.readLine()) != null) {
                securityIds.add(Integer.valueOf(secId));
                if(securityIds.size() == 10000) {
                    System.out.println("starting query");
                    // @TODO
                    DataSource ds = ; // the connection string is given. please create a datasource with default options.

                    try(Connection conn = ds.getConnection(); 
                        ISQLServerCallableStatement stmt = conn.prepareCall("EXEC dbo.test @securityIds = ?", ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY).unwrap(ISQLServerCallableStatement.class)
                    ) {
                        SQLServerDataTable table = new SQLServerDataTable();
                        table.setTvpName("dbo.IntegersPK");
                        table.addColumnMetadata("Token", Types.INTEGER);
                        for(Integer s : securityIds)
                            table.addRow(s);
                        stmt.setObject(1, table); // tried with using setStructured with similar problems
                        ResultSet rs = stmt.executeQuery();
                        while(rs.next()) {
                            int ID = rs.getInt("ID");
                        }
                    }
                    System.out.println("finished query");
                    securityIds.clear();
                }
            }
        }
    }
}

**Comment by roy-saikat** [comment]
[python-script.txt](https://github.com/microsoft/mssql-jdbc/files/6714085/python-script.txt)

This simple python script works fine. That tells me that there is a bug in the TDS protocol implementation in Java.

**Comment by lilgreenbird** [comment]
hi @roy-saikat 

Can you pls include the csv you used to repro as well?

**Comment by roy-saikat** [comment]
> hi @roy-saikat
> 
> Can you pls include the csv you used to repro as well?

[input.csv](https://github.com/microsoft/mssql-jdbc/files/6720371/input.csv)

Sure. Here is a sample. It is simply a collection of half a million integer values.

**Comment by lilgreenbird** [comment]
hi @roy-saikat 

Thanks, we're quite short in resources currently will try to investigate and get back to you

**Comment by lilgreenbird** [comment]
hi @roy-saikat,

I ran your test app with the csv file you provided, I'm not seeing any errors.

**Comment by roy-saikat** [comment]
> hi @roy-saikat,
> 
> I ran your test app with the csv file you provided, I'm not seeing any errors.

Just happened again on my end. I will try to add more context to the sample app for reproduction steps, and also the network structure we are using.

**Comment by lilgreenbird** [comment]
closing due to inactivity. Please feel free to request re-opening if you have more info.
