### ISSUE TITLE
Not able to build on my local machine due to data type not found sql exception. 

### ISSUE THREAD

**Issue by Avkashhirpara** [microsoft/mssql-jdbc#1611]
I am getting the test failure due to the following exception. 

com.microsoft.sqlserver.jdbc.SQLServerException: Column, parameter, or variable @P0. : Cannot find data type TVP_jdbc_avkash.hirpara_'44c0c0ef-3ab3-40ca-
98cd-ba486e8f0c35.
  at com.microsoft.sqlserver.jdbc.tvp.TVPAllTypesTest.testTVPDataTable(TVPAllTypesTest.java:172)
[ERROR] testQueryDateTVP  Time elapsed: 0.245 s  <<< ERROR!
com.microsoft.sqlserver.jdbc.SQLServerException: Column, parameter, or variable @P0. : Cannot find data type dateTVP_jdbc_avkash.hirpara_'8dc0b177-03a3-4
ea4-bebd-fe5914306ff0.
        at com.microsoft.sqlserver.jdbc.datatypes.DateAndTimeTypeTest.testQueryDateTVP(DateAndTimeTypeTest.java:127)

[ERROR] testQueryTimeTVP  Time elapsed: 0.252 s  <<< ERROR!
com.microsoft.sqlserver.jdbc.SQLServerException: Column, parameter, or variable @P0. : Cannot find data type timeTVP_jdbc_avkash.hirpara_'07614d0f-aa59-4
617-bc92-10a56ba6713e.
        at com.microsoft.sqlserver.jdbc.datatypes.DateAndTimeTypeTest.testQueryTimeTVP(DateAndTimeTypeTest.java:175)

[ERROR] testQueryTimestampTVP  Time elapsed: 0.233 s  <<< ERROR!
com.microsoft.sqlserver.jdbc.SQLServerException: Column, parameter, or variable @P0. : Cannot find data type timestampTVP_jdbc_avkash.hirpara_'9f04b8d3-3
004-4222-b49d-e836563730eb.
        at com.microsoft.sqlserver.jdbc.datatypes.DateAndTimeTypeTest.testQueryTimestampTVP(DateAndTimeTypeTest.java:151)

I am following all the instruction as per the readme.md. 

Thanks, 
Avkash

**Comment by lilgreenbird** [comment]
hi @Avkashhirpara,

Can you tell us how you are building the driver? it looks like the errors are from the tests are these the only failure you are seeing or you can not run any of the junit tests at all? What is the connection string you are using?

**Comment by Avkashhirpara** [comment]
@lilgreenbird 
The failure count is 36 around. and those are due to the above reason "It cannot find the custom data type" 
I am building using maven. 
here is my querystring. 
env.Var : mssql_jdbc_test_connection_properties
value    : jdbc:sqlserver://localhost:5005;database=test2;user=sa;password=sa@123
sql server : 14.0.3048.4

**Comment by lilgreenbird** [comment]
hi @Avkashhirpara 

I'm unsure why you are not able to run the tests. Could you check if you have permission to that database in your SQL server? Did the driver build successfully and were you able to use the driver from a standalone app? It's hard to tell what is in your env that is causing this to happen, can you attach the full Maven log that includes the command you are using to build and run the tests?

**Comment by lilgreenbird** [comment]
closing due to inactivity, please feel free to request re-opening if you have more questions.

**Comment by jocstar** [comment]
I just hit this exact same problem and have found a possible cause. In my case it was down to how the TVP names were created. They use `System.getProperty("user.name")` as part of the name generation, but on my company laptop that value is `firstname.lastname` and I guess the separator there is the problem.
