### ISSUE TITLE
samples\connections\ConnectURL.java: No suitable driver found for jdbc:sqlserver://

### ISSUE THREAD

**Issue by jnahmias** [microsoft/mssql-jdbc#1625]
## Driver version
9.2.1.0

## SQL Server version
ANY

## Client Operating System
```
C:\Users\me\Downloads\sqljdbc_9.2_enu\samples\connections>ver

Microsoft Windows [Version 10.0.19042.1110]
```

## JAVA/JVM version
```
C:\Users\me\Downloads\sqljdbc_9.2_enu\samples\connections>java -version
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
```

## Problem description

1. Expected behaviour:

  Java can find/load the MSSQL JDBC driver

2. Actual behaviour:

  Java complains that it cannot find an appropriate driver

3. Error message/stack trace:
```
C:\Users\me\Downloads\sqljdbc_9.2_enu\samples\connections>java -cp .:..\.. ConnectURL
java.sql.SQLException: No suitable driver found for jdbc:sqlserver://<server>:<port>;databaseName=AdventureWorks;user=<user>;password=<password>
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
        at ConnectURL.main(ConnectURL.java:32)
```

4. Any other details that can be helpful:

I've seen this on Windows & Mac with various JDK versions.

## Reproduction code

```
C:\Users\me\Downloads>unzip sqljdbc_9.2.1.0_enu.zip
Archive:  sqljdbc_9.2.1.0_enu.zip
   creating: sqljdbc_9.2_enu/
   creating: sqljdbc_9.2_enu/auth/
   creating: sqljdbc_9.2_enu/auth/x64/
   creating: sqljdbc_9.2_enu/auth/x86/
   creating: sqljdbc_9.2_enu/samples/
   creating: sqljdbc_9.2_enu/samples/adaptive/
   creating: sqljdbc_9.2_enu/samples/alwaysencrypted/
   creating: sqljdbc_9.2_enu/samples/azureactivedirectoryauthentication/
   creating: sqljdbc_9.2_enu/samples/connections/
   creating: sqljdbc_9.2_enu/samples/constrained/
   creating: sqljdbc_9.2_enu/samples/dataclassification/
   creating: sqljdbc_9.2_enu/samples/datatypes/
   creating: sqljdbc_9.2_enu/samples/resultsets/
   creating: sqljdbc_9.2_enu/samples/sparse/
   creating: sqljdbc_9.2_enu/xa/
   creating: sqljdbc_9.2_enu/xa/x64/
   creating: sqljdbc_9.2_enu/xa/x86/
  inflating: sqljdbc_9.2_enu/auth/x64/mssql-jdbc_auth-9.2.1.x64.dll
  inflating: sqljdbc_9.2_enu/auth/x86/mssql-jdbc_auth-9.2.1.x86.dll
  inflating: sqljdbc_9.2_enu/install.txt
  inflating: sqljdbc_9.2_enu/license.txt
  inflating: sqljdbc_9.2_enu/mssql-jdbc-9.2.1.jre11.jar
  inflating: sqljdbc_9.2_enu/mssql-jdbc-9.2.1.jre15.jar
  inflating: sqljdbc_9.2_enu/mssql-jdbc-9.2.1.jre8.jar
  inflating: sqljdbc_9.2_enu/release.txt
  inflating: sqljdbc_9.2_enu/samples/adaptive/ExecuteStoredProcedures.java
  inflating: sqljdbc_9.2_enu/samples/adaptive/readLargeData.java
  inflating: sqljdbc_9.2_enu/samples/adaptive/updateLargeData.java
  inflating: sqljdbc_9.2_enu/samples/alwaysencrypted/AlwaysEncrypted.java
  inflating: sqljdbc_9.2_enu/samples/azureactivedirectoryauthentication/AzureActiveDirectoryAuthentication.java
  inflating: sqljdbc_9.2_enu/samples/connections/ConnectDataSource.java
  inflating: sqljdbc_9.2_enu/samples/connections/ConnectURL.java
  inflating: sqljdbc_9.2_enu/samples/constrained/ConstrainedDelegation.java
  inflating: sqljdbc_9.2_enu/samples/dataclassification/DataDiscoveryAndClassification.java
  inflating: sqljdbc_9.2_enu/samples/datatypes/BasicDataTypes.java
  inflating: sqljdbc_9.2_enu/samples/datatypes/SpatialDataTypes.java
  inflating: sqljdbc_9.2_enu/samples/datatypes/SqlXmlDataType.java
  inflating: sqljdbc_9.2_enu/samples/resultsets/CacheResultSet.java
  inflating: sqljdbc_9.2_enu/samples/resultsets/RetrieveResultSet.java
  inflating: sqljdbc_9.2_enu/samples/resultsets/UpdateResultSet.java
  inflating: sqljdbc_9.2_enu/samples/sparse/SparseColumns.java
  inflating: sqljdbc_9.2_enu/thirdpartynotices.txt
  inflating: sqljdbc_9.2_enu/xa/x64/sqljdbc_xa.dll
  inflating: sqljdbc_9.2_enu/xa/x86/sqljdbc_xa.dll
  inflating: sqljdbc_9.2_enu/xa/xa_install.sql

C:\Users\me\Downloads>cd sqljdbc_9.2_enu\samples\connections

C:\Users\me\Downloads\sqljdbc_9.2_enu\samples\connections>type ConnectURL.java
/*=====================================================================
File:    ConnectURL.java
Summary: This Microsoft JDBC Driver for SQL Server sample application
         demonstrates how to connect to a SQL Server database by using
                 a connection URL. It also demonstrates how to retrieve data
                 from a SQL Server database by using an SQL statement.
---------------------------------------------------------------------
This file is part of the Microsoft JDBC Driver for SQL Server Code Samples.
Copyright (C) Microsoft Corporation.  All rights reserved.

This source code is intended only as a supplement to Microsoft
Development Tools and/or on-line documentation.  See these other
materials for detailed information regarding Microsoft code samples.

THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF
ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
PARTICULAR PURPOSE.
=====================================================================*/
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class ConnectURL {
    public static void main(String[] args) {

        // Create a variable for the connection string.
        String connectionUrl = "jdbc:sqlserver://<server>:<port>;databaseName=AdventureWorks;user=<user>;password=<password>";

        try (Connection con = DriverManager.getConnection(connectionUrl); Statement stmt = con.createStatement();) {
            String SQL = "SELECT TOP 10 * FROM Person.Contact";
            ResultSet rs = stmt.executeQuery(SQL);

            // Iterate through the data in the result set and display it.
            while (rs.next()) {
                System.out.println(rs.getString("FirstName") + " " + rs.getString("LastName"));
            }
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
C:\Users\me\Downloads\sqljdbc_9.2_enu\samples\connections>javac ConnectURL.java

C:\Users\me\Downloads\sqljdbc_9.2_enu\samples\connections>dir ..\..\*.jar
 Volume in drive C is REDACTED
 Volume Serial Number is REDACTED

 Directory of C:\Users\me\Downloads\sqljdbc_9.2_enu

02/24/2021  01:46 PM         1,338,216 mssql-jdbc-9.2.1.jre11.jar
02/24/2021  01:46 PM         1,352,089 mssql-jdbc-9.2.1.jre15.jar
02/24/2021  01:46 PM         1,327,629 mssql-jdbc-9.2.1.jre8.jar
               3 File(s)      4,017,934 bytes
               0 Dir(s)  34,256,756,736 bytes free

C:\Users\me\Downloads\sqljdbc_9.2_enu\samples\connections>java -cp .:..\.. ConnectURL
java.sql.SQLException: No suitable driver found for jdbc:sqlserver://<server>:<port>;databaseName=AdventureWorks;user=<user>;password=<password>
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
        at ConnectURL.main(ConnectURL.java:32)
```

**Comment by lilgreenbird** [comment]
hi @jnahmias,

do you have `C:\Users\me\Downloads\sqljdbc_9.2_enu` in your classpath? your java application needs to be able to find the driver jar in your classpath

**Comment by jnahmias** [comment]
Hi @lilgreenbird,

I set classpath as an arg to java: `java -cp .:..\..`. When run from `C:\Users\me\Downloads\sqljdbc_9.2_enu\samples\connections\`, the `..\..` should be equivalent to `C:\Users\me\Downloads\sqljdbc_9.2_enu`.

**Comment by lilgreenbird** [comment]
hi @jnahmias,

Windows classpath separator is `;`. 
Also, you need to specify the driver jar file in the classpath, or alternatively you could use the wildcard `*` char. 
Try `java -cp .;..\..\* ConnectURL`

**Comment by jnahmias** [comment]
Thank you @lilgreenbird . I copied the `mssql-jdbc-9.2.1.jre11.jar` to the current directory and then did not get the error when running `java -cp .;mssql-jdbc-9.2.1.jre11.jar ConnectURL`.
