### ISSUE TITLE
JDBC driver doesn't support CTEs

### ISSUE THREAD

**Issue by Yasston** [microsoft/mssql-jdbc#1657]
## Driver version
Driver version : latest (9.4.0). It is actually the driver that is natively included with Synapse Spark pool

## SQL Server version
Microsoft SQL Azure (RTM) - 12.0.2000.8 

## Client Operating System
Azure Synapse Apache Spark pool (Spark v2 and v3 are impacted)

## JAVA/JVM version
the JVM natively included with Azure Synapse Apache Spark pool (Spark v2 and v3 are impacted)

## Problem description
1. Expected behaviour: queries with CTEs should execute normally and provide the same results as when they are being run from SSMS

2. Actual behaviour: Any SQL query containing one or more CTEs do not run, on Synapse Apache Spark we get the following error when trying to run a query with "WITH Cte_Name AS (SELECT Something FROM AnyTable) SELECT * FROM Cte_Name"

3. Error message/stack trace:
```
Py4JJavaError: An error occurred while calling o217.load.
: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'WITH'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:602)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7375)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3206)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:446)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:61)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRelation$.getSchema(JDBCRelation.scala:226)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:35)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:355)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:325)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:308)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:308)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

Traceback (most recent call last):

  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 210, in load
    return self._df(self._jreader.load())

  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/py4j/java_gateway.py", line 1304, in __call__
    return_value = get_return_value(

  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)

  File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(

py4j.protocol.Py4JJavaError: An error occurred while calling o217.load.
: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'WITH'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:602)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7375)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3206)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:446)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:61)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRelation$.getSchema(JDBCRelation.scala:226)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:35)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:355)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:325)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:308)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:308)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

4. Any other details that can be helpful:
The query doesn't even get run the SQL Server instance, when trying to capture the query using the Profiler, we can't see any query being executed.

A wrongfully Closed github issue was also declared here, with several commentators :
https://github.com/microsoft/mssql-jdbc/issues/1340

## Reproduction code
Try running ANY sql query with a CTE, for example the one in my previous example

**Comment by lilgreenbird** [comment]
hi @Yasston 

I looked at issue #1340 that was closed due to the the fact that the query generated by Spark contain syntax that is not valid in SQL Server.  I see that an issue was opened in Spark about that.

In this case, you mentioned you did not see a query being executed in Profiler so sounds like the driver is catching a SQL syntax error before sending to the server. Can you pls tell us what that **exact** query is and verify that the query runs using SSMS?

One thing that comes to mind, is please make sure the names containing special characters are escaped properly.

We do have tests using CTEs in our test lab that all run fine we are not aware of any issues with executing CTE queries. Could you please provide a simple java program and a schema which repro this issue here.

Thanks

**Comment by Yasston** [comment]
Hello @lilgreenbird ,
Sure I can give you an example, you can actually run ANY query with a CTE, even a dummy one as I'm going to show in my example. One thing I want to stress is that I am seeing the problem in the jdbc connector that appaearently was specifically made by MS for Spark, but since many people have commented on issue #1340 , I'm thinking the issue applies for this jdbc connector as well.

With that being said : 

Perfectly working example in SSMS :
![image](https://user-images.githubusercontent.com/33063733/134673091-4f151071-a46d-4787-be77-4f93a8c7b2d8.png)

Same query in Synapse Spark pool using the SQL Server jdbc driver (cf. issue I declared here : https://github.com/microsoft/sql-spark-connector/issues/147) : 
![image](https://user-images.githubusercontent.com/33063733/134674109-61da8032-661f-4adc-97d3-e4ded62817be.png)


Same query but without CTE, running fine in Synapse Spark pool using the SQL Server jdbc driver : 
![image](https://user-images.githubusercontent.com/33063733/134673971-23afdeae-291f-49dc-989b-c29dd4c2f5da.png)


As you can see, it's pretty easy to reproduce the issue.

Hope this helps. Thank you

**Comment by lilgreenbird** [comment]
hi @Yasston 

I ran your query in a simple java app with no problems. I'm not familiar and not sure what's happening with your application in Synapse Spark and why it's giving you errors? I would suggest that you try your queries using the driver directly in a simple standalone java app.

fyi if you look at our junit tests there are many examples of queries containing CTEs.

**Comment by KevinAppelBofa** [comment]
@Yasston, @lilgreenbird

I opened up a new Spark issue hopefully there is some help to get this feature added, otherwise you can patch the code yourself to get these to run. After doing this patches then both the jdbc, in addition to the CTE query the temp table queries also work
https://issues.apache.org/jira/browse/SPARK-37259

**Comment by WaterKnight1998** [comment]
@Yasston, @siggemannen, @supunt, @ankitbko, @ypv0rfh, @lilgreenbird

Did you find any solution to this error? I am finding the same error.

I have checked with the latests build:

```xml
<dependency>
    <groupId>com.microsoft.sqlserver</groupId>
    <artifactId>mssql-jdbc</artifactId>
    <version>10.2.0.jre8</version>
</dependency>
```

**Comment by KevinAppelBofa** [comment]
I had created an issue with the Spark and there was two people that had submitted PR with possible solution however they were not pushed to the end, i had tested them both, then it looks like they were closed for the timeout.
I have been using the custom code I did initially to work and that has been working out great for us

**Comment by WaterKnight1998** [comment]
And how can I use your solution from Databricks Cluster 9.1 using pyspark? @KevinAppelBofa

**Comment by WaterKnight1998** [comment]
I have contacted Databricks Support Teams and they have told me that they will push this PRs to get them integrated on Spark Core.
