### ISSUE TITLE
JDBC driver intermittently fails to connect to Azure MSSQL PaaS

### ISSUE THREAD

**Issue by laxgc** [microsoft/mssql-jdbc#1667]
## Driver version
mssql-jdbc-9.4.0.jre8.jar

## SQL Server version
Azure MSSQL PaaS

## Client Operating System
Suse Linux

## JAVA/JVM version
SAP JVM 8

## Table schema
NA

## Problem description

We have a client program that uses JDBC to execute SQLs. We have a customer that executes approximately 900 SQL queries per hour for about 4 hrs with about 60 concurrent sqls executing at a time. Some times the program finishes with no issues and sometimes, it fails to establish connection (shown below) for some of the SQLs we are trying to execute. The client program sits in an Azure VM as well in the same region. We suspect that it is the redirects that are causing the issue intermittently. Seemingly there is a single SQLServer instance node. 
Each of these sqls do not pull in a massive amount of data, most resultsets are around 200 rows with some reaching 100k rows.

Any help appreciated ! 

2021-09-22 08:25:15,164 [ERROR] DPFramework | WorkerThread.processRequest  - com.sap.hana.dp.adapter.sdk.AdapterException: Adapter validation failed. [DB_HIST]Failed to establish JDBC connection. Error: The TCP/IP connection to the host abf8a96418cb.tr6469.westus2-a.worker.database.windows.net (redirected from n0-qa.database.windows.net), port 11019 has failed. Error: "connect timed out (local port 9846 to address 1x.x.x.17x (xxx.com), remote port 11019 to address 1x.6x.13x.3x). Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.". Context: com.sap.hana.dp.cdcadaptercommons.validation.ValidationException: [DB_HIST]Failed to establish JDBC connection. Error: The TCP/IP connection to the host abf8a96418cb.tr6469.westus2-a.worker.database.windows.net (redirected from n0-qa.database.windows.net), port 11019 has failed. Error: "connect timed out (local port 9846 to address 1x.x.x.17x (xxx.com), remote port 11019 to address 1x.6x.13x.3x). Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
                                at com.sap.hana.dp.cdcadaptercommons.validation.AbstractDBAccessValidator.validate(AbstractDBAccessValidator.java:46)
                                at com.sap.hana.dp.cdcadaptercommons.validation.AdapterPropertiesValidator.validate(AdapterPropertiesValidator.java:126)
                                at com.sap.hana.dp.cdcadaptercommons.validation.AdapterPropertiesValidator.validate(AdapterPropertiesValidator.java:66)
                                at com.sap.hana.dp.cdcadaptercommons.validation.AdapterPropertiesValidator.validate(AdapterPropertiesValidator.java:153)
  ...
                                Adapter validation failed. [DB_HIST]Failed to establish JDBC connection. Error: The TCP/IP connection to the host abf8a96418cb.tr6469.westus2-a.worker.database.windows.net (redirected from n0-qa.database.windows.net), port 11019 has failed. Error: "connect timed out (local port 9846 to address 1x.x.x.17x (xxx.com, remote port 11019 to address 1x.6x.13x.3x). Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
                                	at com.sap.hana.dp.adapter.sdk.util.ExceptionUtil.newAdapterException(ExceptionUtil.java:166)
                                	at com.sap.hana.dp.mssqllogreaderadapter.MssqlLogReaderAdapter.sdaOpen(MssqlLogReaderAdapter.java:579)
                                	at com.sap.hana.dp.cdcadaptercommons.StatefulAdapterCDC$NotOpened.open(StatefulAdapterCDC.java:802)
                                	at com.sap.hana.dp.cdcadaptercommons.StatefulAdapterCDC.open(StatefulAdapterCDC.java:285)
                                	at com.sap.hana.dp.cdcadaptercommons.logreader.ReusableClassloaderAdapterCDC.open(ReusableClassloaderAdapterCDC.java:79)
                                	at com.sap.hana.dp.mssqllogreaderadapter.MssqlAdapterCDCLoader.open(MssqlAdapterCDCLoader.java:40)
                                	at com.sap.hana.dp.adapter.sdk.decorator.AdapterCDCDelegate.open(AdapterCDCDelegate.java:263)
                                	at com.sap.hana.dp.adapter.framework.core.WorkerThread.processAdapterOpen(WorkerThread.java:1823)
                                	at com.sap.hana.dp.adapter.framework.core.WorkerThread.processRequest(WorkerThread.java:261)
                                	at com.sap.hana.dp.adapter.framework.core.WorkerThread.run(WorkerThread.java:2054)
                                	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                                	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                	at java.lang.Thread.run(Thread.java:836)
                                Caused by: com.sap.hana.dp.cdcadaptercommons.validation.ValidationException: [DB_HIST]Failed to establish JDBC connection. Error: The TCP/IP connection to the host abf8a96418cb.tr6469.westus2-a.worker.database.windows.net (redirected from n0-qa.database.windows.net), port 11019 has failed. Error: "connect timed out (local port 9846 to address 1x.x.x.17x (xxx.com, remote port 11019 to address 1x.6x.13x.3x). Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
                                	at com.sap.hana.dp.cdcadaptercommons.validation.AbstractDBAccessValidator.validate(AbstractDBAccessValidator.java:46)
                                	at com.sap.hana.dp.cdcadaptercommons.validation.AdapterPropertiesValidator.validate(AdapterPropertiesValidator.java:126)
                                	at com.sap.hana.dp.cdcadaptercommons.validation.AdapterPropertiesValidator.validate(AdapterPropertiesValidator.java:66)
                                	at com.sap.hana.dp.cdcadaptercommons.validation.AdapterPropertiesValidator.validate(AdapterPropertiesValidator.java:153)
                                	at com.sap.hana.dp.mssqllogreaderadapter.MssqlLogReaderAdapter.sdaOpen(MssqlLogReaderAdapter.java:559)
                                	... 11 more

1. Expected behaviour:
Stable connections
2. Actual behaviour:
Intermittent connection failure
3. Error message/stack trace:
                                Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host abf8a96418cb.tr6469.westus2-a.worker.database.windows.net (redirected from n0-qa.database.windows.net), port 11019 has failed. Error: "connect timed out (local port 9846 to address 1x.x.x.17x (xxx.com, remote port 11019 to address 1x.6x.13x.3x). Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
                                	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237)
                                	at com.microsoft.sqlserver.jdbc.SQLServerException.ConvertConnectExceptionToSQLServerException(SQLServerException.java:288)
                                	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2466)
                                	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:676)
                                	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2957)
                                	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2628)
                                	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2471)
                                	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1470)
                                	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:915)
                                	at java.sql.DriverManager.getConnection(DriverManager.java:664)
                                	at java.sql.DriverManager.getConnection(DriverManager.java:208)
                                	at com.sap.hana.dp.mssqllogreaderadapter.MssqlConnectionFactory.getConnection(MssqlConnectionFactory.java:136)
                                	at com.sap.hana.dp.mssqllogreaderadapter.MssqlConnectionFactory.newConnection(MssqlConnectionFactory.java:121)

4. Any other details that can be helpful:

## JDBC trace logs

Since the failure is very intermittent, it is difficult to capture. but we have now enabled the jdbc traces with "FINE" level of logging. Will attach as soon as JDBC trace logs are available

**Comment by lilgreenbird** [comment]
closing due to inactivity, please free free to request re-opening if you have more info
