### ISSUE TITLE
Flood of threads related finding connection

### ISSUE THREAD

**Issue by derekhackbardt** [microsoft/mssql-jdbc#1668]
## Driver version
9.4.0

## SQL Server version
Microsoft SQL Server 2019 (RTM-CU12) (KB5004524) - 15.0.4153.1 (X64)   Jul 19 2021 15:37:34   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) 

Availability group cluster with 3 nodes.  2 on one subnet and 1 on another.  listener has 2 IPs assigned.  Non-microsoft dns in use, so dns has both IPs always listed.

## Client Operating System
Windows 10

## JAVA/JVM version
java version "11.0.11" 2021-04-20 LTS

## Problem description
At random times, the driver will spawn tens of thousands of threads attempting to get a connection to an availability group when connection string has transparentNetworkIPResolution=true or multiSubnet=true.   Availability group has 3 nodes with 2 different IP addresses on different subnets.  The issue is not consistent with every connection attempt.

Removing transparentNetworkIPResolution=true and multisubnet=true from the connection url seems to eliminate this issue, but then connections aren't made when in a timely manner when dns reports one of the non-active addresses.

Stack trace:  all threads in the thread dump appear similar to this:
"pool-2-thread-33375" - Thread t@38313
   java.lang.Thread.State: RUNNABLE
        at java.base@11.0.11/java.util.concurrent.locks.AbstractQueuedSynchronizer.addWaiter(AbstractQueuedSynchronizer.java:651)
        at java.base@11.0.11/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
        at java.base@11.0.11/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
        at java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:986)
        at java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base@11.0.11/java.lang.Thread.run(Thread.java:834)

4. Any other details that can be helpful:
The issue happens inconsistently but semi-frequently when attempting to get a connection.

**Comment by lilgreenbird** [comment]
closing due to inactivity, please feel free to request re-opening if you have more info
