### ISSUE TITLE
The server failed to resume the transaction

### ISSUE THREAD

**Issue by JDBC-0** [microsoft/mssql-jdbc#1704]
## Driver version
9.4.0

## SQL Server version
2019

## Client Operating System
Windows 10

## JAVA/JVM version
OpenJDK 11

## Problem description
We try to exchange our current JDBC driver (jTDS) with this driver (since version 7.x) but even with teh latest 9.4.0, we get random SQL Exceptions

`
104329622 SEVERE  T188: Error executing SQL ijs_JobProcFinished 'AMC', '2112061043-54ED8BAB-5078-4E1B-88A8-7C58351C0FB3', null, null, null, 59 . errorCode=3971, message=Der Server konnte die Transaktion nicht fortsetzen. Beschreibung:7600000003., SQLState=S0001, cause=null
    com.microsoft.sqlserver.jdbc.SQLServerException: Der Server konnte die Transaktion nicht fortsetzen. Beschreibung:7600000003.
    	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
    	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1662)
    	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:615)
    	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:537)
    	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7417)
    	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3488)
    	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:262)
    	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:237)
    	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:483)
`

We have no idea why this occurs with the driver (occasionaly). We found https://docs.microsoft.com/de-de/archive/blogs/jdbcteam/the-server-failed-to-resume-the-transaction-why and tried to understand and act to it, but even thogh we ensured that our transactions are valid, this error still occurs (occasionally). Switching back to the old driver (jTDS) this exception never occurs.

## Reproduction code
Unfortunately, this is random.

**Comment by v-zhangw** [comment]
Hello @JDBC-0,

It is difficult to help with so little information. Can you not extract this behavior into a stand alone java app?

**Comment by JDBC-0** [comment]
The problem is, that the exception occurs totally random. I startet testing the mssql-jdbc driver a year ago since 7.x versions and the same error occured there. Re-checkd with misc 8.x versions - same error. Now with 9.x versions - same error. I played with the stored procedures that were involved, changed transaction isolation levels, etc. but the driver does not hold an hour without this transaction where I have no idea anymore what else to try fix this.

**Comment by v-zhangw** [comment]
We do not know of any such limitation with the Microsoft JDBC Driver.

We are not able to really assist without knowing more about what is causing this issue.
Does this happen with any explicit transaction? If you try a very simple one many many times, does it still happen?

**Comment by JDBC-0** [comment]
Unfortunately, this is a bigger application with dozens of prozedures and it occured randomly. However, there error has not occured anymore since I removed/resolved/reimplemented the old stored procedures that used explicit transactions. So, the error seems to be caused by those explicit transactions in the called stored procedures. 

The jTDS driver does not have this problem (for years), so it seems to be an issue of the driver. 

As I worked around this by removing explicit transactions, I close this isse.

**Comment by woj-tek** [comment]
I just hit exactly same issue and it's reproducible. We switched from jTDS driver to original driver from MS due to JDK17 compatibility.

We have two stored procedures [`TigPubSubCreateNode`](https://github.com/tigase/tigase-pubsub/blob/a099e0a41b6b85ad597fd46d8ef3ea3e309d3c5c/src/main/database/sqlserver-pubsub-5.0.0.sql#L95-L95) and [`TigPubSubEnsureServiceJid`](https://github.com/tigase/tigase-pubsub/blob/a099e0a41b6b85ad597fd46d8ef3ea3e309d3c5c/src/main/database/sqlserver-pubsub-5.0.0.sql#L61) that both use explicit transactions. Calling them yields same exception:
```
[2022-12-15 15:14:26:205] [WARNING ] [           in_1-pubsub ] CachedPubSubRepository.saveNode(): Problem saving pubsub data:
tigase.component.exceptions.RepositoryException: Node subscribers writing error
        at tigase.pubsub.repository.PubSubDAOJDBC.updateNodeAffiliation(PubSubDAOJDBC.java:1097)
        at tigase.pubsub.repository.PubSubDAOJDBC.updateNodeAffiliation(PubSubDAOJDBC.java:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at tigase.stats.StatisticsInvocationHandler.invoke(StatisticsInvocationHandler.java:75)
        at jdk.proxy2/jdk.proxy2.$Proxy39.updateNodeAffiliation(Unknown Source)
        at tigase.pubsub.repository.PubSubDAOPool.updateNodeAffiliation(PubSubDAOPool.java:468)
        at tigase.pubsub.repository.cached.CachedPubSubRepository.saveNode(CachedPubSubRepository.java:872)
        at tigase.pubsub.repository.cached.CachedPubSubRepository.update(CachedPubSubRepository.java:598)
        at tigase.pubsub.modules.SubscribeNodeModule.process(SubscribeNodeModule.java:173)
        at tigase.component.modules.StanzaProcessor.execute(StanzaProcessor.java:219)
        at tigase.component.modules.StanzaProcessor.process(StanzaProcessor.java:206)
        at tigase.component.modules.StanzaProcessor.processPacket(StanzaProcessor.java:103)
        at tigase.component.AbstractKernelBasedComponent.processPacket(AbstractKernelBasedComponent.java:81)
        at tigase.pubsub.PubSubComponent.processPacket(PubSubComponent.java:191)
        at tigase.server.AbstractMessageReceiver$QueueListener.run(AbstractMessageReceiver.java:1398)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The server failed to resume the transaction. Desc:3500000021.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1676)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:615)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:537)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7730)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3786)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:515)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at tigase.db.jdbc.PreparedStatementInvocationHandler.invoke(PreparedStatementInvocationHandler.java:38)
        at jdk.proxy2/jdk.proxy2.$Proxy35.execute(Unknown Source)
        at tigase.pubsub.repository.PubSubDAOJDBC.updateNodeAffiliation(PubSubDAOJDBC.java:1089)
        ... 17 more
```

Currently testing with `10.2.1.jre17` and it was working fine with jtds:1.3.1

Removing explicit transactions works but in our case it could lead to data inconsistencies in some situations thus it would be best to be able to stick with transactions.

**Comment by Jeffery-Wasty** [comment]
Hi @woj-tek,

As this issue is now closed, please open a new issue with the above details included. This will help us in addressing the issue quickly and efficiently.

**Comment by woj-tek** [comment]
@Jeffery-Wasty Hi, I assumed that because the issue seems quite the same, instead of opening new one re-open this one, given that it wasn't resolved per se but the user simply removed the transactions. At any rate, I created https://github.com/microsoft/mssql-jdbc/issues/2008

**Comment by Jeffery-Wasty** [comment]
That's a fair assumption to make, but comments on closed issues are sometimes missed, and re-opening, and re-assigned formerly completed tasks can be a bit of hassle. For JDBC, who have <100 open issues on GitHub, this is the preferred way.
