### ISSUE TITLE
[FEATURE REQUEST] use also filesystem on large LOBs if delayLoadingLob=false (like jTDS driver)

### ISSUE THREAD

**Issue by AlBundy33** [microsoft/mssql-jdbc#1801]
Currently I'm trying to migrate from jTDS to mssql-jdbc
This seems to work really good but I get a lot of R_streamIsClosed-exceptions (some only logged in FINE or FINEST) from com.microsoft.sqlserver.jdbc.BaseInputStream.checkClosed()
```
Caused by: java.io.IOException: Der Datenstrom wurde geschlossen.
	at com.microsoft.sqlserver.jdbc.BaseInputStream.checkClosed(SimpleInputStream.java:95)
	at com.microsoft.sqlserver.jdbc.SimpleInputStream.read(SimpleInputStream.java:281)
	at com.c4u.eis.core.database.DatabaseStream.read(DatabaseStream.java:163)
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:385)
```

According to this thread
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/f4f14c4f-7634-4355-99d1-f5402abbca96/getting-javaioioexception-the-stream-is-closed-when-retrieving-image-field-from-db-with-jdbc-type?forum=sqldataaccess
this is by intention because with mssql-jdbc we have to read the stream directly after calling the column-getter.

This is currently an issue for us because we have our own framework wrapped around the resultset that reads the column first and the caller decides what to do with it.
Some parts of our application are also reading the the stream after the coresponding resultset is closed (mssql-jdbc closes the stream together with the resultset).

setting delayLoadingLob=false seems to be a workaround for this issue but loading all LOBs into memory may cause an out of memory sooner or later.

so it would be nice to if we could configure a buffer together with delayLoadingLob where all LOBs <= buffer will be stored in memory and all LOBs larger than buffer will be stored as temp-file in the filesystem (can be deleted when the stream is closed).

I think this in done in net.sourceforge.jtds.util.BlobBuffer in jTDS-driver.

**Comment by lilgreenbird** [comment]
hi @AlBundy33 

I have added this feature request into our backlog it will be triaged along with other bug fixes and feature requests when we do planning for future releases.
