### ISSUE TITLE
Failed to load MSAL4J Java library for performing ActiveDirectoryPassword authentication.

### ISSUE THREAD

**Issue by anupamkakade** [microsoft/mssql-jdbc#1832]
## Driver version
10.2.0.jre8

## SQL Server version
Microsoft Azure SQL Data Warehouse - 10.0.13727.0 May 7 2022 09:10:00 Copyright (c) Microsoft Corporation

## Client Operating System
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"

## JAVA/JVM version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)

## Problem description
Authentication type with `ActiveDirectoryPassword` is not working with `10.2.0.jre8` but is working with `7.3.0.jre8-preview`
## Expected behavior
Authentication type with `ActiveDirectoryPassword` should work with `10.2.0.jre8`
## Actual behavior
Output of what you actually see.
## Error message/stack trace
2022-05-16 15:10:05,894 ERROR [main] c.z.h.p.HikariPool:593 - Mssql-master - Exception during pool initialization.
com.microsoft.sqlserver.jdbc.SQLServerException: Failed to load MSAL4J Java library for performing ActiveDirectoryPassword authentication.
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.getFedAuthToken(SQLServerConnection.java:5318)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:5293)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:5180)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:305)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:128)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6162)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4785)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$100(SQLServerConnection.java:90)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4723)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7785)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3793)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3233)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)

## JDBC trace logs
Provide the JDBC driver trace logs.  Instructions can be found here: https://docs.microsoft.com/sql/connect/jdbc/tracing-driver-operation

**Comment by anupamkakade** [comment]
Adding a MSAL4J library helped to resolve the issue. We can close the issue

**Comment by Pundarikaksha-Nimmala** [comment]
@anupamkakade which version of MSAL4j library need to be added. I have added msal4j-1.11.3.jar and getting the below error.

 Could not initialize class com.microsoft.aad.msal4j.JsonHelper

**Comment by Jeffery-Wasty** [comment]
Hi @Pundarikaksha-Nimmala,

That is the correct version to use. This problem seems to be different to the one the original poster was asking about, can you create a new issue so that we can look into this?
