### ISSUE TITLE
Getting Kerberos working from inside of a Kubernetes Pod

### ISSUE THREAD

**Issue by mlbiam** [microsoft/mssql-jdbc#1921]
## Question
I'm trying to get the JDBC driver working from inside of a Kubernetes `Pod`.  There's a sidecar that runs kinit to get a ticket cache and the cache is populated:

```
 k exec -ti  openunison-operator-6b765b747f-tfjwr -c openunison-operator -n openunison -- klist
Ticket cache: FILE:/dev/shm/ccache
Default principal: unison-sql-server@ENT2K19.DOMAIN.COM

Valid starting     Expires            Service principal
09/21/22 22:53:20  09/22/22 08:53:20  krbtgt/ENT2K19.DOMAIN.COM@ENT2K19.DOMAIN.COM
        renew until 09/22/22 22:53:20
```

But I'm getting the following exception:

```
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Kerberos Login failed: Integrated authentication failed. ClientConnectionId:76e2dc74-222a-4682-8947-d1a864249436 due to javax.security.auth.login.LoginException (Cannot get any of properties: [user, USER] from con properties not available to garner  authentication information  from the user)
        at com.microsoft.sqlserver.jdbc.KerbAuthentication.intAuthInit(KerbAuthentication.java:100)
        at com.microsoft.sqlserver.jdbc.KerbAuthentication.generateClientContext(KerbAuthentication.java:207)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6026)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4907)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4845)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7627)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3912)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3358)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2950)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2790)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1663)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1064)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
        at com.tremolosecurity.kubernetes.artifacts.util.DbUtils.runSQL(DbUtils.java:54)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$144$1699$\^eval\_$cu1$restOf.proc_sql(<eval>:72)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$140$23A$\^eval\_$cu1$restOf.on_watch(<eval>:31)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:657)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
        ... 7 more
Caused by: javax.security.auth.login.LoginException: Cannot get any of properties: [user, USER] from con properties not available to garner  authentication information  from the user
        at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.promptForName(Krb5LoginModule.java:848)
        at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:684)
        at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:592)
        at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:747)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:672)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:670)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:670)
        at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:581)
        at com.microsoft.sqlserver.jdbc.KerbAuthentication.intAuthInit(KerbAuthentication.java:77)
        ... 26 more
```

The **java** command:

```
        - java
        - -Djava.security.krb5.conf=/etc/krb5-local/krb5.conf
        - -Djava.security.krb5.debug=true
        - -Djava.security.auth.login.config=/etc/krb5-local/SQLJDBCDriver.conf
        .
        .
        .
```

My **/etc/krb5-local/krb5.conf**:

```
[libdefaults]
        default_realm = ENT2K19.DOMAIN.COM
        kdc_timesync = 1
        default_ccache_name = /dev/shm/ccache
        ccache_type = 4
        forwardable = true
        proxiable = true

# The following encryption type specification will be used by MIT Kerberos
# if uncommented.  In general, the defaults in the MIT Kerberos code are
# correct and overriding these specifications only serves to disable new
# encryption types as they are added, creating interoperability problems.
#
# The only time when you might need to uncomment these lines and change
# the enctypes is if you have local software that will break on ticket
# caches containing ticket encryption types it doesn't know about (such as
# old versions of Sun Java).

#       default_tgs_enctypes = des3-hmac-sha1
#       default_tkt_enctypes = des3-hmac-sha1
#       permitted_enctypes = des3-hmac-sha1

# The following libdefaults parameters are only for Heimdal Kerberos.
        fcc-mit-ticketflags = true

[realms]
        ENT2K19.DOMAIN.COM = {
                kdc = adfs.ent2k19.domain.com
                admin_server = adfs.ent2k19.domain.com
        }

[domain_realm]
       ent2k19.domain.com = ENT2K19.DOMAIN.COM
       .ent2k19.domain.com = ENT2K19.DOMAIN.COM
```

My **SQLJDBCDriver.conf**:

```
SQLJDBCDriver {  
  com.sun.security.auth.module.Krb5LoginModule required useTicketCache=true;  
};
```

My URL: `jdbc:sqlserver://adfs.ent2k19.domain.com:1433;databaseName=somedb;trustServerCertificate=true;integratedSecurity=true;authenticationScheme=JavaKerberos`

Software versions:
OS - ubuntu 20.04.5
Java version - OpenJDK 11
mssql jdbc driver version:  11.2.0.jre11

I'm not seeing any kerberos debugging data.  it's as if there's no kerberos going on.  Am I missing something?  Any help would be greatly appreciated.

**Comment by tkyc** [comment]
Strange, the error in the stack trace occurs when a ticket hasn't been created. I'm guessing maybe it can't find the ticket (although I see that you specified the ticket cache in your krb5.conf). Could you try explicitly setting the `KRB5CCNAME` environment variable with the path to your ticket (this should take precedence over the krb5.conf)? Also, could share the `errorlog` file of sql server? The logs should be found at `/var/opt/mssql/log/errorlog`.

**Comment by tkyc** [comment]
Is there any update on this? Otherwise, I'll be closing this soon.

**Comment by mlbiam** [comment]
@tkyc sorry, I got sidetracked.  I needed to do two things:

1. As suggested - set `KRB5CCNAME` explicitly
2. Turned out there was an issue with my testing domain controller that had nothing to do with the driver.  Once I deployed a new one everything worked.

Wanted to close the loop in case others ran into the same issue.  Thanks again!
