### ISSUE TITLE
socket read timeout during connection creation when a user-assigned managed identity is used

### ISSUE THREAD

**Issue by vloo** [microsoft/mssql-jdbc#1979]
## Driver version
mssql-jdbc-11.2.0.jre11.jar

## SQL Server version
Microsoft SQL Azure (RTM) - 12.0.2000.8
Oct 18 2022 13:24:45
Copyright (C) 2022 Microsoft Corporation

## Client Operating System
Microsoft Windows Server 
Version 1607 (OS Build 14393.54)

## JAVA/JVM version
java -version
openjdk version "11.0.13" 2021-10-19 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.13+8-LTS, mixed mode)

## Problem description
Socket read timeout during connection creation when a user-assigned managed identity is used. It doesn't happen often, but once every few thousand attempts over time. It happened to us several times in a production environment.

connection string:
jdbc:sqlserver://xxxxxxxxxx.database.windows.net:1433;databaseName=mydb;msiClientId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx;Authentication=ActiveDirectoryMsi;socketTimeout=600

## Expected behavior
Establishing a new connection should not wait for a socket timeout. Login timeout should be respected. A stuck connection establishment should not block other operations in the connection pool.

## Actual behavior
This will cause all connections in the DB pool to be exhausted.

## Error message/stack trace
```
2022-11-29T07:58:38,774+00:00 DEBUG [log_db connection adder] com.zaxxer.hikari.pool.PoolBase: log_db - Failed to create/setup connection: Read timed out ClientConnectionId:a210d126-4929-4ac8-b92b-1411c7818ca6
2022-11-29T07:58:38,774+00:00 DEBUG [log_db connection adder] com.zaxxer.hikari.pool.HikariPool: log_db - Cannot acquire connection from data source
com.microsoft.sqlserver.jdbc.SQLServerException: Read timed out ClientConnectionId:a210d126-4929-4ac8-b92b-1411c7818ca6
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3806) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2107) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6795) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:8017) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7980) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendFedAuthToken(SQLServerConnection.java:5612) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$FedAuthTokenCommand.doExecute(SQLServerConnection.java:5394) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7627) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:5422) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:5302) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:306) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:126) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6295) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4907) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4845) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7627) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3912) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3358) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2950) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2790) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1663) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1064) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar!/:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar!/:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar!/:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar!/:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:733) ~[HikariCP-5.0.1.jar!/:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[HikariCP-5.0.1.jar!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:115) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:168) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1207) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:1194) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1207) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:1194) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1374) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:985) ~[?:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1207) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:1194) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2100) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	... 31 more
```

## Any other details that can be helpful
Without setting the socket timeout, it takes forever to create a connection. 
It also happened on an older version of the driver - 9.4.0

thread dump:
```
log_db connection adder" #3512664 daemon prio=5 os_prio=0 cpu=0.00ms elapsed=24061.58s tid=0x000001ee4cc6f800 nid=0x2128 runnable  [0x000001ee0c5fe000]
   java.lang.Thread.State: RUNNABLE
    at java.net.SocketInputStream.socketRead0(java.base@11.0.13/Native Method)
    at java.net.SocketInputStream.socketRead(java.base@11.0.13/SocketInputStream.java:115)
    at java.net.SocketInputStream.read(java.base@11.0.13/SocketInputStream.java:168)
    at java.net.SocketInputStream.read(java.base@11.0.13/SocketInputStream.java:140)
    at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1023)
    at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:1013)
    at sun.security.ssl.SSLSocketInputRecord.read(java.base@11.0.13/SSLSocketInputRecord.java:478)
    at sun.security.ssl.SSLSocketInputRecord.readHeader(java.base@11.0.13/SSLSocketInputRecord.java:472)
    at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(java.base@11.0.13/SSLSocketInputRecord.java:70)
    at sun.security.ssl.SSLSocketImpl.readApplicationRecord(java.base@11.0.13/SSLSocketImpl.java:1374)
    at sun.security.ssl.SSLSocketImpl$AppInputStream.read(java.base@11.0.13/SSLSocketImpl.java:985)
    at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2058)
    at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6616)
    - locked <0x0000000740700440> (a com.microsoft.sqlserver.jdbc.TDSReader)
    at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7804)
    at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7767)
    at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendFedAuthToken(SQLServerConnection.java:4906)
    at com.microsoft.sqlserver.jdbc.SQLServerConnection$FedAuthTokenCommand.doExecute(SQLServerConnection.java:4703)
    at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7417)
    at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:4731)
    at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:4680)
    at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:289)
    at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:125)
    at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
    at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:5560)
    at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4289)
    at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4227)
    at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7417)
    at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3488)
    - locked <0x0000000740700750> (a java.lang.Object)
    at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2978)
    at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2628)
    at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2471)
    at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1470)
    at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:915)
    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
    at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
    at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
    at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
    at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:733)
    at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
    at java.util.concurrent.FutureTask.run(java.base@11.0.13/FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.13/ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.13/ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(java.base@11.0.13/Thread.java:829)
```

**Comment by lilgreenbird** [comment]
hi @vloo 

I noticed you are using Hikari pools. Intermittent connection issues are usually caused by pool config settings are you able to reproduce this without using pooling? While our driver is known to work with Hikari pools we do not support them directly I would suggest that you look at their documentation to fine tune your configuration or ask for help in their [repo ](https://github.com/brettwooldridge/HikariCP)seems to be actively maintained.

**Comment by vloo** [comment]
Yes, we are using HikariCP.  We are not able to reproduce it on purpose. Yes, the driver works fine in most cases fine. This situation occurred several times and caused the database outage in our production environment. 

`socketTimeout` on the JDBC driver level is set to 600 = 10 minutes - this is the absolute minimum for our application

Our HikariCP configuration is the default, except `validationTimeout` which is 10 seconds, `connectionTimeout` is 60 seconds `maximumPoolSize` is 30, and `minimumIdle` is 5.

`maxLifetime` is default 30 minutes - every 30 minutes connection is closed and then a new one is created.
https://github.com/brettwooldridge/HikariCP#gear-configuration-knobs-baby

In HikariCP for creating new connections, there is a queue and single-threaded executor. 
```
      LinkedBlockingQueue<Runnable> addConnectionQueue = new LinkedBlockingQueue<>(16);
      this.addConnectionExecutor = createThreadPoolExecutor(addConnectionQueue, poolName + " connection adder", threadFactory, new CustomDiscardPolicy());
      this.closeConnectionExecutor = createThreadPoolExecutor(maxPoolSize, poolName + " connection closer", threadFactory, new ThreadPoolExecutor.CallerRunsPolicy());
...

   public static ThreadPoolExecutor createThreadPoolExecutor(final BlockingQueue<Runnable> queue, final String threadName, ThreadFactory threadFactory, final RejectedExecutionHandler policy)
...
      return new ThreadPoolExecutor(1 /*core*/, 1 /*max*/, 5 /*keepalive*/, SECONDS, queue, threadFactory, policy);
...
   }
```

When creating a new connection gets stuck, there is no way how to create another new connection. After socket timeout expires, connections are recreated and everything works fine since. The socket timeout is taken from JDBC URL.  When no socket timeout is specified, creating new connections will get stuck indefinitely and an application restart is required. 

The socket timeout is infinite by default in driver: https://learn.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver16 `socketTimeout` `The default value is 0, which means infinite timeout.`

HikariCP log
closing old connections
```
2022-11-29T07:48:38,697+00:00 DEBUG [log_db connection closer] com.zaxxer.hikari.pool.PoolBase: log_db - Closing connection ConnectionID:990 ClientConnectionId: f9ad8b33-757e-4d0c-8a63-20d4b82a0cf0: (connection has passed maxLifetime)
2022-11-29T07:48:48,094+00:00 DEBUG [log_db housekeeper] com.zaxxer.hikari.pool.HikariPool: log_db - Before cleanup stats (total=4, active=0, idle=4, waiting=0)
2022-11-29T07:48:48,094+00:00 DEBUG [log_db housekeeper] com.zaxxer.hikari.pool.HikariPool: log_db - After cleanup  stats (total=4, active=0, idle=4, waiting=0)
2022-11-29T07:48:53,800+00:00 DEBUG [log_db housekeeper] com.zaxxer.hikari.pool.HikariPool: log_db - Add connection elided, waiting=0, adders pending/running=3
2022-11-29T07:48:53,800+00:00 DEBUG [log_db connection closer] com.zaxxer.hikari.pool.PoolBase: log_db - Closing connection ConnectionID:992 ClientConnectionId: 57efbeb7-99af-4c6b-8376-dabe295d8738: (connection has passed maxLifetime)
2022-11-29T07:49:07,354+00:00 DEBUG [log_db housekeeper] com.zaxxer.hikari.pool.HikariPool: log_db - Add connection elided, waiting=0, adders pending/running=4
2022-11-29T07:49:07,354+00:00 DEBUG [log_db connection closer] com.zaxxer.hikari.pool.PoolBase: log_db - Closing connection ConnectionID:995 ClientConnectionId: 88a430e7-da93-4efe-a308-7d8dcf457508: (connection has passed maxLifetime)
2022-11-29T07:49:18,104+00:00 DEBUG [log_db housekeeper] com.zaxxer.hikari.pool.HikariPool: log_db - Before cleanup stats (total=2, active=0, idle=2, waiting=0)
2022-11-29T07:49:18,104+00:00 DEBUG [log_db housekeeper] com.zaxxer.hikari.pool.HikariPool: log_db - After cleanup  stats (total=2, active=0, idle=2, waiting=0)
2022-11-29T07:49:47,031+00:00 DEBUG [log_db housekeeper] com.zaxxer.hikari.pool.HikariPool: log_db - Add connection elided, waiting=0, adders pending/running=6
2022-11-29T07:49:47,031+00:00 DEBUG [log_db connection closer] com.zaxxer.hikari.pool.PoolBase: log_db - Closing connection ConnectionID:1000 ClientConnectionId: b735534b-db4e-4cfb-a7aa-a380f9c12bc2: (connection has passed maxLifetime)
2022-11-29T07:49:48,109+00:00 DEBUG [log_db housekeeper] com.zaxxer.hikari.pool.HikariPool: log_db - Before cleanup stats (total=1, active=0, idle=1, waiting=0)
2022-11-29T07:49:48,109+00:00 DEBUG [log_db housekeeper] com.zaxxer.hikari.pool.HikariPool: log_db - After cleanup  stats (total=1, active=0, idle=1, waiting=0)
2022-11-29T07:49:52,502+00:00 DEBUG [log_db housekeeper] com.zaxxer.hikari.pool.HikariPool: log_db - Add connection elided, waiting=0, adders pending/running=8
2022-11-29T07:49:52,502+00:00 DEBUG [log_db connection closer] com.zaxxer.hikari.pool.PoolBase: log_db - Closing connection ConnectionID:1002 ClientConnectionId: e6e54962-440b-4931-a21a-c71045553f18: (connection has passed maxLifetime)
2022-11-29T07:50:00,313+00:00 DEBUG [app-4_Worker-1] com.zaxxer.hikari.pool.HikariPool: log_db - Add connection elided, waiting=1, adders pending/running=9
2022-11-29T07:50:08,687+00:00 DEBUG [app-thread-135] com.zaxxer.hikari.pool.HikariPool: log_db - Add connection elided, waiting=2, adders pending/running=9
2022-11-29T07:50:17,866+00:00 DEBUG [app-thread-137] com.zaxxer.hikari.pool.HikariPool: log_db - Add connection elided, waiting=3, adders pending/running=9
2022-11-29T07:50:18,117+00:00 DEBUG [log_db housekeeper] com.zaxxer.hikari.pool.HikariPool: log_db - Before cleanup stats (total=0, active=0, idle=0, waiting=3)
```

then socket timeout:
```
2022-11-29T07:58:38,774+00:00 DEBUG [log_db connection adder] com.zaxxer.hikari.pool.PoolBase: log_db - Failed to create/setup connection: Read timed out ClientConnectionId:a210d126-4929-4ac8-b92b-1411c7818ca6
2022-11-29T07:58:38,774+00:00 DEBUG [log_db connection adder] com.zaxxer.hikari.pool.HikariPool: log_db - Cannot acquire connection from data source
com.microsoft.sqlserver.jdbc.SQLServerException: Read timed out ClientConnectionId:a210d126-4929-4ac8-b92b-1411c7818ca6
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3806) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2107) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6795) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:8017) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7980) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendFedAuthToken(SQLServerConnection.java:5612) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$FedAuthTokenCommand.doExecute(SQLServerConnection.java:5394) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7627) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:5422) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:5302) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:306) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:126) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6295) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4907) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4845) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7627) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3912) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3358) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2950) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2790) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1663) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1064) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-5.0.1.jar!/:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar!/:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar!/:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar!/:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:733) ~[HikariCP-5.0.1.jar!/:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[HikariCP-5.0.1.jar!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:115) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:168) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1207) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:1194) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1207) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:1194) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1374) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:985) ~[?:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1207) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:1194) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2100) ~[mssql-jdbc-11.2.0.jre11.jar!/:?]
	... 31 more
```

connections are created and everything starts working again after 10 minutes
```
2022-11-29T07:58:38,883+00:00 DEBUG [log_db connection adder] com.zaxxer.hikari.pool.HikariPool: log_db - Added connection ConnectionID:1049 ClientConnectionId: 57281756-97f2-4f6d-baf0-519445bca71c
2022-11-29T07:58:38,962+00:00 DEBUG [log_db connection adder] com.zaxxer.hikari.pool.HikariPool: log_db - Added connection ConnectionID:1050 ClientConnectionId: 6e698306-359f-46eb-ab24-dca3002e501b
2022-11-29T07:58:39,040+00:00 DEBUG [log_db connection adder] com.zaxxer.hikari.pool.HikariPool: log_db - Added connection ConnectionID:1051 ClientConnectionId: ec8e4628-ff88-4212-ace0-90c66b9405c0
```




Is it the responsibility of the pool or the driver that it takes a long time to create a new connection? If the socket timeout is set incorrectly, does it end up stuck?

**Comment by David-Engel** [comment]
SocketTimeout is milliseconds. 600ms is excessively low. Considering when socketTimeout comes into play, 30000 - 60000 (30 seconds to 1 minute) would be more reasonable.

**Comment by lilgreenbird** [comment]
hi @vloo 

Please see David's comment above re socketTimeout value. 

These types of intermittent issues are always difficult to troubleshoot it's best to limit the number of moving parts to identify the root cause. From past experience these types of issues are always environment/configuration related if the driver is able to estimate a connection most of the time then the problem does not lie within the driver. Do you still experience this issue if you do not use Hikari? I have seen similar issues in the past like this from users using Hikari it seems to be related to the pool settings. If you look on their repo there are quite a lot of issues relating to dead connections and their suggestion is to increase _maxlifetime_ and/or check _isConnectionAlive_. I've heard users have had luck with this in the past. There are many settings for Hikari as I mentioned before we don't support them directly so if you need help with that I would encourage you to file an issue with them their [repo ](https://github.com/brettwooldridge/HikariCP)seems to be actively maintained.

If you still experience the issue without Hikari, we do have a [wiki ](https://github.com/microsoft/mssql-jdbc/wiki/Troubleshooting-Intermittent-Connection-Failures)that contains some resources that might help you with troubleshooting. And if you provide us with a log we might be able to identify where the problem is.

**Comment by tkyc** [comment]
Could you attach relevant logs? Troubleshooting these intermittent connection issues is difficult without more information. I'd also recommend reaching out to Azure support as to me this seems more like a problem they'd be able to help with.

**Comment by vloo** [comment]
What logs would help you? It will probably not be easy to set the logger correctly. The problem occurs once in a long time - let's say a week, that could be a really large amount of logs.

**Comment by tkyc** [comment]
My mistake for not being specific. I meant driver logs and pooling logs (logs around/about the time when the error occurs eg. maybe a couple hours before and after when the error occurs). Logging instructions for the driver can be found in this [doc](https://learn.microsoft.com/en-us/sql/connect/jdbc/tracing-driver-operation?view=sql-server-ver16#enabling-tracing-by-using-the-loggingproperties-file).

> The problem occurs once in a long time - let's say a week, that could be a really large amount of logs.

That does make debugging this issue harder. Right now, there isn't anything actionable we can take on the driver side with what we know.

The things I can think of to do right now are these:

- Revisit your hikari settings and tune and experiment a bit more according to your use case (eg. are the settings appropriate for you used case?). As mentioned by lilgreenbird, we've seen issues in the past like this one and they're usually solved by refining the connection pool settings since the driver works most of the time.

- Reach out to Azure support. They collect telemetry info that might shed some light on your situation.

- Again, we recommend filing an issue with hikari as they might have ideas as well.

**Comment by tkyc** [comment]
Closing for inactivity.
