### ISSUE TITLE
SQLServerException: The server failed to resume the transaction. Desc:3500000021.

### ISSUE THREAD

**Issue by woj-tek** [microsoft/mssql-jdbc#2008]
## Driver version
`10.2.1.jre17`

## SQL Server version
```
Microsoft Azure SQL Edge Developer (RTM) - 15.0.2000.1565 (ARM64) 
	Jun 14 2022 00:37:12 
	Copyright (C) 2019 Microsoft Corporation
	Linux (Ubuntu 18.04.6 LTS aarch64) <ARM64>
```

## Client Operating System
macOS Ventura 13.1

## JAVA/JVM version
```
$ java -version
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode)
```

## Table schema
[`TigPubSubCreateNode`](https://github.com/tigase/tigase-pubsub/blob/a099e0a41b6b85ad597fd46d8ef3ea3e309d3c5c/src/main/database/sqlserver-pubsub-5.0.0.sql#L95-L95) and [`TigPubSubEnsureServiceJid`](https://github.com/tigase/tigase-pubsub/blob/a099e0a41b6b85ad597fd46d8ef3ea3e309d3c5c/src/main/database/sqlserver-pubsub-5.0.0.sql#L61) that both use explicit transactions.

## Problem description

I just hit exactly same issue as https://github.com/microsoft/mssql-jdbc/issues/1704 and it's reproducible. We switched from jTDS driver to original driver from MS due to JDK17 compatibility.

## Expected behavior

SP should continue to work, even if we have explicit transactions within SP.

## Actual behavior

Calling them yields same exception:
```
[2022-12-15 15:14:26:205] [WARNING ] [           in_1-pubsub ] CachedPubSubRepository.saveNode(): Problem saving pubsub data:
tigase.component.exceptions.RepositoryException: Node subscribers writing error
        at tigase.pubsub.repository.PubSubDAOJDBC.updateNodeAffiliation(PubSubDAOJDBC.java:1097)
        at tigase.pubsub.repository.PubSubDAOJDBC.updateNodeAffiliation(PubSubDAOJDBC.java:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at tigase.stats.StatisticsInvocationHandler.invoke(StatisticsInvocationHandler.java:75)
        at jdk.proxy2/jdk.proxy2.$Proxy39.updateNodeAffiliation(Unknown Source)
        at tigase.pubsub.repository.PubSubDAOPool.updateNodeAffiliation(PubSubDAOPool.java:468)
        at tigase.pubsub.repository.cached.CachedPubSubRepository.saveNode(CachedPubSubRepository.java:872)
        at tigase.pubsub.repository.cached.CachedPubSubRepository.update(CachedPubSubRepository.java:598)
        at tigase.pubsub.modules.SubscribeNodeModule.process(SubscribeNodeModule.java:173)
        at tigase.component.modules.StanzaProcessor.execute(StanzaProcessor.java:219)
        at tigase.component.modules.StanzaProcessor.process(StanzaProcessor.java:206)
        at tigase.component.modules.StanzaProcessor.processPacket(StanzaProcessor.java:103)
        at tigase.component.AbstractKernelBasedComponent.processPacket(AbstractKernelBasedComponent.java:81)
        at tigase.pubsub.PubSubComponent.processPacket(PubSubComponent.java:191)
        at tigase.server.AbstractMessageReceiver$QueueListener.run(AbstractMessageReceiver.java:1398)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The server failed to resume the transaction. Desc:3500000021.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1676)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:615)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:537)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7730)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3786)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:515)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at tigase.db.jdbc.PreparedStatementInvocationHandler.invoke(PreparedStatementInvocationHandler.java:38)
        at jdk.proxy2/jdk.proxy2.$Proxy35.execute(Unknown Source)
        at tigase.pubsub.repository.PubSubDAOJDBC.updateNodeAffiliation(PubSubDAOJDBC.java:1089)
        ... 17 more
```

## Error message/stack trace
Complete error message and stack trace.

## Any other details that can be helpful

Currently testing with `10.2.1.jre17` and it was working fine with jtds:1.3.1

Removing explicit transactions works but in our case it could lead to data inconsistencies in some situations thus it would be best to be able to stick with transactions.

## JDBC trace logs
```
[2022-12-16 12:38:33:207] [FINEST  ] [          in_16-pubsub ] PubSubDAOJDBC.updateNodeAffiliation(): Updating node affiliation[1]: node-e51bbea3-68d5-4e9a-bec8-41767e42c4a2 / {admin@test-domain.com/owner}
[2022-12-16 12:38:33:207] [FINER   ] [          in_16-pubsub ] SQLServerPreparedStatement:2.isClosed(): ENTRY
[2022-12-16 12:38:33:207] [FINER   ] [          in_16-pubsub ] SQLServerPreparedStatement:2.isClosed(): RETURN false
[2022-12-16 12:38:33:207] [FINER   ] [          in_16-pubsub ] SQLServerCallableStatement:703.setLong(): ENTRY 1 1
[2022-12-16 12:38:33:207] [FINER   ] [          in_16-pubsub ] SQLServerCallableStatement:703.setLong(): RETURN
[2022-12-16 12:38:33:207] [FINER   ] [          in_16-pubsub ] SQLServerCallableStatement:703.setString(): ENTRY 2 admin@test-domain.com
[2022-12-16 12:38:33:207] [FINER   ] [          in_16-pubsub ] SQLServerCallableStatement:703.setString(): RETURN
[2022-12-16 12:38:33:207] [FINER   ] [          in_16-pubsub ] SQLServerCallableStatement:703.setString(): ENTRY 3 owner
[2022-12-16 12:38:33:207] [FINER   ] [          in_16-pubsub ] SQLServerCallableStatement:703.setString(): RETURN
[2022-12-16 12:38:33:207] [FINER   ] [          in_16-pubsub ] SQLServerCallableStatement:703.execute(): ENTRY
[2022-12-16 12:38:33:207] [FINEST  ] [          in_16-pubsub ] TDSCommand.detach()              : TDSCommand@c62078f (SQLServerCallableStatement:616 executeXXX): detaching...
[2022-12-16 12:38:33:207] [FINEST  ] [          in_16-pubsub ] SQLServerConnection.isConnectionDead(): ConnectionID:3 ClientConnectionId: 4e6c0799-49be-41db-9375-d928b4b05a5d Network not idle. Skipping networkSocketStillConnected check.
[2022-12-16 12:38:33:207] [FINEST  ] [          in_16-pubsub ] TDSCommand.startRequest()        : TDSCommand@76ab007c (SQLServerCallableStatement:703 executeXXX): starting request...
[2022-12-16 12:38:33:207] [FINEST  ] [          in_16-pubsub ] TDSWriter.writeBytes()           : TDSWriter@7d72e5eb (ConnectionID:3) Writing 8 bytes
[2022-12-16 12:38:33:207] [FINEST  ] [          in_16-pubsub ] TDSWriter.writeBytes()           : TDSWriter@7d72e5eb (ConnectionID:3) Writing 8 bytes
[2022-12-16 12:38:33:207] [FINE    ] [          in_16-pubsub ] SQLServerPreparedStatement.buildExecSQLParams(): SQLServerCallableStatement:703: calling sp_executesql: SQL:EXEC TigPubSubSetNodeAffiliation @P0, @P1, @P2
[2022-12-16 12:38:33:207] [FINEST  ] [          in_16-pubsub ] TDSWriter.writeBytes()           : TDSWriter@7d72e5eb (ConnectionID:3) Writing 92 bytes
[2022-12-16 12:38:33:207] [FINEST  ] [          in_16-pubsub ] TDSWriter.writeBytes()           : TDSWriter@7d72e5eb (ConnectionID:3) Writing 96 bytes
[2022-12-16 12:38:33:207] [FINEST  ] [          in_16-pubsub ] TDSWriter.writeBytes()           : TDSWriter@7d72e5eb (ConnectionID:3) Writing 42 bytes
[2022-12-16 12:38:33:207] [FINEST  ] [          in_16-pubsub ] TDSWriter.writeBytes()           : TDSWriter@7d72e5eb (ConnectionID:3) Writing 10 bytes
[2022-12-16 12:38:33:207] [FINEST  ] [          in_16-pubsub ] TDSCommand.startResponse()       : TDSCommand@76ab007c (SQLServerCallableStatement:703 executeXXX): finishing request
[2022-12-16 12:38:33:207] [FINEST  ] [          in_16-pubsub ] TDSWriter.endMessage()           : TDSWriter@7d72e5eb (ConnectionID:3) Finishing TDS message
[2022-12-16 12:38:33:207] [FINEST  ] [          in_16-pubsub ] TDSChannel.logPacket()           : /127.0.0.1:51557 SPID:56 TDSWriter@7d72e5eb (ConnectionID:3) sending packet (337 bytes)
03 01 01 51 00 38 01 00 16 00 00 00 12 00 00 00   ...Q.8..........
02 00 21 00 00 00 38 00 00 00 01 00 00 00 FF FF   ..!...8.........
0A 00 00 00 00 00 E7 40 1F 09 04 D0 00 34 5C 00   .......@.....4\.
45 00 58 00 45 00 43 00 20 00 54 00 69 00 67 00   E.X.E.C. .T.i.g.
50 00 75 00 62 00 53 00 75 00 62 00 53 00 65 00   P.u.b.S.u.b.S.e.
74 00 4E 00 6F 00 64 00 65 00 41 00 66 00 66 00   t.N.o.d.e.A.f.f.
69 00 6C 00 69 00 61 00 74 00 69 00 6F 00 6E 00   i.l.i.a.t.i.o.n.
20 00 40 00 50 00 30 00 2C 00 20 00 40 00 50 00    .@.P.0.,. .@.P.
31 00 2C 00 20 00 40 00 50 00 32 00 00 00 E7 40   1.,. .@.P.2....@
1F 09 04 D0 00 34 60 00 40 00 50 00 30 00 20 00   .....4`.@.P.0. .
62 00 69 00 67 00 69 00 6E 00 74 00 2C 00 40 00   b.i.g.i.n.t.,.@.
50 00 31 00 20 00 6E 00 76 00 61 00 72 00 63 00   P.1. .n.v.a.r.c.
68 00 61 00 72 00 28 00 34 00 30 00 30 00 30 00   h.a.r.(.4.0.0.0.
29 00 2C 00 40 00 50 00 32 00 20 00 6E 00 76 00   ).,.@.P.2. .n.v.
61 00 72 00 63 00 68 00 61 00 72 00 28 00 34 00   a.r.c.h.a.r.(.4.
30 00 30 00 30 00 29 00 00 00 26 08 08 01 00 00   0.0.0.)...&.....
00 00 00 00 00 00 00 E7 40 1F 09 04 D0 00 34 2A   ........@.....4*
00 61 00 64 00 6D 00 69 00 6E 00 40 00 74 00 65   .a.d.m.i.n.@.t.e
00 73 00 74 00 2D 00 64 00 6F 00 6D 00 61 00 69   .s.t.-.d.o.m.a.i
00 6E 00 2E 00 63 00 6F 00 6D 00 00 00 E7 40 1F   .n...c.o.m....@.
09 04 D0 00 34 0A 00 6F 00 77 00 6E 00 65 00 72   ....4..o.w.n.e.r
00                                                .
[2022-12-16 12:38:33:207] [FINEST  ] [          in_16-pubsub ] TDSCommand.onRequestComplete()   : TDSCommand@76ab007c (SQLServerCallableStatement:703 executeXXX): request complete
[2022-12-16 12:38:33:208] [FINEST  ] [          in_16-pubsub ] TDSCommand.startResponse()       : TDSCommand@76ab007c (SQLServerCallableStatement:703 executeXXX): Reading response...
[2022-12-16 12:38:33:208] [FINEST  ] [          in_16-pubsub ] TDSChannel$ProxyInputStream.readInternal(): com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@4d131e3e Reading 8 bytes
[2022-12-16 12:38:33:215] [FINEST  ] [          in_16-pubsub ] TDSChannel$ProxyInputStream.readInternal(): com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@4d131e3e Read 8 bytes
[2022-12-16 12:38:33:215] [FINEST  ] [          in_16-pubsub ] TDSChannel$ProxyInputStream.readInternal(): com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@4d131e3e Reading 393 bytes
[2022-12-16 12:38:33:215] [FINEST  ] [          in_16-pubsub ] TDSChannel$ProxyInputStream.readInternal(): com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@4d131e3e Read 393 bytes
[2022-12-16 12:38:33:215] [FINEST  ] [          in_16-pubsub ] TDSChannel.logPacket()           : /127.0.0.1:51557 SPID:56 TDSReader@130 (ConnectionID:3 ClientConnectionId: 4e6c0799-49be-41db-9375-d928b4b05a5d) received Packet:1 (393 bytes)
04 01 01 91 00 38 01 00 AB D6 00 56 0F 00 00 02   .....8.....V....
00 58 00 54 00 68 00 65 00 20 00 74 00 72 00 61   .X.T.h.e. .t.r.a
00 6E 00 73 00 61 00 63 00 74 00 69 00 6F 00 6E   .n.s.a.c.t.i.o.n
00 20 00 61 00 63 00 74 00 69 00 76 00 65 00 20   . .a.c.t.i.v.e.
00 69 00 6E 00 20 00 74 00 68 00 69 00 73 00 20   .i.n. .t.h.i.s.
00 73 00 65 00 73 00 73 00 69 00 6F 00 6E 00 20   .s.e.s.s.i.o.n.
00 68 00 61 00 73 00 20 00 62 00 65 00 65 00 6E   .h.a.s. .b.e.e.n
00 20 00 63 00 6F 00 6D 00 6D 00 69 00 74 00 74   . .c.o.m.m.i.t.t
00 65 00 64 00 20 00 6F 00 72 00 20 00 61 00 62   .e.d. .o.r. .a.b
00 6F 00 72 00 74 00 65 00 64 00 20 00 62 00 79   .o.r.t.e.d. .b.y
00 20 00 61 00 6E 00 6F 00 74 00 68 00 65 00 72   . .a.n.o.t.h.e.r
00 20 00 73 00 65 00 73 00 73 00 69 00 6F 00 6E   . .s.e.s.s.i.o.n
00 2E 00 0C 66 00 33 00 62 00 34 00 65 00 35 00   ....f.3.b.4.e.5.
66 00 39 00 61 00 66 00 31 00 38 00 00 01 00 00   f.9.a.f.1.8.....
00 AA A0 00 83 0F 00 00 01 10 3D 00 54 00 68 00   ..........=.T.h.
65 00 20 00 73 00 65 00 72 00 76 00 65 00 72 00   e. .s.e.r.v.e.r.
20 00 66 00 61 00 69 00 6C 00 65 00 64 00 20 00    .f.a.i.l.e.d. .
74 00 6F 00 20 00 72 00 65 00 73 00 75 00 6D 00   t.o. .r.e.s.u.m.
65 00 20 00 74 00 68 00 65 00 20 00 74 00 72 00   e. .t.h.e. .t.r.
61 00 6E 00 73 00 61 00 63 00 74 00 69 00 6F 00   a.n.s.a.c.t.i.o.
6E 00 2E 00 20 00 44 00 65 00 73 00 63 00 3A 00   n... .D.e.s.c.:.
33 00 38 00 30 00 30 00 30 00 30 00 30 00 30 00   3.8.0.0.0.0.0.0.
32 00 31 00 2E 00 0C 66 00 33 00 62 00 34 00 65   2.1....f.3.b.4.e
00 35 00 66 00 39 00 61 00 66 00 31 00 38 00 00   .5.f.9.a.f.1.8..
01 00 00 00 FD 02 00 FD 00 00 00 00 00 00 00 00   ................
00                                                .
[2022-12-16 12:38:33:215] [FINEST  ] [          in_16-pubsub ] TDSCommand.onResponseEOM()       : TDSCommand@76ab007c (SQLServerCallableStatement:703 executeXXX): disabling interrupts
[2022-12-16 12:38:33:215] [FINEST  ] [          in_16-pubsub ] TDSReader.nextPacket()           : TDSReader@130 (ConnectionID:3 ClientConnectionId: 4e6c0799-49be-41db-9375-d928b4b05a5d) Moving to next packet -- unlinking consumed packet
[2022-12-16 12:38:33:215] [FINEST  ] [          in_16-pubsub ] TDSParser.parse()                : TDSReader@130 (ConnectionID:3 ClientConnectionId: 4e6c0799-49be-41db-9375-d928b4b05a5d): getNextResult: Processing TDS_MSG (0xAB)
[2022-12-16 12:38:33:216] [FINEST  ] [          in_16-pubsub ] TDSReader.readBytes()            : TDSReader@130 (ConnectionID:3 ClientConnectionId: 4e6c0799-49be-41db-9375-d928b4b05a5d) Reading 176 bytes from offset 11
[2022-12-16 12:38:33:216] [FINEST  ] [          in_16-pubsub ] TDSReader.readBytes()            : TDSReader@130 (ConnectionID:3 ClientConnectionId: 4e6c0799-49be-41db-9375-d928b4b05a5d) Reading 24 bytes from offset 188
[2022-12-16 12:38:33:218] [FINEST  ] [          in_16-pubsub ] TDSParser.parse()                : TDSReader@130 (ConnectionID:3 ClientConnectionId: 4e6c0799-49be-41db-9375-d928b4b05a5d): getNextResult: Processing TDS_ERR (0xAA)
[2022-12-16 12:38:33:218] [FINEST  ] [          in_16-pubsub ] TDSReader.readBytes()            : TDSReader@130 (ConnectionID:3 ClientConnectionId: 4e6c0799-49be-41db-9375-d928b4b05a5d) Reading 122 bytes from offset 228
[2022-12-16 12:38:33:218] [FINEST  ] [          in_16-pubsub ] TDSReader.readBytes()            : TDSReader@130 (ConnectionID:3 ClientConnectionId: 4e6c0799-49be-41db-9375-d928b4b05a5d) Reading 24 bytes from offset 351
[2022-12-16 12:38:33:218] [FINEST  ] [          in_16-pubsub ] TDSParser.parse()                : TDSReader@130 (ConnectionID:3 ClientConnectionId: 4e6c0799-49be-41db-9375-d928b4b05a5d): getNextResult: Processing TDS_DONE (0xFD)
[2022-12-16 12:38:33:218] [FINE    ] [          in_16-pubsub ] SQLServerException.logException(): *** SQLException: com.microsoft.sqlserver.jdbc.SQLServerException: The server failed to resume the transaction. Desc:3800000021. Msg 3971, Level 16, State 1, The server failed to resume the transaction. Desc:3800000021.
[2022-12-16 12:38:33:219] [WARNING ] [          in_16-pubsub ] CachedPubSubRepository.saveNode(): Problem saving pubsub data:
tigase.component.exceptions.RepositoryException: Node subscribers writing error
        at tigase.pubsub.repository.PubSubDAOJDBC.updateNodeAffiliation(PubSubDAOJDBC.java:1097)
        at tigase.pubsub.repository.PubSubDAOJDBC.updateNodeAffiliation(PubSubDAOJDBC.java:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at tigase.stats.StatisticsInvocationHandler.invoke(StatisticsInvocationHandler.java:75)
        at jdk.proxy2/jdk.proxy2.$Proxy39.updateNodeAffiliation(Unknown Source)
        at tigase.pubsub.repository.PubSubDAOPool.updateNodeAffiliation(PubSubDAOPool.java:468)
        at tigase.pubsub.repository.cached.CachedPubSubRepository.saveNode(CachedPubSubRepository.java:872)
        at tigase.pubsub.repository.cached.CachedPubSubRepository.update(CachedPubSubRepository.java:598)
        at tigase.pubsub.modules.SubscribeNodeModule.process(SubscribeNodeModule.java:173)
        at tigase.component.modules.StanzaProcessor.execute(StanzaProcessor.java:219)
        at tigase.component.modules.StanzaProcessor.process(StanzaProcessor.java:206)
        at tigase.component.modules.StanzaProcessor.processPacket(StanzaProcessor.java:103)
        at tigase.component.AbstractKernelBasedComponent.processPacket(AbstractKernelBasedComponent.java:81)
        at tigase.pubsub.PubSubComponent.processPacket(PubSubComponent.java:191)
        at tigase.server.AbstractMessageReceiver$QueueListener.run(AbstractMessageReceiver.java:1398)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The server failed to resume the transaction. Desc:3800000021.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1676)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:615)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:537)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7730)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3786)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:515)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at tigase.db.jdbc.PreparedStatementInvocationHandler.invoke(PreparedStatementInvocationHandler.java:38)
        at jdk.proxy2/jdk.proxy2.$Proxy35.execute(Unknown Source)
        at tigase.pubsub.repository.PubSubDAOJDBC.updateNodeAffiliation(PubSubDAOJDBC.java:1089)
        ... 17 more
```

(those are around the exception, could dig up more)

**Comment by tkyc** [comment]
Hi @woj-tek, would it be possible for you in the meantime to remove the explicit transactions as a workaround? 

After doing an initial look through in the code, it'll take some time for me to understand the nuances and to come up with a solution as I'm not sure this is a trivial fix. Thanks for your patience and understanding. Issue #1704 should have been more emphasized by us as a bug when it was first discovered.

**Comment by woj-tek** [comment]
Indeed, we disabled it for now accepting the tradeoff (lower SQL Server usage and only relatively small possibility of concurrency data corruption)

**Comment by tkyc** [comment]
Could you provide the Java code used to execute the SP? Thanks.

**Comment by woj-tek** [comment]
Of course. This particulare ST is a result of execution of [`updateNodeAffiliation()` method](https://github.com/tigase/tigase-pubsub/blob/8ebaf56edf0be0234bff638a61d1c15f5283dcc9/src/main/java/tigase/pubsub/repository/PubSubDAOJDBC.java#L1067-L1067). Underneath it uses our generic DataRepository implementation: we get prepared statement via [`getPreparedStatement()`](https://github.com/tigase/tigase-server/blob/12ec0802634f25b985c74986026879711875a93d/src/main/java/tigase/db/jdbc/DataRepositoryImpl.java#L216-L216), which is created in [`initStatement()`](https://github.com/tigase/tigase-server/blob/12ec0802634f25b985c74986026879711875a93d/src/main/java/tigase/db/jdbc/DataRepositoryImpl.java#L491-L491) / [`prepareQuery()`](https://github.com/tigase/tigase-server/blob/12ec0802634f25b985c74986026879711875a93d/src/main/java/tigase/db/jdbc/DataRepositoryImpl.java#L546-L546). I think we don't do anything out of the ordinary here, the only special thing being usage of `Statement.RETURN_GENERATED_KEYS` for MS SQL Server.

**Comment by lilgreenbird** [comment]
thank you for your patience sorry this has taken a while, we are still in the process of preparing for our GA release we will get back to investigating this issue after.

**Comment by woj-tek** [comment]
No worries :-)

**Comment by David-Engel** [comment]
Are you turning off auto commit in the driver (`setAutoCommit(false)`)? It's not recommended to mix JDBC transactions and T-SQL transactions. It can result in the error you are seeing.
https://learn.microsoft.com/en-us/sql/connect/jdbc/understanding-transactions?view=sql-server-ver16#:~:text=Applications%20should%20control,the%20transaction%22%20exceptions.

**Comment by woj-tek** [comment]
No, even more - when preparing the connection we explicitly enable auto-commit:

https://github.com/tigase/tigase-server/blob/c81e831f4c635c3687ad7dea6ee7ed39433e3cbd/src/main/java/tigase/db/jdbc/DataRepositoryImpl.java#L526-L526

**Comment by lilgreenbird** [comment]
@woj-tek 

Can you please share the app you used to see the issue? It's difficult for us to debug the issue since we're unable to repro here. It would really help if you have the exact code you used that worked ok using jTDS but fails when using our driver.

**Comment by lilgreenbird** [comment]
closing due to inactivity, please feel free to request opening if you have more info or questions

**Comment by JDBC-0** [comment]
The problem still exists - even with driver version 13.4.0!   @lilgreenbird
#1704 was from me and the current problem we have just looks exactly the same: occasional errors, but after removing the explicit transaction in the stored procedure it didn't occur anymore.

**Comment by machavan** [comment]
Hi @JDBC-0, thanks for highlighting.  We will appreciate if you could open a new issue with the repro app shared with it ? It will help us track it better.
