### ISSUE TITLE
Connection.rollback method does not work for the Azure Synapse "serverless" database

### ISSUE THREAD

**Issue by LonwoLonwo** [microsoft/mssql-jdbc#2071]
## Driver version
Provide the JDBC driver version - the latest

## SQL Server version
Database: Azure Synapse "serverless"
Server: Microsoft SQL Server 12.00.2531, Microsoft Azure SQL Data Warehouse - 10.0.15318.0

## Client Operating System
Windows 10

## Problem description

One of our users has problem with data transfer operation in the NOT auto-commit mode in our program because we use the standard Connection method - rollback.

https://github.com/dbeaver/dbeaver/issues/18820

The issue that he has during this method execution:

```java
com.microsoft.sqlserver.jdbc.SQLServerException:  '@@TRANCOUNT' is not supported.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:283)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:129)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:26)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$1ConnectionCommand.doExecute(SQLServerConnection.java:3316)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3274)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectionCommand(SQLServerConnection.java:3320)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.rollback(SQLServerConnection.java:3516)
```

As I can see in the [documentation](https://learn.microsoft.com/en-us/sql/t-sql/functions/trancount-transact-sql?view=sql-server-ver16)

> This syntax is not supported by serverless SQL pool in Azure Synapse Analytics.

The user uses not the latest driver, but  I do not see in the code any conditions for the serverless databases:

https://github.com/microsoft/mssql-jdbc/blob/f636770978e9a6e12df67b4d426e569eaf77dbec/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L4374-L4387

## Expected behavior
Using another function for the Azure Synapse "serverless" database

**Comment by tkyc** [comment]
@LonwoLonwo We've had issues in the past related to this, more recently ie. https://github.com/microsoft/mssql-jdbc/issues/2071. This is as designed and so there isn't anything the driver can do if the database doesn't support transactions.

I'll reopen discussion within the team and see what their thoughts are again as this is the second time this issue was brought up in the past few months. I'll let you know if opinions have changed.

**Comment by LonwoLonwo** [comment]
I see that I can't get this info from this method:

https://github.com/microsoft/mssql-jdbc/blob/242911001e33e1ce242aa2066cf725a7553b885d/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java#L2171-L2175

Maybe another method has the `doesn't support transactions` info?

**Comment by tkyc** [comment]
That looks like a mistake by us. We'll need to update that method.
