### ISSUE TITLE
OpenSSL 3+ requires SSL_OP_IGNORE_UNEXPECTED_EOF flag to connect to SQL Server

### ISSUE THREAD

**Issue by EternalDeiwos** [microsoft/mssql-jdbc#2083]
## Driver version

MSSQL JDBC 11.2.1 (`mssql-jdbc-11.2.0.jre8-preview.jar`)

## SQL Server version

```
Microsoft SQL Server 2019 (RTM-CU18-GDR) (KB5021124) - 15.0.4280.7 (X64) 
	Jan 23 2023 12:37:13 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor)
```

## Client Operating System

Ubuntu 22.04.1 LTS with OpenSSL `3.0.2-0ubuntu1.8`

## JAVA/JVM version

```
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (build 25.362-b09, mixed mode)
```

## Problem description

Changes in OpenSSL 3+ made checking for `close_notify` more strict, such that it produces an error when it is not sent. A flag was provided to disable this stricter check but is not enabled by default. The [man pages](https://www.openssl.org/docs/man3.0/man3/SSL_set_options.html) for OpenSSL display the following:

> SSL_OP_IGNORE_UNEXPECTED_EOF
>
> Some TLS implementations do not send the mandatory close_notify alert on shutdown. If the application tries to wait for the close_notify alert but the peer closes the connection without sending it, an error is generated. When this option is enabled the peer does not need to send the close_notify alert and a closed connection will be treated as if the close_notify alert was received.
>
> You should only enable this option if the protocol running over TLS can detect a truncation attack itself, and that the application is checking for that truncation attack.
>
> For more information on shutting down a connection, see [SSL_shutdown(3)](https://www.openssl.org/docs/man3.0/man3/SSL_shutdown.html).

The root of this problem seems to be SQL Server does not use a compliant TLS implementation as described above. I would like to imagine a scenario where SQL Server could fix this problem on their side but the turnaround is likely to be long and we have no visibility to know whether it is actually being worked on. In the meanwhile, none of our systems using OpenSSL 3+ are able to connect to any of our DBMS'.

We are pursuing support channels for SQL Server directly, however parallel efforts are more likely to produce a workaround faster.

## Expected behavior

The JDBC driver should set the `SSL_OP_IGNORE_UNEXPECTED_EOF` flag on connections made to SQL Server using OpenSSL 3+. Alternatively, an option should be provided to enable this behaviour.

## Actual behavior

No connections are possible using the MSSQL JDBC driver on systems running OpenSSL 3+.

The corresponding error message of `Connection reset` is also not particularly helpful.

## Error message/stack trace

<details>
<summary>Log</summary>

```
java.io.IOException: Connection reset ClientConnectionId:...
        at com.microsoft.sqlserver.jdbc.TDSChannel$SSLHandshakeInputStream.ensureSSLPayload(IOBuffer.java:918)
        at com.microsoft.sqlserver.jdbc.TDSChannel$SSLHandshakeInputStream.readInternal(IOBuffer.java:968)
        at com.microsoft.sqlserver.jdbc.TDSChannel$SSLHandshakeInputStream.read(IOBuffer.java:961)
        at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1207)
        at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:1194)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1505)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1420)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
        at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1795)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3329)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2950)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2790)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1663)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1064)
        at com.intellij.database.remote.jdbc.helpers.JdbcHelperImpl.connect(JdbcHelperImpl.java:54)
        at com.intellij.database.remote.jdbc.impl.RemoteDriverImpl.connect(RemoteDriverImpl.java:26)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
        Suppressed: com.intellij.database.util.AsyncTask$Frame$FrameData: Async frame data: <Anonymous> -> Refresh -> Submit -> Prepare connection -> Establish database connection -> Get database credentials -> Perform database connection
```

</details>

I believe the error in JDBC is being caused by this underlying error (see below):

```
4087DB192E7F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:../ssl/record/rec_layer_s3.c:308:
```

## Any other details that can be helpful

Unfortunately I am not the application developer so my ability to debug this on my side is limited; my goal here is to notify and provide as much information as possible to get the ball rolling.

That said, for demonstration purposes please consider the following examples using the OpenSSL CLI:

<details>
<summary>

Connection using OpenSSL `3.0.2-0ubuntu1.8`

</summary>

```bash
openssl s_client -connect x.x.x.x:1433
```

```
CONNECTED(00000003)
4087DB192E7F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:../ssl/record/rec_layer_s3.c:308:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 300 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

</details>

<details>
<summary>

Connection using OpenSSL `3.0.2-0ubuntu1.8` with `-ignore_unexpected_eof`

</summary>

```bash
openssl s_client -ignore_unexpected_eof -connect x.x.x.x:1433
```

```
CONNECTED(00000003)
closed
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 293 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

</details>

<details>
<summary>

Connection using OpenSSL `1.1.1n`

</summary>

```bash
openssl s_client -connect x.x.x.x:1433
```

```
CONNECTED(00000003)
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 283 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

</details>

<details>
<summary>

Connection using LibreSSL `3.3.6`

</summary>

```bash
openssl s_client -connect x.x.x.x:1433
```

```
CONNECTED(00000003)
read:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 287 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Start Time: 1677486738
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
```

</details>

**Comment by Jeffery-Wasty** [comment]
@EternalDeiwos,

Thank you for bringing this to our attention. We'll look into whether this is something we can resolve from the JDBC side, and keep you updated on the progress.

**Comment by EternalDeiwos** [comment]
After some further testing I think this problem might not actually be related to the OpenSSL 3+ changes. I was able to successfully connect to the database using the official ODBC driver on the same system with OpenSSL 3.0.2-0ubuntu1.8. I think this indicates the problem might be in the JDBC driver after all.
