### ISSUE TITLE
MS JDBC Driver runs into issues with PreparedStatement over TLS1.3

### ISSUE THREAD

**Issue by yong-jie-gong** [microsoft/mssql-jdbc#2090]
## Driver version
    <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc</artifactId>
      <version>12.2.0.jre11</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc_auth</artifactId>
      <version>12.2.0.x64</version>
      <type>dll</type>
    </dependency>

## SQL Server version
Provide the output of executing `SELECT @@VERSION` on your target SQL Server.
Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64) 
	Oct  8 2022 05:58:25 
	Copyright (C) 2022 Microsoft Corporation
	Express Edition (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) (Hypervisor)

## Client Operating System
Provide the Operating System the client application is running on.
Window 10 Enterprise
![image](https://user-images.githubusercontent.com/13399313/224213458-20dea9f3-e1de-4c64-aa67-32fd06a05cdc.png)

## JAVA/JVM version
Provide the JAVA/JVM version (e.g. java version "1.8.0").
OpenJDK 11.0.6

## Table schema
Provide the table schema to repro the issue.
use embeded table "sys.tables"

## Problem description
Provide full details of the problem.
with code below
```java
        String url = "jdbc:sqlserver://sqlserver.test.com:1433;databaseName=test1;encrypt=strict;trustServerCertificate=false;trustStore=C:\\tmp\\sqlserver2022.pfx;trustStorePassword=testpass;user=test1;password=testpass";
        
        Connection conn = DriverManager.getConnection(url);
        Statement stmt1 = conn.createStatement();
        ResultSet rs1 = stmt1.executeQuery("select t.schema_id, schema_name(t.schema_id) as schema_name, t.name as table_name, t.create_date, t.modify_date "
                + " from sys.tables t  "
                + " where t.schema_id=1 "
                + " order by t.schema_id "
                + " OFFSET 0 ROWS FETCH NEXT 2 ROWS ONLY"
                + "");
        while (rs1.next()) {
            System.out.println(rs1.getObject(1) + " " + rs1.getObject(2) + " " + rs1.getObject(3));
        }
        
        
        PreparedStatement stmt2 = conn.prepareStatement("select t.schema_id, schema_name(t.schema_id) as schema_name, t.name as table_name, t.create_date, t.modify_date "
                + " from sys.tables t  "
                + " where t.name=?");
        stmt2.setString(1, "dbo");
        ResultSet rs2  = stmt2.executeQuery();
        while (rs2.next()) {
            System.out.println("Test2: "+rs2.getObject(1) + " " + rs2.getObject(2));
        }

````
"stmt1" can be executed correctly and print the query result correctly, but "stmt2" runs into issue which failed  in line "stmt2.executeQuery()"

## Expected behavior
It seems JDBC driver or MSSQL server bugs since "Statement" works fine. exception happens only with PreparedStatement"

## Error message/stack trace
**Error stack:**
Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 1: The parameter name is invalid.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1695)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:620)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:539)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7685)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4048)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:272)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:246)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:457)
	at org.basic.db.mssql.DatabaseMSSQL.main(DatabaseMSSQL.java:53)

## JDBC trace logs
Provide the JDBC driver trace logs.  Instructions can be found here: https://docs.microsoft.com/sql/connect/jdbc/tracing-driver-operation

**Comment by Jeffery-Wasty** [comment]
You can't set table name in a prepared statement using setString, it's meant only column values. This is for security reasons. If you really want to send in the table name dynamically, you can use string concatenation, e.g. [here](https://stackoverflow.com/a/45248399), but please be aware of the security risks you would be taking.

**Comment by mmimica** [comment]
They did not use it for table name. The bind variable is for a column `t.value`.

**Comment by Jeffery-Wasty** [comment]
Thank you @mmimica. You're right, I misread the name column as table name. 

I'm not able to replicate this on my end, but will continue to look into this.

**Comment by David-Engel** [comment]
This is an issue in SQL Server 2022 RTM that is fixed in CU1:
https://learn.microsoft.com/en-us/troubleshoot/sql/releases/sqlserver-2022/cumulativeupdate1#2042238

I verified I could repro it before applying CU1 and not after.

Regards,
David

**Comment by Jeffery-Wasty** [comment]
Hi @yong-jie-gong,

Have you been able to confirm this issue is resolved for you when using CU1 as opposed to RTM?

**Comment by Jeffery-Wasty** [comment]
Closing due to inactivity.
