### ISSUE TITLE
"Cannot find data type" error when attempting to create a TVP

### ISSUE THREAD

**Issue by humada05** [microsoft/mssql-jdbc#2126]
## Driver version
Provide the JDBC driver version (e.g. 10.2.0).

`9.4.0.jre11`

## SQL Server version
Provide the output of executing `SELECT @@VERSION` on your target SQL Server.

```
Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64) 
	Oct  8 2022 05:58:25 
	Copyright (C) 2022 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 20.04.5 LTS) <X64>
```

## Client Operating System
Provide the Operating System the client application is running on.

Running SQL Server 2022 on a docker instance inside my Macbook Pro.

## JAVA/JVM version
Provide the JAVA/JVM version (e.g. java version "1.8.0").

```
> java -version
openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment Zulu11.45+27-CA (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.45+27-CA (build 11.0.10+9-LTS, mixed mode)

```

## Table schema
Ill provide the java code that includes the schema as well. This is directly from an MS article explaining [how to use TVPs with the JDBC driver](https://learn.microsoft.com/en-us/sql/connect/jdbc/using-table-valued-parameters?view=sql-server-ver16#passing-a-table-valued-parameter-as-a-sqlserverdatatable-object):
```
/* Assumes connection is an active Connection object. */

// Create an in-memory data table.  
SQLServerDataTable sourceDataTable = new SQLServerDataTable();
  
// Define metadata for the data table.  
sourceDataTable.addColumnMetadata("CategoryID" ,java.sql.Types.INTEGER);
sourceDataTable.addColumnMetadata("CategoryName" ,java.sql.Types.NVARCHAR);
  
// Populate the data table.  
sourceDataTable.addRow(1, "CategoryNameValue1");
sourceDataTable.addRow(2, "CategoryNameValue2");
  
// Pass the data table as a table-valued parameter using a prepared statement.  
SQLServerPreparedStatement pStmt =
        (SQLServerPreparedStatement) connection.prepareStatement(  
            "INSERT INTO dbo.Categories SELECT * FROM ?;");  
pStmt.setStructured(1, "dbo.CategoryTableType", sourceDataTable);  
pStmt.execute();  
```

## Problem description
Im attempting both examples provided by the MS docs. In both cases, Im getting an error once the code attempts to call `pStmt.execute()`.

## Expected behavior
I should be able to execute the `INSERT INTO dbo.Categories SELECT * FROM ?` without any errors.
## Actual behavior
Described below, the code fails with exception thrown: `com.microsoft.sqlserver.jdbc.SQLServerException: Column, parameter, or variable @P0. : Cannot find data type`.
## Error message/stack trace
```
com.microsoft.sqlserver.jdbc.SQLServerException: Column, parameter, or variable @P0. : Cannot find data type dbo.CategoryTableType.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1662)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:615)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:537)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7417)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3488)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:237)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:515)
```
## Any other details that can be helpful
This is using dockerized SQL Server, but I was able to replicate the bug with different versions.

## JDBC trace logs
```
May 11, 2023 3:42:01 PM com.microsoft.sqlserver.jdbc.Util parseUrl
FINE: Property:serverName Value:localhost
May 11, 2023 3:42:02 PM com.microsoft.sqlserver.jdbc.Util parseUrl
FINE: Property:portNumber Value:7020
May 11, 2023 3:42:02 PM com.microsoft.sqlserver.jdbc.Util parseUrl
FINE: Property:databaseName Value:test_database
May 11, 2023 3:42:02 PM com.microsoft.sqlserver.jdbc.SQLServerConnection <init>
FINE: ConnectionID:1 created by (SQLServerDriver:1)
May 11, 2023 3:42:02 PM com.microsoft.sqlserver.jdbc.SQLServerConnection login
FINE: ConnectionID:1 This attempt server name: localhost port: 7020 InstanceName: null useParallel: false
May 11, 2023 3:42:02 PM com.microsoft.sqlserver.jdbc.SQLServerConnection login
FINE: ConnectionID:1 This attempt endtime: 1683844923945
May 11, 2023 3:42:02 PM com.microsoft.sqlserver.jdbc.SQLServerConnection login
FINE: ConnectionID:1 This attempt No: 0
May 11, 2023 3:42:02 PM com.microsoft.sqlserver.jdbc.SQLServerConnection connectHelper
FINE: ConnectionID:1 Connecting with server: localhost port: 7020 Timeout slice: 1854 Timeout Full: 15
May 11, 2023 3:42:02 PM com.microsoft.sqlserver.jdbc.SQLServerConnection Prelogin
FINE: ConnectionID:1 ClientConnectionId: 0f500e6b-3dde-4406-981c-fbbecc591ec1 Server returned major version:16
May 11, 2023 3:42:02 PM com.microsoft.sqlserver.jdbc.SQLServerStatement <init>
FINE: SQLServerPreparedStatement:1 created by (ConnectionID:1 ClientConnectionId: 0f500e6b-3dde-4406-981c-fbbecc591ec1)
May 11, 2023 3:42:02 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement buildExecSQLParams
FINE: SQLServerPreparedStatement:1: calling sp_executesql: SQL:INSERT INTO dbo.Categories SELECT * FROM @P0;
May 11, 2023 3:42:02 PM com.microsoft.sqlserver.jdbc.SQLServerException logException
FINE: *** SQLException: com.microsoft.sqlserver.jdbc.SQLServerException: Column, parameter, or variable @P0. : Cannot find data type dbo.CategoryTableType. Msg 351, Level 16, State 3, Column, parameter, or variable @P0. : Cannot find data type dbo.CategoryTableType.
```

**Comment by Jeffery-Wasty** [comment]
Hi @humada05,

Near the top of the page, I see a line: "You have to create a table type and define the structure in SQL Server before you can use table-valued parameters in your client applications.". Was this done prior to running the query?

**Comment by humada05** [comment]
@Jeffery-Wasty ah I missed that. That was it, thank you!
