### ISSUE TITLE
java.lang.NullPointerException at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6890)

### ISSUE THREAD

**Issue by rafalhcl** [microsoft/mssql-jdbc#2141]
## Driver version
12.3.0.0

## SQL Server version
Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

## Client Operating System
Windows Server 2019 Standard

## JAVA/JVM version
java.version = 1.8.0_361

## Table schema
dbo

## Problem description

JDBC driver throws java.lang.NullPointerException into the server application logs. Exact scenario is not fully known, but it may be related to the network connection issues / connection terminated / socket closed.

## Expected behavior
java.lang.NullPointerException should not be thrown, instead meaningful error code and checked exception should be thrown.

## Actual behavior
java.lang.NullPointerException is thrown by jdbc driver in some situations.

## Error message/stack trace

[5/28/23 21:53:26:080 UTC] 0000244f SystemErr                                                    R Exception in thread "Thread-463" 
[5/28/23 21:53:26:095 UTC] 0000244f SystemErr                                                    R java.lang.NullPointerException
[5/28/23 21:53:26:095 UTC] 0000244f SystemErr                                                    R 	at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6890)
[5/28/23 21:53:26:095 UTC] 0000244f SystemErr                                                    R 	at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:8087)
[5/28/23 21:53:26:095 UTC] 0000244f SystemErr                                                    R 	at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:8050)
[5/28/23 21:53:26:095 UTC] 0000244f SystemErr                                                    R 	at com.microsoft.sqlserver.jdbc.SQLServerConnection$1ConnectionCommand.doExecute(SQLServerConnection.java:4195)
[5/28/23 21:53:26:095 UTC] 0000244f SystemErr                                                    R 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7685)
[5/28/23 21:53:26:095 UTC] 0000244f SystemErr                                                    R 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeReconnectCommand(SQLServerConnection.java:4157)
[5/28/23 21:53:26:095 UTC] 0000244f SystemErr                                                    R 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectionCommand(SQLServerConnection.java:4201)
[5/28/23 21:53:26:095 UTC] 0000244f SystemErr                                                    R 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:5099)
[5/28/23 21:53:26:095 UTC] 0000244f SystemErr                                                    R 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$300(SQLServerConnection.java:93)
[5/28/23 21:53:26:095 UTC] 0000244f SystemErr                                                    R 	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:5025)
[5/28/23 21:53:26:095 UTC] 0000244f SystemErr                                                    R 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7685)
[5/28/23 21:53:26:095 UTC] 0000244f SystemErr                                                    R 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeReconnect(SQLServerConnection.java:3519)
[5/28/23 21:53:26:095 UTC] 0000244f SystemErr                                                    R 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3500)
[5/28/23 21:53:26:095 UTC] 0000244f SystemErr                                                    R 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3102)
[5/28/23 21:53:26:095 UTC] 0000244f SystemErr                                                    R 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2948)
[5/28/23 21:53:26:095 UTC] 0000244f SystemErr                                                    R 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1799)
[5/28/23 21:53:26:095 UTC] 0000244f SystemErr                                                    R 	at com.microsoft.sqlserver.jdbc.ReconnectThread.run(IdleConnectionResiliency.java:461)
[5/28/23 21:53:26:133 UTC] 00000405 SystemOut                                                    O 2023-05-28 21:53:26 ERROR: Java::ComMicrosoftSqlserverJdbc::SQLServerException: Socket closed: SELECT TOP (1) [Version] FROM [DBINFO]

## Any other details that can be helpful
none

## JDBC trace logs
none available

**Comment by rafalhcl** [comment]
Hi @Jeffery-Wasty,

I was able to reproduce the same issue with trace on.

The error was simulated on another machine by restarting the MSSQL Server while application was working. Originally the issue may have different source, like socket closed due to network issues. The NPE is coming from the same origin.

The connection string was:
`jdbc:sqlserver://localhost;database=temadb;applicationName=Tivoli Endpoint Manager Analytics;lockTimeout=180000;encrypt=false`

[trace.zip](https://github.com/microsoft/mssql-jdbc/files/11705109/trace.zip)

**Comment by Jeffery-Wasty** [comment]
We've now fixed this. The next release to include this fix will be our GA on July 31st.
