### ISSUE TITLE
Thread stuck infinite while reading result set  ,infinite loop when getting ResultSet

### ISSUE THREAD

**Issue by chinnusabbineni** [microsoft/mssql-jdbc#2203]
## Driver version
Provide the JDBC driver version (e.g. 10.2.0).
Driver version is : 11.2.3
## SQL Server version
Provide the output of executing `SELECT @@VERSION` on your target SQL Server.
sql server 2016
## Client Operating System
Provide the Operating System the client application is running on.
client application is on
os: Microsoft Windows Server 2019 Standard
    service pack: 
    physical memory: 65534,9
    manufacturer: VMware, Inc.
    model: VMware7,1
    type: x64-based PC
    pagefile "d:\pagefile.sys"
      size: 20480
      max size: 20480

    Active Processes "Active Processes"
      processes running: 231

## JAVA/JVM version
Provide the JAVA/JVM version (e.g. java version "1.8.0").
java 1.8. (1.8.352)
<jdk.version>8.0</jdk.version>
<jdk.patch>352</jdk.patch>
<zulu.version>8.66.0.15</zulu.version>
## Table schema
Provide the table schema to repro the issue.

## Problem description
A thread is running indefinitely in fetching the result and blocking other operations.
## Expected behavior
Thread should be unlocked or killed after predefined time if the resultset is not returned.
## Actual behavior
Output of what you actually see.
## Error message/stack trace
Complete error message and stack trace.
Id=1455 RUNNABLE (in native)
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:171)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1208)
    -  locked com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@488c1304
    at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:1195)
    at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1208)
    -  locked com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@29f3ccc3
    at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:1195)
    at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:476)
    at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:470)
    at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
    at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1369)
    at sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:73)
    at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:978)
    at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1208)
    -  locked com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@23a2b780
    at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:1195)
    at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2101)
    -  locked com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@23a2b780
    at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6788)
    -  locked com.microsoft.sqlserver.jdbc.TDSReader@36961244
    at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:8008)
    at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:618)
    at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:540)
    at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7620)
    at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3916)
    -  locked java.lang.Object@1a518338
    at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
    at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
    at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:486)
    at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
    at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3285)
    at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3183)
    at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3525)
    at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:159)
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:465)
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:351)
    at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)
    at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
    at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1258)
    at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:425)
    at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)
    at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:177)

## Any other details that can be helpful
we see this problem post driver upgrade from 11.2.0 to 11.2.3

## JDBC trace logs
Provide the JDBC driver trace logs.  Instructions can be found here: https://docs.microsoft.com/sql/connect/jdbc/tracing-driver-operation

**Comment by Jeffery-Wasty** [comment]
Hi @chinnusabbineni,

We have a `queryTimeout` connection property that defaults to an infinite wait, can you try setting that property? Information on our connection properties can be found [here](https://learn.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver15).

**Comment by lilgreenbird** [comment]
hi @chinnusabbineni 

Did setting the `socketTimeout` value resolve your issue?
Please let us know if you have more questions otherwise we will be closing this issue off shortly.
