### ISSUE TITLE
Using a temp table in a stored procedure fails when calling stored procedure via JDBC

### ISSUE THREAD

**Issue by StijnVdd** [microsoft/mssql-jdbc#2206]
## Driver version
12.4

## SQL Server version
Microsoft SQL Server 2019 (RTM-CU21) (KB5025808) - 15.0.4316.3 (X64)   Jun  1 2023 16:32:31   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

## Client Operating System
Windows Server 2016

## JAVA/JVM version
Java 1.8

## Table schema
Provide the table schema to repro the issue.

`
CREATE PROCEDURE [dbo].[ImportIdentifiers]
     
AS
BEGIN

        CREATE TABLE #TmpIdentifiers
        (
            identifier nvarchar(50),
            customer nvarchar(12)
        )
 
        INSERT INTO #TmpIdentifiers(identifier, customer)
 
        SELECT ie.SenderIdentifier, LEFT(e1.Name,12) FROM otherDatabase.dbo.IdentifiersToEndpoints ie
       
        -- Other logic
END
`

## Problem description

Above SP is only to demonstrate the issue and does not server a actual purpose.
When calling the SP via the SQL management studio, it is running just fine. But when calling this stored procedure via JDBC, I receive a error.

## Expected behavior
When I use the JTDS driver, this just works without any issue. I therefore expect the driver to return the same result as when calling the SP via the SQL Management studio

## Actual behavior
Error thrown

## Error message/stack trace
`SQL error while calling stored procedure "ImportEDIDeskEdifactIdentifiers": Invalid object name '#TmpIdentifiers'.
com.companyx.Exception: SQL error while calling stored procedure "ImportEDIDeskEdifactIdentifiers": Invalid object name '#TmpIdentifiers'.
	at com.companyx.operation.sql.OperationCallStoredProcedure.execute(OperationCallStoredProcedure.java:314) ~[OperationCallStoredProcedure.class:?]
	at com.companyx.operation.Pipeline.execute(Pipeline.java:101) ~[Pipeline.class:?]
	at com.companyx.integrator.monitor.MonitorThread.run(MonitorThread.java:577) [engine-5.3.14.jar!/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name '#TmpIdentifiers'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:255) ~[mssql-jdbc-12.4.0.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1695) ~[mssql-jdbc-12.4.0.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:920) ~[mssql-jdbc-12.4.0.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:814) ~[mssql-jdbc-12.4.0.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7675) ~[mssql-jdbc-12.4.0.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4137) ~[mssql-jdbc-12.4.0.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:272) ~[mssql-jdbc-12.4.0.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:246) ~[mssql-jdbc-12.4.0.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeQueryInternal(SQLServerStatement.java:743) ~[mssql-jdbc-12.4.0.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.buildExecuteMetaData(SQLServerPreparedStatement.java:1214) ~[mssql-jdbc-12.4.0.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.getMetaData(SQLServerPreparedStatement.java:1190) ~[mssql-jdbc-12.4.0.jre8.jar:?]
	at com.companyx.operation.sql.OperationCallStoredProcedure.execute(OperationCallStoredProcedure.java:164) ~[OperationCallStoredProcedure.class:?]
	... 3 more`

**Comment by lilgreenbird** [comment]
hi @StijnVdd 

could you please include the repro code you ran to repro the error?

**Comment by lilgreenbird** [comment]
closing due to inactivity, please feel free to request re-opening if you have more info
