### ISSUE TITLE
Getting Socket read timed out error after sometime when application runs after months of upgrading to 12.2 from 8.4

### ISSUE THREAD

**Issue by HarshaVardhan-Sai** [microsoft/mssql-jdbc#2278]
## Driver version
Provide the JDBC driver version (e.g. 10.2.0).  :12.2

## SQL Server version
Provide the output of executing `SELECT @@VERSION` on your target SQL Server.
SQL server 2019
## Client Operating System
Provide the Operating System the client application is running on.
Cloud and windows server 2019
## JAVA/JVM version
Provide the JAVA/JVM version (e.g. java version "1.8.0").
Java version 11.0.20
## Table schema
Provide the table schema to repro the issue.

## Problem description
Provide full details of the problem.
## Expected behavior
After updating the sql server driver to 12.2 frok 8.4 when application runs for longer time and does sql queries at sudden instances in time I am getting read time out exception for the server
## Actual behavior
I don't want to have this exception 
Output of what you actually see.
## Error message/stack trace
Complete error message and stack trace.
## JDBC trace logs
Provide the JDBC driver trace logs.  Instructions can be found here: https://docs.microsoft.com/sql/connect/jdbc/tracing-driver-operation

**Comment by lilgreenbird** [comment]
hi @HarshaVardhan-Sai 

Could you please provide more info on how you are using the driver, e.g. code to repro, connection string, error msg/call stack, and trace logs would also be helpful.

There could also be a lot of non-driver related reasons for intermittent connection failures, here is a link to our [wiki ](https://github.com/microsoft/mssql-jdbc/wiki/Troubleshooting-Intermittent-Connection-Failures)to help you with troubleshooting.

**Comment by HarshaVardhan-Sai** [comment]
We are connecting Wildfly to the database 
Connection URL will look as jdbc:sqlserver:// [SERVERNAME]\[INSTANCE NAME]:1433;encrypt=false
```
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at com.mssql//com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1193)
	at com.mssql//com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:1179)
	at com.mssql//com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2151)
```

**Comment by HarshaVardhan-Sai** [comment]
@lilgreenbird Please let me know if additional log statements are required

Thank you

**Comment by lilgreenbird** [comment]
hi @HarshaVardhan-Sai 

When does this happen during login or when you are executing queries? Is this intermittent or does this happen every time? 
Are you able to reproduce this using a standalone java program only?

It is hard to tell what the cause is since the error call stack shown only show that there was a socket read timeout but there could be a lot of reasons why that could happen.

**Comment by HarshaVardhan-Sai** [comment]
HI @lilgreenbird 

This happens during the query execution. I tried this on standalone java program. The program execution is way too slower when using the 12.2 driver. The same program with same sql statements executes much faster while using the 8.x driver.

This happens at random instances popping up this error in our server logs. The same executions are fine with the old driver. Hence for now the driver version is reverted to an older version. Please let me know if there are some additional details that I could provide you with.

**Comment by lilgreenbird** [comment]
could you please share your repro code

**Comment by HarshaVardhan-Sai** [comment]
@lilgreenbird there is nothing like repro code as this occurs while running the application. When SQL statements are executed via JDBC this is timeout error occurs at random point.
We also observe this when we try to add a column to a table having huge number of records like 1million records (when executed with jdbc connection).

**Comment by lilgreenbird** [comment]
@HarshaVardhan-Sai 

What queries are you executing? We are not aware of any decreased performance issues so there is nothing for us to go by here unless you have some specific examples of what you are doing that is exhibiting this behavior? The error stack above show that it is timing out on a socket read which could occur if the connection to the server is dropped or other network issues. You can control how long the driver will wait before the timeout occurs by specifying a value for `socketTimeout`. 

Also, version 8.x is quite an old release there had been quite a lot of changes in the driver since then . Some of the changes that could affect timing:

- default value of `loginTimeout` has been increased from 15 to 30seconds  
- [Idle Connection Resiliency ](https://learn.microsoft.com/en-us/sql/connect/jdbc/connection-resiliency?view=sql-server-ver16) feature which auto retries dropped connections. Default values are `connectRetryCount=1` and `connectRetryInterval=10`. You can disable this feature by setting `connectRetryCount=0` however unfortunately there is current an bug with this it will still attempt some retries.

You can find descriptions of all the driver connection properties in the following page:
https://learn.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver16

In addition, we also have a [wiki ](https://github.com/microsoft/mssql-jdbc/wiki/Troubleshooting-Intermittent-Connection-Failures)containing links to pages that could help you to troubleshoot intermittent connection failures.

**Comment by Jeffery-Wasty** [comment]
Hi @HarshaVardhan-Sai,

Without further activity, we'll move forward with closing the issue. Please let us know if you need more assistance around the above issue.

**Comment by HarshaVardhan-Sai** [comment]
Hello @Jeffery-Wasty  and @lilgreenbird  sorry for not checking on this following the comments above and upgrading to 12.4 driver has indeed fixed the issue of slowness. So maybe something in 12.2 was corrected with 12.4 I am not sure but its good with 12.4
