### ISSUE TITLE
[QUESTION] "Could not find prepared statement with handle 1" - probably, it was fixed?

### ISSUE THREAD

**Issue by smesh** [microsoft/mssql-jdbc#2362]
## Question

Random exception: "Could not find prepared statement with handle 1", mssql-jdbc-11.2.3.jre11.jar
Probably, it was fixed in latest versions?

Stack:
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Could not find prepared statement with handle 1.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265) ~[mssql-jdbc-11.2.3.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1676) ~[mssql-jdbc-11.2.3.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:620) ~[mssql-jdbc-11.2.3.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:540) ~[mssql-jdbc-11.2.3.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7620) ~[mssql-jdbc-11.2.3.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3916) ~[mssql-jdbc-11.2.3.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268) ~[mssql-jdbc-11.2.3.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242) ~[mssql-jdbc-11.2.3.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQueryInternal(SQLServerPreparedStatement.java:473) ~[mssql-jdbc-11.2.3.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getResultSetFromStoredProc(SQLServerDatabaseMetaData.java:360) ~[mssql-jdbc-11.2.3.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getResultSetWithProvidedColumnNames(SQLServerDatabaseMetaData.java:374) ~[mssql-jdbc-11.2.3.jre11.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getIndexInfo(SQLServerDatabaseMetaData.java:1162) ~[mssql-jdbc-11.2.3.jre11.jar:?]

**Comment by smesh** [comment]
https://github.com/microsoft/mssql-jdbc/pull/1886 - looks relevant maybe help with answer?

**Comment by bhoeferlin** [comment]
Seems not to be fixed recently - I get the same errors randomly after some time since switching from 12.4.2.jre8 to 12.6.1.jre8

com.microsoft.sqlserver.jdbc.SQLServerException: Could not find prepared statement with handle 1.
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:261)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1752)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:675)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:594)
at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7739)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4384)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:293)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:263)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:509)

**Comment by lilgreenbird** [comment]
hi @smesh

this looks like it might be related to #2356  could you please tell us what your connection string is?

**Comment by smesh** [comment]
Hi @lilgreenbird ,
Connection url is: jdbc:sqlserver://<server:port>;authentication=SqlPassword;DatabaseName=<db>;trustServerCertificate=true;SelectMethod=cursor

**Comment by lilgreenbird** [comment]
we have another issue relating to this that we are working on, we think it's related to the cache not being cleared. Can you pls try to disable prepared statement handle caching and see if that resolves your issue? if so, that's a temporary workaround for the issue for now. 

i.e. add `disableStatementPooling=false;statementPoolingCacheSize=0` to your connection string

**Comment by smesh** [comment]
> we have another issue relating to this that we are working on, we think it's related to the cache not being cleared. Can you pls try to disable prepared statement handle caching and see if that resolves your issue? if so, that's a temporary workaround for the issue for now.
> 
> i.e. add `disableStatementPooling=false;statementPoolingCacheSize=0` to your connection string

Sorry for not replying, we could not try workaround in the production.
