### ISSUE TITLE
[QUESTION]How to use kerberos authentication in JDBC on Windows

### ISSUE THREAD

**Issue by Gong-Allen** [microsoft/mssql-jdbc#2373]
## Question
I am trying to use Kerberos authentication in JDBC on Windows:
Java Version: Java 17
mssql-jdbc version: com.microsoft.sqlserver:mssql-jdbc:12.6.1.jre11

I can login successfully in Microsoft SQL Server Management Studio with Windows Authentication, but can not access database in my Java application, here is my java code:
```
public static void main(String[] args) {
        try (
                Connection connection = 
DriverManager.getConnection("jdbc:sqlserver://localhost:1433;integratedSecurity=true;authenticationScheme=JavaKerberos;encrypt=true;trustServerCertificate=true;", "", "");
                Statement statement = connection.createStatement();
                ResultSet rs = statement.executeQuery("select 'abc'")
        ){
            if(rs.next()){
                System.out.println(rs.getString(1));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
```
After I run my application on this Windows machine, I got below error:
```
**java -Dsun.security.krb5.debug=true -jar kerberos-1.0-SNAPSHOT.jar**

Java config name: null
LSA: Found Ticket
LSA: Made NewWeakGlobalRef
LSA: Found PrincipalName
LSA: Made NewWeakGlobalRef
LSA: Found EncryptionKey
LSA: Made NewWeakGlobalRef
LSA: Found TicketFlags
LSA: Made NewWeakGlobalRef
LSA: Found KerberosTime
LSA: Made NewWeakGlobalRef
LSA: Found String
LSA: Made NewWeakGlobalRef
LSA: Found Ticket constructor
LSA: Found PrincipalName constructor
LSA: Found EncryptionKey constructor
LSA: Found TicketFlags constructor
LSA: Found KerberosTime constructor
LSA: Finished OnLoad processing
Native config name: C:\Windows\krb5.ini
Loaded from native config
>>>KinitOptions cache name is C:\Users\<***>\<***>\<***>
>> Acquire default native Credentials
Using builtin default etypes for default_tkt_enctypes
default etypes for default_tkt_enctypes: 18 17 20 19.
LSA: Found KrbCreds constructor
LSA: Got handle to Kerberos package
LSA: Response size is 1843
LSA: TICKET SessionKey KeyType is 18
LSA: Valid etype found: 18
LSA: Principal domain is ***
LSA: Name type is 1
LSA: Name count is 1
LSA: Principal domain is ***
LSA: Name type is 2
LSA: Name count is 2
LSA: Session key all zero. Stop.
>>> Found no TGT's in native ccache
com.microsoft.sqlserver.jdbc.SQLServerException: Kerberos Login failed: Integrated authentication failed. ClientConnectionId:c6f18883-621c-4647-9369-adb0578b406a due to javax.security.auth.login.LoginException (Cannot get any of properties: [user, USER] from con properties not available to garner  authentication information  from the user)
        at com.microsoft.sqlserver.jdbc.KerbAuthentication.initAuthInit(KerbAuthentication.java:130)
        at com.microsoft.sqlserver.jdbc.KerbAuthentication.generateClientContext(KerbAuthentication.java:238)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6587)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:5402)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:5334)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7739)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4384)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3823)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3348)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:3179)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1953)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1263)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
        at com.mssql.Kerberos.main(Kerberos.java:8)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: javax.security.auth.login.LoginException: Cannot get any of properties: [user, USER] from con properties not available to garner  authentication information  from the user
        at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.promptForName(Krb5LoginModule.java:853)
        at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:689)
        at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:597)
        at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:679)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:677)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:677)
        at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at com.microsoft.sqlserver.jdbc.KerbAuthentication.initAuthInit(KerbAuthentication.java:107)
        ... 22 more
```
Is there any configuration I am missing? Thanks,

**Comment by tkyc** [comment]
@Gong-Allen 

Just some basic initial kerberos troubleshooting questions first.

1. Did you get a successful `kinit` to get a ticket on the client machine on the domain?

2. Was a [SPN](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections?view=sql-server-2017) properly registered on the server? You can check the error log text file in SQL Server for this. If you see `The SQL Server Network Interface library successfully registered the Service Principal Name (SPN) [ MSSQLSvc/MySqlServerHostName:1433 ] for the SQL Server service` then it's working. You can [find the error log text](https://learn.microsoft.com/en-us/sql/relational-databases/performance/view-the-sql-server-error-log-sql-server-management-studio?view=sql-server-ver16) file on SSMS in the "Object Explorer > Management > SQL Server Logs".

If the above 2 points are working for you, then maybe for some reason it can't find the ticket cache. Then you can try explicitly setting the path to the ticket using the `KRB5CCNAME` environment variable.

**Comment by tkyc** [comment]
Also, incase you haven't seen this yet. We have a doc for using the driver with kerberos found here:

https://learn.microsoft.com/en-us/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server?view=sql-server-ver16

**Comment by Gong-Allen** [comment]
Hi @tkyc ,
Thanks for your information, after I call the kinit.exe under the bin folder of my JRE, I can connection to SQL Server with Kerberos authentication successfully, but here comes a question for me: is the manual calling  ***kinit*** a mandatory step? My application would be a windows backend service and there is no user interaction, in this case is it possible to use kerberos authentication?

**Comment by tkyc** [comment]
@Gong-Allen 

>  is the manual calling kinit a mandatory step? My application would be a windows backend service and there is no user interaction, in this case is it possible to use kerberos authentication?

I'm not an expert on kerberos and and vaguely recall this (and I can't say for sure if this is appropriate, so you'll need to do more research), but I believe you'll need a kerberos keytab file which can be used to get a ticket without entering a password. Then you can schedule some sort of cron to run the `kinit` with the keytab file to renew.

I'm sure there are better and more appropriate ways to do this, but this was my immediate thought.

**Comment by Gong-Allen** [comment]
Hi @tkyc ,
Would you please tell me how to use the kerberos keytab file? Is there any document for it? Thanks.

**Comment by tkyc** [comment]
@Gong-Allen 

Personally I don't recall exactly how, but you can refer to this relevant doc here:

https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/ktpass

**Comment by lilgreenbird** [comment]
hi @Gong-Allen 

As @tkyc mentioned we are not experts in Kerberos nor can we provide any support on how to setup Kerberos in your environment. We can only offer you support on issues on our driver only.  As @tkyc mentioned you will have to verify that your Kerberos environment is setup correctly before you can successfully use the driver.

**Comment by Gong-Allen** [comment]
Hi @lilgreenbird  
Thanks for your clarification, I will close this question.
