### ISSUE TITLE
[QUESTION] How to pass MAXDOP option

### ISSUE THREAD

**Issue by guoliqiang** [microsoft/mssql-jdbc#2395]
Looks like this JDBC lib does not pass MAXDOP option.

spark.read()
                .format("jdbc")
                .option("driver","com.microsoft.sqlserver.jdbc.SQLServerDriver")
                .option("url", "jdbc:sqlserver://xxx.database.windows.net;databaseName=xxxx")
                .option("query", "SELECT TOP 10 * FROM dbo.Demo with (nolock) WHERE Id = 1 option (maxdop 1)")
                .load()
                .show();

com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'option'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:270)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1778)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:697)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:616)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7775)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4397)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:293)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:263)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:531)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:61)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRelation$.getSchema(JDBCRelation.scala:226)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:35)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:344)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:297)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:286)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:286)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:221)

how to make it work? is there any work around. thank you.

**Comment by guoliqiang** [comment]
Thanks for your reply, asked same question to spark community.

**Comment by Jeffery-Wasty** [comment]
Hi @guoliqiang,

Given the above, this appears to be an issue from the Spark side, and not an issue with the JDBC driver. As such, we'll be closing the issue. If you receive any new information pointing towards this being a JDBC issue, please feel free to comment below and we can re-open this issue for discussion.

**Comment by guoliqiang** [comment]
Thanks @Jeffery-Wasty. I did not get any clear suggestion from spark community. I implement a custom spark connector on top of this JDBC lib based on my needs.

**Comment by Jeffery-Wasty** [comment]
Hi @guoliqiang,

Unfortunately, we are only able to provide assistance with the JDBC driver, which we've shown above is able to parse `option (maxdop` correctly. 

Our suggestions at this point are either:

- remove this custom Spark connector as it appears to be the issue with MAXDOP, 
- try using a different query, without MAXDOP, to achieve your desired output, or 
- find Spark-related help from another source.
