### ISSUE TITLE
Error While Executing Query With CROSS APPLY STRING_SPLIT

### ISSUE THREAD

**Issue by oguzhantortop** [microsoft/mssql-jdbc#2567]
## Driver version
Provide the JDBC driver version (e.g. 10.2.0).
mssql-jdbc-12.8.0.jre11.jar
## SQL Server version
Provide the output of executing `SELECT @@VERSION` on your target SQL Server.
Microsoft SQL Server 2022 (RTM-CU16) (KB5048033) - 16.0.4165.4 (X64) 
	Nov  6 2024 19:24:49 
	Copyright (C) 2022 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 22.04.5 LTS) <X64>
## Client Operating System
Provide the Operating System the client application is running on.
OSX AND LINUX
## JAVA/JVM version
Provide the JAVA/JVM version (e.g. java version "1.8.0").
JRE 11
## Table schema
Provide the table schema to repro the issue.

## Problem description
Provide full details of the problem.
select a.val from dbo."BURCU_MAIL" a CROSS APPLY STRING_SPLIT(a.TO, '@') WHEN YOU TRY TO EXECUTE ANY QUERY LIKE THIS YOU GET AN ERROR. When you use table column as STRING_SPLIT functions first parameter causes this problem if a static string used instead of column reference it doesn't give any error.

## Expected behavior
It's a valid query and should work.
## Actual behavior
Output of what you actually see.
SQL Error [156] [S0001]: Incorrect syntax near the keyword 'TO'.
## Error message/stack trace
Complete error message and stack trace.
## Any other details that can be helpful
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [156] [S0001]: Incorrect syntax near the keyword 'TO'.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:631)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$2(SQLQueryJob.java:522)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:192)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:541)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:1016)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4273)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:128)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:192)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:126)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5166)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:119)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'TO'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:270)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1778)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:946)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:840)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7775)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4408)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:293)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:263)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:813)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:344)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:128)
	... 12 more
## JDBC trace logs
Provide the JDBC driver trace logs.  Instructions can be found here: https://docs.microsoft.com/sql/connect/jdbc/tracing-driver-operation

**Comment by oguzhantortop** [comment]
Hi Machavan,
Thank you for the information. The error message led me to think that it was a driver-related issue.
