### ISSUE TITLE
ActiveDirectory based login is broken

### ISSUE THREAD

**Issue by davidkarlsen** [microsoft/mssql-jdbc#2570]
## Driver version
mssql-jdbc-12.6.3.jre11.jar

## SQL Server version
N/A

## Client Operating System
N/A

## JAVA/JVM version
OpenJDK Runtime Environment Temurin-17.0.13+11 (build 17.0.13+11)

## Table schema
N/A

## Problem description

Use the script at https://github.com/davidkarlsen/flyway-db2, msal-test.sh , giving it an argument of a hostname of an sql-server
There is no magic mix of msal, identity, or whatever convoluted non-documented library that will work, it will fail at the missing method com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder.logPii(boolean)

Provide full details of the problem.
## Expected behavior
Entra-based auth should work.

## Actual behavior
Output of what you actually see.
## Error message/stack trace
```
ee release notes here: https://rd.gt/416ObMi
Exception in thread "main" java.lang.NoSuchMethodError: 'com.microsoft.aad.msal4j.AbstractClientApplicationBase$Builder com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder.logPii(boolean)'
        at com.azure.identity.implementation.IdentityClientBase.getConfidentialClient(IdentityClientBase.java:242)
        at com.azure.identity.implementation.IdentityClient.lambda$getConfidentialClientApplication$5(IdentityClient.java:152)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:45)
        at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4476)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:427)
        at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:335)
        at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:294)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:201)
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:83)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4491)
        at reactor.core.publisher.Mono.blockOptional(Mono.java:1786)
        at com.microsoft.sqlserver.jdbc.SQLServerSecurityUtility.getDefaultAzureCredAuthToken(SQLServerSecurityUtility.java:466)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.getFedAuthToken(SQLServerConnection.java:6179)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:5995)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:5829)
        at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:335)
        at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:130)
        at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:42)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6888)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:5434)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:5366)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7745)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4391)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3828)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3385)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:3194)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1971)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1263)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:275)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:240)
        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:59)
        at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:76)
```

## JDBC trace logs
Provide the JDBC driver trace logs.  Instructions can be found here: https://docs.microsoft.com/sql/connect/jdbc/tracing-driver-operation

**Comment by machavan** [comment]
With mssql-jdbc-12.6.3.jre11.jar, azure-identity-1.12.2, JRE17

```
    <dependency>
       <groupId>com.microsoft.sqlserver</groupId>
       <artifactId>mssql-jdbc</artifactId>
       <version>12.6.3.jre11</version>
    </dependency>

    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.12.2</version>
    </dependency>
```

Based on the stack trace above which is for ActiveDirectoryDefault authentication method, a sample application `did not run into the issue` mentioned above 

```
Exception in thread "main" java.lang.NoSuchMethodError: 'com.microsoft.aad.msal4j.AbstractClientApplicationBase$Builder com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder.logPii(boolean)'
```

Sample app
```
        ds.setServerName("yourdb.database.windows.net"); // Replace with your server name
        ds.setDatabaseName("yourdb"); // Replace with your database name
        ds.setAuthentication("ActiveDirectoryDefault");

        try (Connection connection = ds.getConnection();
                Statement stmt = connection.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT SUSER_SNAME()")) {
            if (rs.next()) {
                System.out.println("You have successfully logged on as: " + rs.getString(1));
            }
        }
```

References:

https://learn.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver16#connect-using-activedirectorydefault-authentication-mode

https://learn.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver16#client-setup-requirements


Can you help us understand further and be able to reproduce the issue you are hitting?

**Comment by davidkarlsen** [comment]
Sorry for the noise - it is the base-image that was broken.
