### ISSUE TITLE
A processing error "Invalid object name '#T'." 

### ISSUE THREAD

**Issue by rodlogic** [Microsoft/mssql-jdbc#309]
I am using 6.1.4.jre8-preview and getting the following exception:
```
2017-05-23 10:43:05.397 |-WARN  [] - Could not set query parameters: com.microsoft.sqlserver.jdbc.SQLServerException: A processing error "Invalid object name '#T'." occurred.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:227)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.buildExecuteMetaData(SQLServerPreparedStatement.java:832)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.getMetaData(SQLServerPreparedStatement.java:796)
```

When executing a SP that creates a #T table:
```
CREATE TABLE #T (Role NVARCHAR(50), SortOrder INT)
```

Note: this works using the non open source driver.

**Comment by v-suhame** [comment]
@rodlogic I tried to reproduce the exception based on details you shared. I was able to create local temp table with 6.1.4.jre8-preview successfully. Can you share a repo code so we can investigate further?

**Comment by rodlogic** [comment]
Here is a simple procedure that renders the error:
```
CREATE DATABASE test;
USE [test];
CREATE PROCEDURE test @id int
AS
    SET NOCOUNT ON
    CREATE TABLE #T (Role NVARCHAR(50), SortOrder INT)
    INSERT INTO #T(Role,SortOrder) VALUES('john',2)
    INSERT INTO #T(Role,SortOrder) VALUES('jen',1)
    INSERT INTO #T(Role,SortOrder) VALUES('jil',3)
    SELECT * FROM #T WHERE SortOrder = @id;
```

**Comment by v-suhame** [comment]
Thanks for the details! I'm able to reproduce the exception, but it's thrown by all versions of driver ([oldest ](https://docs.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server) to [latest](https://www.microsoft.com/en-ca/download/details.aspx?id=11774), as far as I tested). 
Can you try running it again and share the driver version that works?

**Comment by rodlogic** [comment]
The thing is none worked. Not even the non-open source driver by Microsoft. So this seems to be a compatibility issue between the native drivers and the JDBC one as far as I can tell.

**Comment by v-suhame** [comment]
Okay! since 'Note' in first comment said it 'works', needed some clarification.
We will mark it for future enhancement. Thanks for raising this issue!

**Comment by v-suhame** [comment]
Fixing #244 should fix this too.

**Comment by v-nisidh** [comment]
connect to #313

**Comment by v-xiangs** [comment]
Hello @rodlogic , thank you for opening the issue. In order to help you, I need some more clarification from you.

Is the exception ```A processing error "Invalid object name '#T'." occurred``` thrown when you call `SQLServerCallableStatement.getMetaData()`? If yes, I believe this error message is proper and expected.

By adding hash(#) in front of a table name, it means the table is a temporary table that's dropped automatically by SQL Server. 

If you called  before calling `SQLServerCallableStatement.getMetaData()`, the table is created. Furthermore, calling `SQLServerCallableStatement.getMetaData()` does not execute the stored procedure you created, so calling `SQLServerCallableStatement.getMetaData()` on the stored procedure does not create table.

Calling `SQLServerCallableStatement.execute()` on the stored procedure actually executes the stored procedure, therefore creates the table;
Calling `SQLServerCallableStatement.getMetaData()` does not execute the stored procedure, so calling `SQLServerCallableStatement.getMetaData()` on the stored procedure does not create the table.

If you called `SQLServerCallableStatement.execute()` first and the table is not temporary table (without #), the table stays in DB and no exception when calling  `SQLServerCallableStatement.getMetaData()`. However, if the table is temporary table (with #), it is dropped automatically after calling `SQLServerCallableStatement.execute()`. That's why we see the exception, because the table does not exist in the DB and `SQLServerCallableStatement.getMetaData()` does not create the table.

**Comment by v-xiangs** [comment]
Hello @rodlogic , did I explain it clearly? Please let me know if you have any questions :)

**Comment by ajlam** [comment]
Closing issue due to inactivity. Please open again if required.
