### ISSUE TITLE
TVP doesn't work on stored procs returning result sets

### ISSUE THREAD

**Issue by cogman** [Microsoft/mssql-jdbc#411]
## Driver version or jar name
6.2.0

## SQL Server version
Sql Server 2014

## Client operating system
Windows

## Java/JVM version
1.8.0_111

## Table schema
```
CREATE TYPE Foo AS TABLE
(val INT)
GO

CREATE PROCEDURE Bar
(@myFoo Foo READONLY)
AS
	SELECT * FROM @myFoo
GO
```

## Problem description
I receive the following exception when I try to call a stored procedure with a TVP that returns result sets.

```
com.microsoft.sqlserver.jdbc.SQLServerException: A metadata error for the parameter {0} occurred.
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.getTVPNameIfNull(SQLServerPreparedStatement.java:2356)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.setObjectNoType(SQLServerPreparedStatement.java:1649)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.setObject(SQLServerPreparedStatement.java:1673)
	at com.zaxxer.hikari.pool.HikariProxyCallableStatement.setObject(HikariProxyCallableStatement.java)
	at fooTest
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: com.microsoft.sqlserver.jdbc.SQLServerException: The parameter number 1 is not valid.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:227)
	at com.microsoft.sqlserver.jdbc.SQLServerParameterMetaData.getParameterTypeName(SQLServerParameterMetaData.java:775)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.getTVPNameIfNull(SQLServerPreparedStatement.java:2345)
	... 11 more
```

## Expected behavior and actual behavior
No exception to happen

## Repro code
```
	public void fooTest(DataSource ds)
	{
		try(Connection conn = ds.getConnection();
			CallableStatement stmt = conn.prepareCall("{call Bar(?)}"))
		{
			int val = 12345;
			SQLServerDataTable param = new SQLServerDataTable();
			param.setTvpName("[dbo].[Foo]");
			param.addColumnMetadata("val", Types.INTEGER);
			param.addRow(val);

			stmt.setObject(1, param);

			boolean execute = stmt.execute();
			if (execute)
			{
				try(ResultSet rs = stmt.getResultSet())
				{
					int dbVal = rs.getInt("val");
					assert val == dbVal;
				}
			}
		}
		catch(SQLException ex)
		{
			LOG.error("bad stuff happened", ex);
			System.exit(-1);
		}
	}
```

I suspect that this line in SQLServerParameterMetaData
` if (((SQLServerPreparedStatement) stmtParent).bReturnValueSyntax && isTVP) {`
Should be an || instead of an &&.  But I'm less familiar with what bReturnValueSyntax actually means in context here.

**Comment by cogman** [comment]
Arg.

Turns out you need to have execute permissions on the type you are trying to use.  This is my mistake.
