### ISSUE TITLE
SQL Server did not return a response. The connection has been closed.

### ISSUE THREAD

**Issue by vishal98** [Microsoft/mssql-jdbc#414]
## Driver version or jar name
mssql-jdbc-6.2.1.jre8

## SQL Server version
2008 r3

## Client operating system
windows

## Java/JVM version
Example: java version "1.8.0_65

## Problem description
We are getting connection close error when we are access any table from database.
 After obtaining the successful connection to the mssql server ,when tried to execute the query ,the server is throwing below exception.

 com.microsoft.sqlserver.jdbc.SQLServerException: SQL Server did not return a response. The connection has been closed.
 at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2435)
 at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2423)
 at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6315)
 at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7545)
 at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:843)
 at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:752)
 at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7151)
 at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2478)
 at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:219)
 at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:199)
 at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeQuery(SQLServerStatement.java:654)

## Expected behavior and actual behavior
We should be able to fetch data

## Repro code
Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
  url=jdbc:sqlserver://localhost:1433;databaseName=table;encrypt=true;trustServerCertificate=true;
  Connection connection =DriverManager.getConnection(url, "dummy","dummypwd"); 
    Statement stmt =  connection.createStatement();
 String    query="SELECT local_tcp_port FROM sys.dm_exec_connections WHERE session_id=@@SPID";
ResultSet   resultSet =      stmt.executeQuery(query);

**Comment by v-afrafi** [comment]
Hi @vishal98 
We were not able to reproduce the issue. Could you make sure that the TCP/IP is enabled and your using the right port? Thanks,

**Comment by nsidhaye** [comment]
@vishal98 : Which version of windows installed?

In case of Windows 10, for very 1st time we need to enable TCP/IP.

**Comment by cheenamalhotra** [comment]
Hi @vishal98 Can you try testing with Prepared Statement and confirm if error exists?

**Comment by vishal98** [comment]
issue was fixed after adding Setting the -Djsse.enableCBCProtection=false in system variable
server contain self signed certificate with force ssl .

**Comment by kyriehan89** [comment]
@vishal98 : do you have email address? can you provide detail step by step to resolve this?
I have same issue 

Thanks

**Comment by Akila94** [comment]
I have the problem too, greatly appreciate if someone could explain how solve this in detail. Thanks.

**Comment by victorpalmeida** [comment]
Hi, I was facing the same issue when using IBM JDK 8 since it was using TLSv1 connecting to a MS SQL Server installed on Win2019 which was enforcing TLSv1.2. I solved the problem by setting this property at JVM level: 
**-Dcom.ibm.jsse2.overrideDefaultTLS=true**. The SQL jdbc driver version used was v12.2 jre8.
