### ISSUE TITLE
Incorrect syntax near '@P0'

### ISSUE THREAD

**Issue by mobilars** [Microsoft/mssql-jdbc#49]
I'm using MS SQL 2016 (express), with a Java-based application using the following mvn reference to this library:

`<dependency>
			<groupId>com.microsoft.sqlserver</groupId>
			<artifactId>mssql-jdbc</artifactId>
			<version>6.1.0.jre8</version>
</dependency>`

And I'm using the following MS-specific Hibernate settings:

String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=fhir;user=fhir;password=xxx";
retVal.setDriver(new com.microsoft.sqlserver.jdbc.SQLServerDriver());
retVal.setUrl(connectionUrl);
retVal.setUsername("fhir");
retVal.setPassword("xxx");
...
//extraProperties.put("hibernate.dialect", org.hibernate.dialect.SQLServer2012Dialect.class.getName());
extraProperties.put("hibernate.dialect", org.hibernate.dialect.SQLServerDialect.class.getName());

I'm using 5.1.0.Final Hibernate. 

The server I'm using is HAPI-FHIR (but I'm guessing that doesn't really matter, as it works towards many other database types. When 'downgrading' my db server to 2012-compatibility and using the 2012 dialect (as commented out above) in my Java code, everything works. But when I use 2016 or 2014 MS SQL together with dialect = org.hibernate.dialect.SQLServerDialect, I get the error below. Any idea what could be wrong??? The code with the 2012-mods is available on https://bitbucket.org/ehelse/hapi-v2

I'm getting the following exception:

62 [scheduledExecutorService-2] WARN  o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:129] SQL Error: 102, SQLState: S0001
2016-12-01 13:22:47.363 [scheduledExecutorService-2] ERROR o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:131] Incorrect syntax near '@P0'.
2016-12-01 13:22:47.367 [scheduledExecutorService-2] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler [TaskUtils.java:95] Unexpected error occurred in scheduled task.
javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1692)
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1602)
        at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:492)
        at ca.uhn.fhir.jpa.dao.BaseHapiFhirSystemDao$1.doInTransaction(BaseHapiFhirSystemDao.java:105)
        at ca.uhn.fhir.jpa.dao.BaseHapiFhirSystemDao$1.doInTransaction(BaseHapiFhirSystemDao.java:93)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at ca.uhn.fhir.jpa.dao.BaseHapiFhirSystemDao.doPerformReindexingPassForResources(BaseHapiFhirSystemDao.java:93)
        at ca.uhn.fhir.jpa.dao.BaseHapiFhirSystemDao.doPerformReindexingPass(BaseHapiFhirSystemDao.java:88)
        at ca.uhn.fhir.jpa.dao.BaseHapiFhirSystemDao.performReindexingPass(BaseHapiFhirSystemDao.java:273)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy121.performReindexingPass(Unknown Source)
        at ca.uhn.fhir.jpa.dao.FhirResourceDaoSearchParameterDstu2.performReindexingPass(FhirResourceDaoSearchParameterDstu2.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:106)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:79)
        at org.hibernate.loader.Loader.getResultSet(Loader.java:2115)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1898)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1874)
        at org.hibernate.loader.Loader.doQuery(Loader.java:919)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)
        at org.hibernate.loader.Loader.doList(Loader.java:2610)
        at org.hibernate.loader.Loader.doList(Loader.java:2593)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2422)
        at org.hibernate.loader.Loader.list(Loader.java:2417)
        at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:501)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:371)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1339)
        at org.hibernate.internal.QueryImpl.list(QueryImpl.java:87)
        at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:606)
        at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:483)
        ... 33 common frames omitted
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near '@P0'.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:232)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1672)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:460)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:405)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7535)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2438)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:208)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:183)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:317)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:83)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:83)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:70)
        ... 49 common frames omitted

Here is some SQL-logging that I think may be related:

Hibernate:
    select
        subscripti0_.PID as col_0_0_
    from
        HFJ_SUBSCRIPTION subscripti0_
    where
        subscripti0_.SUBSCRIPTION_STATUS=?
        and subscripti0_.NEXT_CHECK<=?
Hibernate:
    select
        search0_.PID as PID1_6_,
        search0_.CREATED as CREATED2_6_,
        search0_.LAST_UPDATED_HIGH as LAST_UPD3_6_,
        search0_.LAST_UPDATED_LOW as LAST_UPD4_6_,
        search0_.PREFERRED_PAGE_SIZE as PREFERRE5_6_,
        search0_.RESOURCE_ID as RESOURCE6_6_,
        search0_.RESOURCE_TYPE as RESOURCE7_6_,
        search0_.SEARCH_TYPE as SEARCH_T8_6_,
        search0_.TOTAL_COUNT as TOTAL_CO9_6_,
        search0_.SEARCH_UUID as SEARCH_10_6_
    from
        HFJ_SEARCH search0_
    where
        search0_.CREATED<?
Hibernate:
    select
        count(termconcep0_.PID) as col_0_0_
    from
        TRM_CONCEPT termconcep0_
    where
        termconcep0_.INDEX_STATUS is null

**Comment by v-nisidh** [comment]
Thanks @mobilars for reaching out to us. As per my understanding **`SQLServer2012Dialect` is the latest & greatest Dialect** provided by Hibernate team. `SQLServerDialect` is very old for Microsoft SQL Server 2000. 

Please refer [SQLServerDialect.java](https://github.com/hibernate/hibernate-orm/blob/5.1/hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java) and [SQLServer2012Dialect.java](https://github.com/hibernate/hibernate-orm/blob/5.1/hibernate-core/src/main/java/org/hibernate/dialect/SQLServer2012Dialect.java)

**Comment by mobilars** [comment]
OK, that answers it. I'm not quite sure if I need the 2016-version of MS SQL. I'll find out. For now 2012 will probably work fine as you say. 

Thank you for your swift response. Closing the issue. 

Best regards,
Lars

**Comment by lauyaun** [comment]
very nice. thank you

**Comment by ui2henry** [comment]
very nice. thank you
