### ISSUE TITLE
The conversion from int to TIMESTAMP is unsupported

### ISSUE THREAD

**Issue by phaninra** [Microsoft/mssql-jdbc#512]
## Driver version or jar name
6.2.1.jre7

## SQL Server version
2016

## Client operating system
Windows

## Java/JVM version
1.8.0_121

## Table schema
Culprit column is `[datetime] NULL`

## Problem description
I'm suing using Hibernate 3.6.10.Final and jTDS. I'm working on migrating to mssql-jdbc driver.
The exception `The conversion from int to TIMESTAMP is unsupported` is being thrown when trying to load the entity. The value for the column in the db is null whose dataytpe is `datetime` and the Java-side type is `java.sql.Timestamp`.

```com.microsoft.sqlserver.jdbc.SQLServerException: The conversion from int to TIMESTAMP is unsupported.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:227)
	at com.microsoft.sqlserver.jdbc.DataTypes.throwConversionError(DataTypes.java:1612)
	at com.microsoft.sqlserver.jdbc.ServerDTVImpl.getValue(dtv.java:3779)
	at com.microsoft.sqlserver.jdbc.DTV.getValue(dtv.java:286)
	at com.microsoft.sqlserver.jdbc.Column.getValue(Column.java:189)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getValue(SQLServerResultSet.java:1925)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getValue(SQLServerResultSet.java:1906)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getTimestamp(SQLServerResultSet.java:2332)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getTimestamp(NewProxyResultSet.java:3222)
	at org.hibernate.type.descriptor.sql.TimestampTypeDescriptor$2.doExtract(TimestampTypeDescriptor.java:62)
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:64)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:254)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:250)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:230)
	at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:331)
	at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:2283)
	at org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1527)
	at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1455)
	at org.hibernate.loader.Loader.getRow(Loader.java:1355)
	at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:611)
	at org.hibernate.loader.Loader.doQuery(Loader.java:829)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:274)
	at org.hibernate.loader.Loader.doList(Loader.java:2542)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2276)
	at org.hibernate.loader.Loader.list(Loader.java:2271)
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:316)
	at org.hibernate.impl.StatelessSessionImpl.listCustomQuery(StatelessSessionImpl.java:614)
	at org.hibernate.impl.AbstractSessionImpl.list(AbstractSessionImpl.java:165)
	at org.hibernate.impl.SQLQueryImpl.list(SQLQueryImpl.java:157)```

## Expected behavior and actual behavior
Expected: The value on the Java-side should be null.
Actual: Failure due to an exception.

Thanks.

**Comment by v-afrafi** [comment]
Hi @phaninra . From the stack trace you provided, it looks like your framework is using getTimestamp() to retrieve the value. The jar version that you are using (6.2.1.jre7) already supports calling getTimestamp on columns containing null values. However, we had a fix for this [issue](https://github.com/Microsoft/mssql-jdbc/issues/482) in the latest preview release (6.3.3.jre7-preview) that supports calling any getters on null columns. Could you please try the latest jars and see if your issue is resolved? Thanks.

**Comment by phaninra** [comment]
@v-afrafi 

Excellent, `6.3.3.jre7-preview` works. Any ETA on a non-beta version? Is this `preview` version production ready? Thanks.

**Comment by David-Engel** [comment]
@phaninra,
Thanks for verifying it!

We do not recommend preview releases for production use. For non-preview releases which we officially support in production environments, our goal is to release twice a year. Since the last stable release was June 30, the next one will likely be near the beginning of 2018.
