### ISSUE TITLE
connection reset on some of  the request

### ISSUE THREAD

**Issue by vishal98** [Microsoft/mssql-jdbc#588]
## Driver version or jar name
6.3.0.jre8-preview

## SQL Server version
V12 (azure sqlserver database)
## Client operating system
azure

## Java/JVM version
java 1_8_065

## Table schema
NA 

## Problem description
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
        at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream.writeIntern                                                                                        al(IOBuffer.java:1109)
        at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream.write(IOBuf                                                                                        fer.java:1100)
        at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431)
        at sun.security.ssl.OutputRecord.write(OutputRecord.java:417)
        at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java                                                                                        :876)
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:847)
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
        at com.microsoft.sqlserver.jdbc.TDSChannel.write(IOBuffer.java:2005)
        ... 83 more

## Expected behavior and actual behavior
all the procedures should be properly executed.

## Repro code
issue is coming while executing procedures

**Comment by cheenamalhotra** [comment]
Hi @vishal98 

To be able to assist you on this, please provide us detailed info about which procedures are failing on execution or any repro code to be able to reproduce the issue at our end. 

Also let us know which Azure VM you are using for Client machine and that if this issue is recurring/intermittent.

**Comment by vishal98** [comment]
we are getting this issue when we are running around 20 procedures simultaneously.this is happening on client m/c so we are not able to access logs.This is a recurring issue but not consistent.

**Comment by cheenamalhotra** [comment]
Hi @vishal98 

Without detailed information, I can't say much why this issue is happening. Looking at the error log, it seems that OutputRecord is not completely written when the socket connection got closed. Does your application override "socketTimeout" on connection property? If not, then the default value is 0 that supports infinite timeout on socket and this error should not occur in this case.

Possible reason this could happen is if there are network issues between Azure VM and Azure SQL database. I would recommend testing the same application in a different environment, possibly on the same machine where SQL Server (on-premise) is installed and then execute the same procedures in a stress test run. If you still find issues, we can trace down by studying the procedure definitions, but there is a high chance this issue won't occur in a local environment.

Please let me know on your findings.

**Comment by cheenamalhotra** [comment]
Closing issue as its not reproducible and not enough details available.

**Comment by adrian-ionescu** [comment]
We're also hitting this exact same stack trace occasionally and also lack a reliable way of reproducing it.

@vishal98, did you manage to solve / work around this problem in the meantime?

**Comment by andydkelly-ig** [comment]
@adrian-ionescu did you ever resolve your issue. I experienced something similar when trying to update many databases via Liquibase from VSTS. If i ran identical script against 50 databases 2 or 3 would always fail (always different). I resolved this by increasing the timeout from 30s to 90s in the JDBC connection string.

**Comment by adrian-ionescu** [comment]
@andydkelly-ig, no we still haven't gotten to the bottom of this. We worked around it via retries on our side, but your solution sounds cleaner - thanks!

**Comment by andydkelly-ig** [comment]
@adrian-ionescu i need to prove it out more, but so far i'm yet to see the failure after numerous runs and prior to changing the setting i only achieved a single clean run from about 100
