### ISSUE TITLE
[Azure SQL] JDBC fails to convert queries to Always Encrypted queries

### ISSUE THREAD

**Issue by helderribeirosousa** [Microsoft/mssql-jdbc#625]
## Driver version or jar name
mssql-jdbc-6.2.2.jre8.jar

## SQL Server version
Azure SQL Database V12

## Client operating system
macOS High Sierra 10.13.3

## Java/JVM version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

## Table schema
This a simple test table containing three attributes, where two of them are encrypted using the Always Encrypted feature.

 id -> uniqueidentifier -> PRIMARY KEY (DEFAULT value is 'newid()' ) -> PLAINTEXT
fullName -> nchar(200) (NOT NULL) -> DETERMINISTIC ENCRYPTION
jsonData -> nvarchar(MAX) (NOT NULL) -> RANDOMIZED ENCRYPTION

## Problem description
Based on [this information](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-always-encrypted-with-the-jdbc-driver#errors-due-to-passing-plaintext-instead-of-encrypted-values) i assume JDBC does not convert my queries to Always Encrypted queries.
I've followed [this documentation](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-always-encrypted-with-the-jdbc-driver) thoroughly, specially [this part](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-always-encrypted-with-the-jdbc-driver#using-java-key-store-provider) and everything went ok (master key generation, column key generation, etc.). The configuration through SQL Server Management studio was relatively simple and effortless.
The problem now is that JDBC is not converting my queries to always encrypted.
Here's my connection string:

> "jdbc:sqlserver://my-azure-sql-instance.database.windows.net:1433;" +
                                                    "database=my_test_db;"+
                                                    "user=my_user;"+
                                                    "password=my_password;"+
                                                    "encrypt=true;"+
                                                    "columnEncryptionSetting=Enabled;" +
                                                    "keyStoreAuthentication=JavaKeyStorePassword;"+
                                                    "keyStoreLocation=/full/path/to/keystore.pfx;"+
                                                    "keyStoreSecret=my_key_store_password;"+
                                                    "trustServerCertificate=false;"+
                                                    "hostNameInCertificate=*.database.windows.net;"+
                                                    "loginTimeout=10;"

For instance, when i run and insert query (since my table has no rows) i get the following exception (see repro code):

> Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: Operand type clash: varchar is incompatible with varchar(8000) encrypted with (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'MyColEncKey', column_encryption_key_database_name = 'my_test_db') collation_name = 'SQL_Latin1_General_CP1_CI_AS'
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:258)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1535)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:467)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:409)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7151)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2478)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:219)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:199)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:393)
	at my.package.Main.main(Main.java:37)

Process finished with exit code 1

## Expected behavior and actual behavior
I would expect the query to be converted to the corresponding Always Encrypted query.
According to the documentation the query values are being send in plaintext.

## Repro code
https://pastebin.com/MrT5VYgj

**Comment by ivoribeiro** [comment]
+1

**Comment by ulvii** [comment]
Hi @helderribeirosousa ,

The applications are required to use parametrized queries when sending values to encrypted columns.  From the [documentation](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-always-encrypted-with-the-jdbc-driver#inserting-data-example) you mentioned above: 

> The values inserted into database columns, including the encrypted columns, are passed as parameters using SQLServerPreparedStatement. While using parameters is optional when sending values to non-encrypted columns (although, it is highly recommended because it helps prevent SQL injection), it is required for values targeting encrypted columns. If the values inserted in the encrypted columns were passed as literals embedded in the query statement, the query would fail because the Microsoft JDBC Driver for SQL Server would not be able to determine the values in the target encrypted columns, so it would not encrypt the values. As a result, the server would reject them as incompatible with the encrypted columns.

Please let me know if you have any other questions.

**Comment by helderribeirosousa** [comment]
Hello @ulvii. Thank you.

Unfortunately, while the values being sent by the jdbc driver are now being encrypted, i'm still not able to perform that insert operation successfully.

It seems like there's some issue with attribute collation. Here the exception i'm getting now:

> Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: Operand type clash: varchar(8) encrypted with (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'MyColEncKey', column_encryption_key_database_name = 'my_test_db') collation_name = 'SQL_Latin1_General_CP1_CI_AS' is incompatible with nchar(20) encrypted with (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'MyColEncKey', column_encryption_key_database_name = 'my_test_db')
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:258)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1535)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:467)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:409)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7151)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2478)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:219)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:199)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQueryInternal(SQLServerPreparedStatement.java:344)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.getParameterEncryptionMetadata(SQLServerPreparedStatement.java:695)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:447)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:409)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7151)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2478)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:219)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:199)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:356)
	at my.package.Main.main(Main.java:32)

I changed the insert part of the original code to this:
https://pastebin.com/e7MCuDHQ

**Comment by ulvii** [comment]
Hi @helderribeirosousa ,

`setNString()` method should be used for `NCHAR`, `NVARCHAR`, `NTEXT`, and `XML` data types. Please see [this page](https://docs.microsoft.com/en-us/sql/connect/jdbc/reference/setnstring-method-int-java-lang-string) for documentation.

**Comment by helderribeirosousa** [comment]
@ulvii 
I was finally able to perform select/insert operations. 
I'm experienced with crypto and Java, not so much with JDBC. 
While i was able to understand clearly how the key generation and export worked, with JDBC i guess just needed a little more detailed documentation.

I'm glad you were to help. Thank you!
