### ISSUE TITLE
Thread stuck infinite while closing result set [locked] ,infinite loop when closing ResultSet, pegged CPU

### ISSUE THREAD

**Issue by manu9729** [Microsoft/mssql-jdbc#668]
## Driver version or jar name
Please tell us what the JDBC driver version or jar name is. sqljdbc 6.2.0

## SQL Server version
Please tell us what the SQL Server version is.SQL server  2016

## Client operating system
Please tell us what oprating system the client program is running on. centos

## Java/JVM version
Example: java version "1.8.0", IBM J9 VM java 1.8.65

## Table schema
Please tell us the table schema 

## Problem description
Please share more details with us.
BLOCKING QUERY IN MSSQL DUE TO DRIVER

## Expected behavior and actual behavior
Please tell us what should happen and what happened instead
EXPECTED BEHAVIOUR QUERY SHOULD NOT BE IN RUNNING STATE AND BLOCKING BLOCKING OTHERS BUT IT NOT ABLE TO RELEASE THE RESOURDE

## Repro code
Please share repro code with us, or tell us how to reproduce the issue.

NO REPO 

"http-bio-8086-exec-68" #227 daemon prio=5 os_prio=0 tid=0x00007f42f00d9000 nid=0x90dd runnable [0x00007f42c797e000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:1981)
	at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6310)
	- locked <0x00000000be1d0bb0> (a com.microsoft.sqlserver.jdbc.TDSReader)
	at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7545)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:526)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:461)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7151)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2689)
	- locked <0x00000000b014c598> (a java.lang.Object)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:224)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:204)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:445)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.execute(NewProxyPreparedStatement.java:67)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:185)

PLEASE FIND THE OLD THREAD FOR THE SAME ISSUE 
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/430b4352-92c9-4a5c-98b5-f96643009453/jdbc-driver-thread-stuck-infinite-while-closing-result-set-locked?forum=sqldataaccess
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/7259e597-8f2a-470a-9612-84e07402e724/jdbc-driver-infinite-loop-when-closing-resultset-pegged-cpu?forum=sqldataaccess

**Comment by cheenamalhotra** [comment]
Hi @manu9729 

I see similar issue reported [here ](http://support.sas.com/kb/45/165.html) and looks like it's JDK related. And I do see you're using **Java 1.8.65** which is an old archived version and may have similar issue. Can you try installing latest updates for JDK 8 and confirm if this issue persists?

Thanks!

**Comment by cheenamalhotra** [comment]
Hi @manu9729 

Do you have any update on this issue? I'm hoping it to get resolved with later versions of JDK 8.

**Comment by manu9729** [comment]
Hi @cheenamalhotra  
I reverted back to jtds driver and it is working fine on the same jdk version . as it wont be possible for me to update the jdk version as of now to test the application .

**Comment by cheenamalhotra** [comment]
Closing this issue for now.
In case the issue doesn't get resolved with upgraded JDK version, let us know again.
