### ISSUE TITLE
BigDecimal Bug

### ISSUE THREAD

**Issue by amirmf** [Microsoft/mssql-jdbc#683]
## Driver version or jar name
 mssql-jdbc-6.4.0.jre8.jar

## SQL Server version
mssql 2016 

## Client operating system
i used ubuntu and windows ....both same response

## Java/JVM version
java version "1.8.0",

## Table schema
default(dbo | public)

## Problem description
i've used BigDecimal() in allover my application and i cant change it to use manual scale method:
and when i want to insert BigDecimal() i got this erroe:
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Error converting data type nvarchar to decimal.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:259)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1547)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:548)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:479)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7344)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2713)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:224)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:204)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:426)
	at bitronix.tm.resource.jdbc.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)

## Expected behavior and actual behavior
As jdbc standard api this your driver should support BigDecimal()

**Comment by cheenamalhotra** [comment]
Hi @amirmf 

I've created a fix for the issue reported above, request you to test and confirm if your application gets fixed with PR #684 . Attached Jars for testing as well.

[mssql-jdbc-PR684.zip](https://github.com/Microsoft/mssql-jdbc/files/1939965/mssql-jdbc-PR684.zip)

**Comment by amirmf** [comment]
now i've got this error 
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The scale must be less than or equal to the precision.

**Comment by cheenamalhotra** [comment]
Hi @amirmf 

I made another push to the [PR](https://github.com/Microsoft/mssql-jdbc/pull/684), please find jars attached here. Please share your repro code, if you still encounter any issues.

[mssql-jdbc-PR684-02.zip](https://github.com/Microsoft/mssql-jdbc/files/1945069/mssql-jdbc-PR684-02.zip)

**Comment by amirmf** [comment]
it got fixed.thanks

**Comment by cheenamalhotra** [comment]
Closing the issue as PR #684 merged.
