### ISSUE TITLE
cannot insert a 100 nanosecond-precision Time objects via bulk copy 

### ISSUE THREAD

**Issue by jpoernomoatsafe** [Microsoft/mssql-jdbc#705]
## Driver version or jar name
mssql-jdbc-6.5.0.jre8-preview.jar

## SQL Server version
2008, 2012, 2014

## Client operating system
Windows 10 Pro

## Java/JVM version
Version 8 update 144 (Oracle)

## Table schema
CREATE TABLE [jpoetest] ([mytime] time(7))

## Problem description
It is possible to insert Time with 100 nanosecond precision via JDBC SQL Statement and a java.sql.Timestamp object:
```
private static final Timestamp MY_TIMESTAMP = new Timestamp(114550L).setNanos(1234567L);

Connection jdbcConnection = getConnection();
PreparedStatement statement = jdbcConnection.prepareStatement("INSERT INTO [jpoetest] ([mytime]) VALUES (?)");
statement.setTimestamp(1, MY_TIMESTAMP);
```
However, when trying to do a similar thing using `ISQLServerBulkRecord` and `SQLServerBulkCopy`, I'm getting this stack trace:

>com.microsoft.sqlserver.jdbc.SQLServerException: Received an invalid column length from the bcp client for colid 1.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:264)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:256)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:108)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:28)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.doInsertBulk(SQLServerBulkCopy.java:1615)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.access$200(SQLServerBulkCopy.java:58)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy$1InsertBulk.doExecute(SQLServerBulkCopy.java:709)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7344)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2713)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.sendBulkLoadBCP(SQLServerBulkCopy.java:739)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeToServer(SQLServerBulkCopy.java:1688)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeToServer(SQLServerBulkCopy.java:669)

This was probably due to the `Timestamp` object that we're passing in rowData array. If I passed a `Time` object instead, insertion will succeed. 
However, a `Time` object cannot hold sub-millisecond precision, while SQL Server supports up to 100-nanosecond precision. 

## Expected behavior and actual behavior
Expected: `SQLServerBulkCopy` should be able to accept Timestamp objects to insert into a Time column to support 100 nanosecond-precision. 

## Repro code
This is roughly what our implementation of `ISQLServerBulkRecord` would return.

```
public class MySQLServerBulkRecord implements ISQLServerBulkRecord {

  private final ResultSetMetaData metaData;

public MySQLServerBulkRecord(Connection jdbcConnection) {
  PreparedStatement statement = jdbcConnection.prepareStatement("SELECT* FROM [jpoetest] WHERE 1=0");
  ResultSet resultSet = statement.executeQuery();
  metaData = resultSet.getMetaData();

@Override 
public Object[] getRowData() throws SQLServerException 
{
  List<Object> rowData = new Arraylist<>();
  rowData.add(MY_TIMESTAMP);
  return rowData.toArray();
}

@Override
public int getColumnType(int i)
{
  return metaData.getColumnType(i); // (returns java.sql.Types.Time = 92 )
}

@Override
public int getPrecision(int i)
{
  return metaData.getPrecision(i); // 16 for myTime column
}

@Override
public int getScale(int i)
{
  return metaData.getScale(i); // 7 for myTime column
}

}
```

**Comment by jpoernomoatsafe** [comment]
I think I've found out what I did wrong, and how this is possibly not a bug. 
my implementation of `ISQLServerBulkRecord` is not properly describing the precision and scale of the java.sql.Timestamp object that is being written. Instead of describing the destination column, the `ISQLServerBulkRecord` should describe the data that is being written. 

With this fix, I was able to write 100 nanosecond precision time and timestamps to `time` and `datetime2` columns. 

I'm still unable to insert `java.sql.Timestamp` objects to `datetime` and `smalldatetime` columns, however. Even after making the changes to precision and scale to `ISQLServerBulkRecord`. 
I'm being met with this stack trace:

```
com.microsoft.sqlserver.jdbc.SQLServerException: Conversion failed when converting date and/or time from character string.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:264)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:256)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:108)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:28)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.doInsertBulk(SQLServerBulkCopy.java:1615)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.access$200(SQLServerBulkCopy.java:58)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy$1InsertBulk.doExecute(SQLServerBulkCopy.java:709)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7344)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2713)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.sendBulkLoadBCP(SQLServerBulkCopy.java:739)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeToServer(SQLServerBulkCopy.java:1688)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeToServer(SQLServerBulkCopy.java:669)
	at COM.safe.fme.jdbc.mssql.BulkCopierFeatureBundler.sendFeatures(BulkCopierFeatureBundler.java:98)
	at COM.safe.fme.jdbc.JdbcWriter.commitTransaction(JdbcWriter.java:652)
	at COM.safe.fme.jdbc.JdbcWriter.close(JdbcWriter.java:193)
```

Is this a bug? 
My repro code is roughly the same as the one I've posted earlier, except when returning Precision and Scale:

```
@Override
public int getPrecision(int i)
{
  return 29; // java.sql.Timestamp
}

@Override
public int getScale(int i)
{
  return 9; // java.sql.Timestamp
}
```

Destination table schema:
CREATE TABLE [jpoetest] ([mydatetime] datetime)

**Comment by peterbae** [comment]
Hi @jpoernomoatsafe, thanks for bringing this issue to our attention. While the user could argue that the driver should truncate the Timestamp objects that have the nanosecond value specified according to the source column's scale, I believe this can also easily be done on the application's end (probably in the getRowData method of the class that implements ISQLServerBulkRecord), and existing applications that implement ISQLServerBulkRecord might already be doing this (if the driver were to implement this, this would be more of a feature enhancement than a bug).

I see that you've already modified your application so that it sends the correct data to the database (I assume you've turned the Timestamp object into a string, then truncated the last 2 numbers so that it has 100 nanosecond precision) - I was going to suggest something similar to this. As for the datetime and smalldatetime data types, they have different scales - datetime supports up to 3 digits, and smalldatetime supports 0 digits after the second (you can refer to page: https://docs.microsoft.com/en-us/sql/t-sql/data-types/date-transact-sql?view=sql-server-2017). This means that you can either use datetime2(7) to achieve 100 nanosecond precision, or you can modify your application so that it truncates your Timestamp object according to the source column (7 digits for time/datetime2, 3 digits for datetime, 0 for smalldatetime and so on).

Please let me know if this answers your question, or if you have any other concerns.

**Comment by jpoernomoatsafe** [comment]
hi @peterbae 
thanks for your reply! 
I took the string conversion approach, and it's good to have it affirmed by your suggestion. 

I'll consider this issue closed as not a bug.
