### ISSUE TITLE
SQLException: Cannot resolve the collation conflict between "SQL_Latin1_General_CP1_CI_AS" and "PERSIAN_100_BIN" in the equal to operation

### ISSUE THREAD

**Issue by amirmf** [Microsoft/mssql-jdbc#727]
## Driver version or jar name
mssql-jdbc-PR684-jre8-02.jar

## SQL Server version
Microsoft SQL Server 2016 

## Client operating system
windows 10

## Java/JVM version
1.8.0

## Table schema
My mssql instance has been installed with collatin SQL_Latin1_General_CP1_CI_AS
but my application's database has been created with Persian_100_BIN collation

## Problem description
when I call this method:
    DatabaseMetaData dbData = connection.getMetaData()
    ikSet1 = dbData.getImportedKeys(null, ed.getSchemaName(), ed.getTableName())

i get this exception:

09:44:36.170 ERROR         main                   o.m.i.e.EntityDbMeta Exception checking to see if foreign key exists for table EMAIL_MESSAGE
com.microsoft.sqlserver.jdbc.SQLServerException: Cannot resolve the collation conflict between "SQL_Latin1_General_CP1_CI_AS" and "Persian_100_BIN" in the equal to operation.
        at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getResultSetForForeignKeyInformation(SQLServerDatabaseMetaData.java:1007) ~[mssql-jdbc-PR684-jre8-02.jar:?]
        at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getImportedKeys(SQLServerDatabaseMetaData.java:878) ~[mssql-jdbc-PR684-jre8-02.jar:?]
        at org.moqui.impl.entity.EntityDbMeta.foreignKeyExists(EntityDbMeta.groovy:504) [moqui-framework-2.1.1-rc2.jar:2.1.1-rc2]
  

## Expected behavior and actual behavior
As you know getImportedKeys method is in jdbc driver and the query is creating in the driver 
i think you should add " collate database_default" to end of the query ( according to this related issue [590](https://github.com/Microsoft/mssql-jdbc/issues/590) )

## Repro code
    DatabaseMetaData dbData = connection.getMetaData()
    ikSet1 = dbData.getImportedKeys(null, ed.getSchemaName(), ed.getTableName())

**Comment by rene-ye** [comment]
Hi @amirmf, the collation issue you mentioned has already been resolved in #677 and is available starting from version 6.5.2-preview of the driver. Please see if the newer version resolves the problems.

**Comment by amirmf** [comment]
thanks.

**Comment by marcos-donato-br** [comment]
Hi... i'm having same problem. Tested with mssql-jdbc-6.5.4.jre8-preview.jar

2019-04-10 20:23:47,853 194938 FINE  (http-/0.0.0.0:8080-5:[class br.com.glr.populis.web.pontoeletronico.action.BatFormAction]) com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getResultSetForForeignKeyInformation(SQLServerDatabaseMetaData.java:1003)com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getExportedKeys(SQLServerDatabaseMetaData.java:840)br.com.glr.populis.jdbc.adapter.DataBaseMetaDataWrapper.getExportedKeys(DataBaseMetaDataWrapper.java:545)br.com.glr.populis.model.database.dao.DataBaseDAOANSI.obterReferenceKeys(DataBaseDAOANSI.java:380)br.com.glr.populis.model.database.ejb.DataBaseSessionFacadeBean.obterReferenceKeys(DataBaseSessionFacadeBean.java:143)br.com.glr.populis.model.database.ejb.DataBaseSessionFacadeBean.obterConstraint(DataBaseSessionFacadeBean.java:187)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53)org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53)org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43)org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47)org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:21)org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:53)org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51)org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInNoTx(CMTTxInterceptor.java:267)org.jboss.as.ejb3.tx.CMTTxInterceptor.supports(CMTTxInterceptor.java:392)org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:247)org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:43)org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64)org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:59)org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:55)org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)org.jboss.as.ee.component.TCCLInterceptor.processInvocation(TCCLInterceptor.java:45)org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:185)org.jboss.as.ee.component.ViewDescription$1.processInvocation(ViewDescription.java:185)org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)org.jboss.as.ee.component.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:73)br.com.glr.populis.model.database.ejb.DataBaseSessionFacadeLocal$$$view135.obterConstraint(Unknown Source)br.com.glr.populis.web.database.delegate.DataBaseBusinessDelegate.obterConstraint(DataBaseBusinessDelegate.java:159)br.com.glr.populis.webcommon.action.AbstractPopulisAction.publishDeleteConstraintException(AbstractPopulisAction.java:291)br.com.glr.populis.webcommon.action.GenericFormMaintenanceAction.executeAction(GenericFormMaintenanceAction.java:112)br.com.glr.populis.webcommon.action.AbstractPopulisAction.execute(AbstractPopulisAction.java:187)org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:419)org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:224)org.apache.struts.action.ActionServlet.process(ActionServlet.java:1196)br.com.glr.populis.webcommon.controller.servlet.PopulisServlet.process(PopulisServlet.java:90)org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:432)javax.servlet.http.HttpServlet.service(HttpServlet.java:754)javax.servlet.http.HttpServlet.service(HttpServlet.java:847)org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)br.com.glr.populis.webcommon.controller.filter.LogFilter.doFilter(LogFilter.java:28)org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231)org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:150)org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:854)org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926)java.lang.Thread.run(Thread.java:748)

**Comment by marcos-donato-br** [comment]
Hi. tested with mssql-jdbc-6.5.4.jre8-preview.jar and it works well
