### ISSUE TITLE
FAILURE IN JUNIT TEST CASE DUE TO ENCRYPTION 

### ISSUE THREAD

**Issue by vijjusree** [Microsoft/mssql-jdbc#751]
## Driver version or jar name
<groupId>com.microsoft.sqlserver</groupId>
                                 <artifactId>mssql-jdbc</artifactId>
                                 <version>6.5.1.jre8-preview</version>
                                 <type>jar</type>
                             </dependency> 

## SQL Server version
Microsoft SQL Server 2016 (SP1-GDR) (KB4057118) - 13.0.4210.6 (X64)  

## Client operating system
WINDOWS 

## Java/JVM version
"1.8.0_171"

## Problem description
junit is failing due to change in functionality for encryption removed colence and concat for phone_number and foreign_phone_number . There are two different  parameters that are passing and one method is executing 2 value where as one method expecting 1, this two query execute same method 

## Expected behavior and actual behavior
JUNIT should pass without change but Need to know what conditionit can it passes 

##SQL QUERY FOR FAILING CustomerQueryJoinedData()
Select cust.COMPANY
, cust.OPERATIONS_AREA
, cust.CUSTOMER_ID
, cust.CUSTOMER_NUMBER
, cust.OBJECT_TYPE_CODE
, cust.SEARCH_NAME
, cust.PREVIOUS_SEARCH_NAME
, cust.SSN
, cust.TAX_IDENTIFIER
, cust.LEGAL_REPORTING_TYPE
, cust.LEGAL_TYPE
, addr.CITY
, addr.STATE
, addr.POSTAL_CODE
, MIN(COALESCE(phone.AREA_CODE
, ''))  area_code
, phone.PHONE_NUMBER  PHONE_NUMBER
, phone.FOREIGN_PHONE_NUMBER FOREIGN_PHONE_NUMBER
, cust.STATUS
, cust.PREVIOUS_CUSTOMER_NUMBER
, cust.ORIGINAL_CUSTOMER_NUMBER 
, cust.GROUP_CODE
, cust.DEALER_USAGE_TYPE from S_CUSTOMER_E49 cust  
inner join (select CITY
, STATE
, POSTAL_CODE
, CUSTOMER_ID
, ADDRESS_ID
, IS_PRIMARY
, SEARCH_CITY
, SEARCH_ADDRESS from S_ADDRESS_E01) addr on addr.CUSTOMER_ID = cust.CUSTOMER_ID 
left outer join (select AREA_CODE
, PHONE_NUMBER
, FOREIGN_PHONE_NUMBER
, CUSTOMER_ID
, PHONE_NUMBER_ID from S_PHONE_NUMBER_E18) phone on phone.CUSTOMER_ID = cust.CUSTOMER_ID where cust.CUSTOMER_NUMBER =  321999
  and  addr.address_id = (Select min(addr1.address_id) from S_ADDRESS_E01 addr1 where addr1.CUSTOMER_ID = cust.CUSTOMER_ID  )  
group by 	cust.COMPANY
, cust.OPERATIONS_AREA
,cust.CUSTOMER_ID
, cust.CUSTOMER_NUMBER
, cust.OBJECT_TYPE_CODE
, cust.SEARCH_NAME
, cust.PREVIOUS_SEARCH_NAME
, cust.SSN
, cust.TAX_IDENTIFIER
,	cust.LEGAL_TYPE
, cust.LEGAL_REPORTING_TYPE
, addr.CITY
, addr.STATE
, addr.POSTAL_CODE
, cust.STATUS
, cust.PREVIOUS_CUSTOMER_NUMBER
, cust.ORIGINAL_CUSTOMER_NUMBER 
, cust.GROUP_CODE 
, cust.DEALER_USAGE_TYPE 
, phone.PHONE_NUMBER
, phone.FOREIGN_PHONE_NUMBER 
 order by  cust.SEARCH_NAME
,cust.customer_number 
;

##SQL CustomerQueryDenormalizedData():
Select cust.COMPANY
, cust.OPERATIONS_AREA
, cust.CUSTOMER_ID
, cust.CUSTOMER_NUMBER
, cust.OBJECT_TYPE_CODE
, cust.SEARCH_NAME
, cust.PREVIOUS_SEARCH_NAME
, cust.SSN
, cust.TAX_IDENTIFIER
, cust.LEGAL_REPORTING_TYPE
, cust.LEGAL_TYPE
, CITY
, STATE
, POSTAL_CODE
, area_code
,  PHONE_NUMBER
,  FOREIGN_PHONE_NUMBER
, cust.STATUS
, cust.PREVIOUS_CUSTOMER_NUMBER
, cust.ORIGINAL_CUSTOMER_NUMBER 
, cust.GROUP_CODE
, cust.DEALER_USAGE_TYPE from D_CUSTOMER_SEARCH cust  where cust.CUSTOMER_NUMBER =  321999  order by  cust.SEARCH_NAME
,cust.customer_number 

JUNIT METHOD :

        doCustomerQueryByCustomerNumber(new CustomerQueryJoinedData());
       doCustomerQueryByCustomerNumber(new CustomerQueryDenormalizedData());
        
public void doCustomerQueryByCustomerNumber(CustomerQuery customerQuery) throws Exception {

		customerQuery.setCustomerNumber(customer.getNumber().toString());
		List result = queryDao.executeQuery(customerQuery);
		assertNotNull("Query result not null", result);
		assertEquals("Query result size",2,result.size());
		 
}

Even though I change the values it is showing same error because two queries executing same query 

ERROR TRACE 
junit.framework.AssertionFailedError: Query result size expected:<2> but was:<1>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:282)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:201)

**Comment by rene-ye** [comment]
Hi @vijjusree, this doesn't look like one of the Junit tests part of the mssql-jdbc repository. This also doesn't look like a driver error as much as a test/configuration error. We will require the source code of these tests to assist you further.

**Comment by cheenamalhotra** [comment]
Hi @vijjusree, does this issue still occur for you? 
Let us know in a repro code how we can reproduce the error in order to provide you a fix.

**Comment by cheenamalhotra** [comment]
Closing issue due to inactivity.
