### ISSUE TITLE
NullPointerException after upgrading JDBC-driver from 6.4 to 7.0

### ISSUE THREAD

**Issue by christophs78** [Microsoft/mssql-jdbc#788]
## Driver version or jar name
mssql-jdbc-7.0.0.jre8.jar

## SQL Server version
13.0.4001.0

## Client operating system
Windows 10 1709 
(But i think it does not matter.)

## Java/JVM version
Java HotSpot(TM) 64-Bit Server VM, Version 1.8.0_171-b1 (Oracle)
(But i think it does not matter.)

## Table schema
Sorting: Latin1_general_CI_AS
Compatibility: SQL Server 2012 (110)

## Problem description
Caused by: java.lang.NullPointerException
	at com.microsoft.sqlserver.jdbc.SQLServerClobBase.length(SQLServerClob.java:388)
	at com.microsoft.sqlserver.jdbc.SQLServerClob.length(SQLServerClob.java:97)
	at org.hibernate.type.descriptor.java.DataHelper.determineLengthForBufferSizing(DataHelper.java:285)
	at org.hibernate.type.descriptor.java.DataHelper.extractString(DataHelper.java:264)
	...
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1445)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1414)
	at org.hibernate.query.Query.getResultList(Query.java:146)
	at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getResultList(CriteriaQueryTypeQueryAdapter.java:72)
	...
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy146.findAllByOrderByServiceNameAsc(Unknown Source)
	at iete.view.RecordIssueView.init(RecordIssueView.java:45)

There was a change in SQLServerClobBase.length with Version 7.0.
[https://github.com/Microsoft/mssql-jdbc/commit/b60068c1d92e01f7d62658bad36a0ea0acca48d4](https://github.com/Microsoft/mssql-jdbc/commit/b60068c1d92e01f7d62658bad36a0ea0acca48d4)

## Expected behavior and actual behavior
NullPointerException should not be thrown.

## Repro code
Database-View:
![grafik](https://user-images.githubusercontent.com/10461942/44728766-81faed00-aadd-11e8-909c-77309f215513.png)

JPA-Model-Class:
```
package iete.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

/**
 * The persistent class for the lrg_services_extern_v database table.
 * 
 */
@Entity
@Table(name = "lrg_services_extern_v")
@Getter
@Setter
public class IetServicesExtern implements Serializable {

	private static final long serialVersionUID = 1L;

	@Column(name = "service")
	private String serviceName;

	@Column(name = "service_id")
	@Id
	private int serviceId;

	@Lob
	@Column(name = "service_txt")
	private String serviceTxt;
}
```

SpringData-Repository:
```
/**
 * Spring Data JPA Repository für {@link iete.model.IetServicesExtern}.
 */
public interface IetServicesExternRepository
		extends PagingAndSortingRepository<IetServicesExtern, Integer>, JpaRepository<IetServicesExtern, Integer> {

	public List<IetServicesExtern> findAllByOrderByServiceNameAsc();
}
```

**Comment by rene-ye** [comment]
Hi @christophs78, I wasn't able to create an exact repro described in the issue, but I was able to reproduce the error. I believe the underlying cause for both the errors are the same, and have made a fix to the driver. Can you test these new jars and see if it solves the problem?
[Fixed Jars.zip](https://github.com/Microsoft/mssql-jdbc/files/2332943/Fixed.Jars.zip)

**Comment by christophs78** [comment]
Hi @rene-ye!

Thank´s for your update!
I´m sorry, the fixed Driver JAR creates an other exception.
```
Caused by: org.springframework.orm.jpa.JpaSystemException: IOException occurred reading text; nested exception is org.hibernate.HibernateException: IOException occurred reading text
...
Caused by: java.io.IOException: The stream is closed.
```
(Full Stacktrace further down.)

I´ll try to build a sandbox-eclipse-project for this issue. (Hibernate without Spring) Would this help?

Kind regards,

Christoph

---------
```
Caused by: org.springframework.orm.jpa.JpaSystemException: IOException occurred reading text; nested exception is org.hibernate.HibernateException: IOException occurred reading text
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:314)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:225)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:527)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy111.findAllByOrderByServiceNameAsc(Unknown Source)
	at iete.view.RecordIssueView.init(RecordIssueView.java:45)
	at sun.reflect.GeneratedMethodAccessor950.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:308)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135)
	... 140 more
Caused by: org.hibernate.HibernateException: IOException occurred reading text
	at org.hibernate.type.descriptor.java.DataHelper.extractString(DataHelper.java:79)
	at org.hibernate.type.descriptor.java.DataHelper.extractString(DataHelper.java:267)
	at org.hibernate.type.descriptor.java.StringTypeDescriptor.wrap(StringTypeDescriptor.java:75)
	at org.hibernate.type.descriptor.java.StringTypeDescriptor.wrap(StringTypeDescriptor.java:22)
	at org.hibernate.type.descriptor.sql.ClobTypeDescriptor$1.doExtract(ClobTypeDescriptor.java:44)
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:261)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:247)
	at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:333)
	at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:2868)
	at org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1747)
	at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1673)
	at org.hibernate.loader.Loader.getRow(Loader.java:1562)
	at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:732)
	at org.hibernate.loader.Loader.processResultSet(Loader.java:991)
	at org.hibernate.loader.Loader.doQuery(Loader.java:949)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:341)
	at org.hibernate.loader.Loader.doList(Loader.java:2692)
	at org.hibernate.loader.Loader.doList(Loader.java:2675)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2507)
	at org.hibernate.loader.Loader.list(Loader.java:2502)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:502)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:392)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1490)
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1445)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1414)
	at org.hibernate.query.Query.getResultList(Query.java:146)
	at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getResultList(CriteriaQueryTypeQueryAdapter.java:72)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:129)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:91)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:136)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:125)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:590)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:578)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	... 155 more
Caused by: java.io.IOException: The stream is closed.
	at com.microsoft.sqlserver.jdbc.BaseInputStream.checkClosed(SimpleInputStream.java:95)
	at com.microsoft.sqlserver.jdbc.SimpleInputStream.read(SimpleInputStream.java:284)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.BufferedReader.fill(Unknown Source)
	at java.io.BufferedReader.read1(Unknown Source)
	at java.io.BufferedReader.read(Unknown Source)
	at org.hibernate.type.descriptor.java.DataHelper.extractString(DataHelper.java:71)
	... 197 more
```

**Comment by christophs78** [comment]
Eclipse-Sandbox-Projekt:
[IssueReproSqlServerJdbcClob.zip](https://github.com/Microsoft/mssql-jdbc/files/2336324/IssueReproSqlServerJdbcClob.zip)

It uses gradle (build.gradle) to load dependencies. (hibernate and mssql-jdbc) Remove the mssql-jdbc-dependency to test against your own version of the jdbc-driver. Adapt persistence.xml to connect to your database.
Hope this project is straight-forward and easy to understand.

**Comment by rene-ye** [comment]
Hi @christophs78, the sandbox reproduction you provided works and I can confirm the error on my end. I've updated the change and provided an initial version of the fix below. Please see if it resolves the issue.
[Fixed Jars.zip](https://github.com/Microsoft/mssql-jdbc/files/2338213/Fixed.Jars.zip)

**Comment by christophs78** [comment]
Yes, it resolves the issue. :-)

**Comment by hittor** [comment]
I have encountered the same problem, thanks to @rene-ye , can you tell us the release date of the final version of 7.1.1?

**Comment by rene-ye** [comment]
7.1.1 will be released when all its milestones are completed.

**Comment by rene-ye** [comment]
#799 has been merged and will be available starting from the next preview release. Closing the issue.
