### ISSUE TITLE
setQueryTimeout not works when bulk copy to Azure Data Warehouse

### ISSUE THREAD

**Issue by tilumi** [Microsoft/mssql-jdbc#803]
## Driver version
7.0.0.jre8

## SQL Server version
Azure SQL Data Warehouse Gen1

## Client Operating System
Ubuntu

## JAVA/JVM version
1.8

## Problem description
I use `insertStatement.setQueryTimeout(10 * 60)` to set timeout

1. Expected behaviour: Timeout exception will be thrown after 10 mins
2. Actual behaviour:
Timeout exception thrown only after 1 min, like this:
![screenshot 2018-09-18 14 59 14](https://user-images.githubusercontent.com/734766/45669725-7e460d80-bb53-11e8-8d6b-69f3443a0a2e.png)
3. Error message/stack trace:
```
2018-09-18 06:54:33 Executor task launch worker for task 486 ERROR Executor:91 - Exception in task 162.0 in stage 9.0 (TID 486)
java.sql.BatchUpdateException: The query has timed out.
	at com.shaded.com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:2022)
	at com.microsoft.antispam.outputWriters.SQLDataWarehouseWriter$$anonfun$5$$anonfun$apply$1$$anonfun$6.apply(SQLDataWarehouseWriter.scala:89)
	at com.microsoft.antispam.outputWriters.SQLDataWarehouseWriter$$anonfun$5$$anonfun$apply$1$$anonfun$6.apply(SQLDataWarehouseWriter.scala:89)
	at scala.util.Try$.apply(Try.scala:192)
```

**Comment by peterbae** [comment]
Hi @tilumi, thanks for reporting this issue. The team has confirmed that this was not the intended behavior, and we'll be pushing a fix for this soon. We will let you know when we have an update.

**Comment by tilumi** [comment]
Ok, thanks a lot

**Comment by peterbae** [comment]
Hi @tilumi, I've made PR #817 to fix this issue. In the meantime, I've created this jar for you to use. Please let me know if this jar solves your problem.

[issue-803-fix.zip](https://github.com/Microsoft/mssql-jdbc/files/2435621/issue-803-fix.zip)
