### ISSUE TITLE
[BUG] issue in prepared statement with single quote for contains near query

### ISSUE THREAD

**Issue by findtanmayray** [Microsoft/mssql-jdbc#932]
## Driver version

7.0.0.jre8
## SQL Server version

Microsoft SQL Server 2017 (RTM-CU3-GDR) (KB4052987) - 14.0.3015.40 (X64) 	Dec 22 2017 16:13:22 	Copyright (C) 2017 Microsoft Corporation	Enterprise Edition (64-bit) on Linux (Ubuntu 16.04.3 LTS)
## Client Operating System

Macos-10.13.6
## JAVA/JVM version

jre8
## Table schema

Test
## Problem description

1. Expected behaviour: The query should return rows where the condition meets.
2. Actual behaviour:
Getting exception. The driver does not recognise ? as parameter place holder.
3. Error message/stack trace:
Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: The index 1 is out of range.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:226)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.setterGetParam(SQLServerPreparedStatement.java:1110)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.setValue(SQLServerPreparedStatement.java:1124)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.setString(SQLServerPreparedStatement.java:1669)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setString(HikariProxyPreparedStatement.java)
4. Any other details that can be helpful:

## JDBC trace logs

I am using slf4j for logging, tried to add logging for microsoft package in logback.xml, but could not find any logs coming in console log. Anyway the issue is straight forward to reproduce with a full text search enabled column in database and creating preparedstatement like below.

## Reproduction code

//Datasource code in spring bean
public DataSource dataSource(DaFulfillmentSQLServerConfig config) {
		
		Properties props = new Properties();
		props.setProperty("dataSourceClassName", "com.microsoft.sqlserver.jdbc.SQLServerDataSource");
		props.setProperty("dataSource.user", config.getUser());
		props.setProperty("dataSource.portNumber", config.getPortNumber());
		props.setProperty("dataSource.password", config.getPassword());
		props.setProperty("dataSource.databaseName", config.getDatabaseName());
		HikariConfig connectionPoolConfig = new HikariConfig(props);
		
		HikariDataSource dataSource = new HikariDataSource(connectionPoolConfig);

		return dataSource;
	}
//in main method, the table has full text search enabled on items column. And the sample row value is 
// [{"plannedItemId":43,"itemDescription":"Milk"}]
DataSource ds = context.getBean(DataSource.class);
		Connection connection = ds.getConnection();
		PreparedStatement ps = connection.prepareStatement("select * from inventory where contains(items,'NEAR((?,?),1,TRUE)')");
		ps.setString(1, "plannedItemId");
		ps.setInt(2, 43);

**Comment by findtanmayray** [comment]
I noticed in com.microsoft.sqlserver.jdbc.ParameterUtils, scanSQLForChar method treats all single quote as comment, but then how we are supposed to run contains(<column_name>,'NEAR(..)') queries?

**Comment by cheenamalhotra** [comment]
Hi @findtanmayray 

SQL Server always treats text between single quotes `' '` as literals/constant string value. Variables/Parameters can only be passed to replace this string.

In your case, you can do something like:
```java //
String sql = "select * from inventory where contains(items,?)";
PreparedStatement ps = connection.prepareStatement(sql);
ps.setString(1, "NEAR((" + val1 + "," + val2 + "),1,TRUE)");
ps.executeUpdate();
```

**Comment by findtanmayray** [comment]
@cheenamalhotra did you try the query? Because I am still getting error.
String val1 = "plannedItemId";
Integer val2 =43;
PreparedStatement ps = connection.prepareStatement("select * from fulfillment_summary where contains(items,?");
ps.setString(1, "NEAR((" + val1 + "," + val2 + "),1,TRUE)");
System.out.println(ps.executeQuery().next());

I got below error :
Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near '@P0'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:254)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1608)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:578)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:508)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7240)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2869)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:243)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:218)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:434)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)

**Comment by findtanmayray** [comment]
Thanks a lot @cheenamalhotra ..this worked like a charm.
