### ISSUE TITLE
[BUG] No suitable driver found despite driver being present in local maven repo

### ISSUE THREAD

**Issue by SoucianceEqdamRashti** [Microsoft/mssql-jdbc#997]
I am working an azure java function v2 where I need to connec to an azure sql db.
I have followed the steps here:
https://docs.microsoft.com/en-us/azure/sql-database/sql-database-connect-query-java
I am using driver version 7.2.1.jre8 and have used 7.0.0.jre8
The driver exist in my local maven repository and in my pom file. 

However when I start the function and this the error I get the error seen below. No matter how I try to configure it in Intellij and in the code I always get this error. It is as if it does not found the driver for some reason. Here is the main part of the code. I do not use any Class.forName statements as seen in the link above. I am bit lost on options and how to verify if there is something wrong on my side. Any hints ands would be extremely appreciated. 
```
 try {
            connection = DriverManager.getConnection(url);
            String schema = connection.getSchema();
            System.out.println("Successful connection - Schema: " + schema);
```

```
 java.sql.SQLException: No suitable driver found for jdbc:sqlserver://server:1433;database=db;user=myuser@server;password=mypassword;encrypt=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
[3/19/2019 4:43:59 PM] Request received to search for items received
[3/19/2019 4:43:59 PM] 	at java.sql.DriverManager.getConnection(DriverManager.java:689)
[3/19/2019 4:43:59 PM] 	at java.sql.DriverManager.getConnection(DriverManager.java:270)
[3/19/2019 4:43:59 PM] 	at org.alfalaval.integrations.partfinder.PartFinderDB.getRows(PartFinderSearch.java:52)
[3/19/2019 4:43:59 PM] 	at org.alfalaval.integrations.partfinder.PartFinderSearch.run(PartFinderSearch.java:30)
[3/19/2019 4:43:59 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[3/19/2019 4:43:59 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[3/19/2019 4:43:59 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[3/19/2019 4:43:59 PM] 	at java.lang.reflect.Method.invoke(Method.java:498)
[3/19/2019 4:43:59 PM] 	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
[3/19/2019 4:43:59 PM] 	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:54)
[3/19/2019 4:43:59 PM] 	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:51)
[3/19/2019 4:43:59 PM] 	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[3/19/2019 4:43:59 PM] 	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[3/19/2019 4:43:59 PM] 	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[3/19/2019 4:43:59 PM] 	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[3/19/2019 4:43:59 PM] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[3/19/2019 4:43:59 PM] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[3/19/2019 4:43:59 PM] Function "PartFinderSearch" (Id: ce633691-2b49-4995-948a-d0fa2cf2264b) invoked by Java Worker
[3/19/2019 4:43:59 PM] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[3/19/2019 4:43:59 PM] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[3/19/2019 4:43:59 PM] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rene-ye** [comment]
Have you registered the driver?
```java
DriverManager.registerDriver(new com.microsoft.sqlserver.jdbc.SQLServerDriver());
```

**Comment by SoucianceEqdamRashti** [comment]
No I haven't but neither did the code example from Microsoft in the link.
Is that then required? To register it manually?

**Comment by rene-ye** [comment]
It's not mandatory, but it's required if the driver hasn't been specifically added to the project's classpath.

**Comment by SoucianceEqdamRashti** [comment]
@rene-ye , I tried both but get the same error which is that the package com.microsoft.sqlserver.jdbc.SQLServerDriver does not exist. I am guessing something is wrong with my projects. Thanks for the help.

**Comment by SoucianceEqdamRashti** [comment]
Something was seriously wrong with my Intellij setup. Even after uninstalling it didn't fetch the com.microsoft.sqlserver dependencies correctly. Eclipse did it fine and that solved it.

**Comment by ManikantaNvsr** [comment]
I see a strange behavior. We have been using the code for the past two months. I haven't used `Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver").getConstructor().newInstance();` but it worked fine. 

Now, It gives an error("No suitable driver found") when I execute the application through the JAR. I don't get this error when I run through the Eclipse. Can you please help me on what went wrong?
